# Train-only split ablation: inference vs fine-tuned retrieval vs learned EdgeMLP

This notebook creates an **internal train/test split** using **only** `data/train/` and compares clustering quality across:

1) **Inference-only**: pretrained backbone embeddings + cosine edge weights (no trained checkpoints)
2) **Fine-tuned DINO embeddings**: retrieval fine-tuning on the train split + cosine edges
3) **Fine-tuned + EdgeMLP**: fine-tuned embeddings + learned EdgeMLP edge scoring
4) **Everything**: (2)+(3) **plus hyperparameter selection** on the train split, then evaluated on the test split

Metrics reported (per dataset + overall):
- **mAA** (scene recall under greedy scene↔cluster assignment)
- **Clustering Score** (precision under the same assignment)
- **Final Score** (harmonic mean)

In [19]:
from __future__ import annotations

import json
import os
import sys
import shlex
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, Optional, Tuple

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.io as pio
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.metrics import average_precision_score, roc_auc_score
from sklearn.neighbors import NearestNeighbors
from tqdm.auto import tqdm


def _find_repo_root() -> Path:
    p = Path.cwd().resolve()
    while p != p.parent:
        if (p / "src").exists() and (p / "pyproject.toml").exists():
            return p
        p = p.parent
    raise RuntimeError("Could not find repo root (expected src/ and pyproject.toml)")


REPO_ROOT = _find_repo_root()
os.chdir(REPO_ROOT)
print("REPO_ROOT:", REPO_ROOT)

pio.templates.default = "plotly_white"


def run(cmd: list[str], *, env: dict[str, str] | None = None) -> None:
    print("+", shlex.join(cmd), flush=True)
    subprocess.run(cmd, check=True, cwd=str(REPO_ROOT), env=env)

REPO_ROOT: /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025

## 1) Split `data/train/` into internal train/test

**Test datasets**: `ETs`, `pt_sacrecoeur_trevi_tajmahal`, `pt_stpeters_stpauls`  
**Train datasets**: everything else under `data/train/`.

In [20]:
DATA_TRAIN_ROOT = REPO_ROOT / "data" / "train"
TRAIN_LABELS = REPO_ROOT / "data" / "train_labels.csv"

TEST_DATASETS = [
    "ETs",
    "pt_sacrecoeur_trevi_tajmahal",
    "pt_stpeters_stpauls",
]
TEST_DATASETS_SET = set(TEST_DATASETS)

SPLIT_TAG = "holdout_ets_sacrecoeur_stpeters"
TRAIN_SPLIT_ROOT = REPO_ROOT / "data" / f"train_split_{SPLIT_TAG}"
TEST_SPLIT_ROOT = REPO_ROOT / "data" / f"test_split_{SPLIT_TAG}"

TRAIN_SPLIT_LABELS = REPO_ROOT / "data" / f"train_split_labels_{SPLIT_TAG}.csv"
TEST_SPLIT_LABELS = REPO_ROOT / "data" / f"test_split_labels_{SPLIT_TAG}.csv"

OVERWRITE_SPLIT = False


def _symlink_dir(src: Path, dst: Path, *, overwrite: bool) -> None:
    if dst.exists() or dst.is_symlink():
        if not overwrite:
            return
        if dst.is_symlink() or dst.is_file():
            dst.unlink()
        else:
            # Directory: remove only if it's inside our split roots.
            for p in sorted(dst.rglob("*"), reverse=True):
                if p.is_symlink() or p.is_file():
                    p.unlink()
                elif p.is_dir():
                    p.rmdir()
            dst.rmdir()
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.symlink_to(src, target_is_directory=True)


assert DATA_TRAIN_ROOT.exists(), f"Missing {DATA_TRAIN_ROOT}"
assert TRAIN_LABELS.exists(), f"Missing {TRAIN_LABELS}"

all_datasets = sorted([p.name for p in DATA_TRAIN_ROOT.iterdir() if p.is_dir()])
train_datasets = [d for d in all_datasets if d not in TEST_DATASETS_SET]
test_datasets = [d for d in all_datasets if d in TEST_DATASETS_SET]
print("datasets in data/train:", len(all_datasets))
print("train datasets:", train_datasets)
print("test datasets:", test_datasets)

TRAIN_SPLIT_ROOT.mkdir(parents=True, exist_ok=True)
TEST_SPLIT_ROOT.mkdir(parents=True, exist_ok=True)
for ds in train_datasets:
    _symlink_dir(DATA_TRAIN_ROOT / ds, TRAIN_SPLIT_ROOT / ds, overwrite=OVERWRITE_SPLIT)
for ds in test_datasets:
    _symlink_dir(DATA_TRAIN_ROOT / ds, TEST_SPLIT_ROOT / ds, overwrite=OVERWRITE_SPLIT)

labels = pd.read_csv(TRAIN_LABELS)
labels_train = labels[labels["dataset"].isin(train_datasets)].copy()
labels_test = labels[labels["dataset"].isin(test_datasets)].copy()

if OVERWRITE_SPLIT or (not TRAIN_SPLIT_LABELS.exists()):
    labels_train.to_csv(TRAIN_SPLIT_LABELS, index=False)
if OVERWRITE_SPLIT or (not TEST_SPLIT_LABELS.exists()):
    labels_test.to_csv(TEST_SPLIT_LABELS, index=False)

(REPO_ROOT / "data" / f"split_info_{SPLIT_TAG}.json").write_text(
    json.dumps(
        {
            "split_tag": SPLIT_TAG,
            "source": str(DATA_TRAIN_ROOT),
            "train_root": str(TRAIN_SPLIT_ROOT),
            "test_root": str(TEST_SPLIT_ROOT),
            "train_labels": str(TRAIN_SPLIT_LABELS),
            "test_labels": str(TEST_SPLIT_LABELS),
            "train_datasets": train_datasets,
            "test_datasets": test_datasets,
        },
        indent=2,
    )
)
print("[ok] split ready")
print("TRAIN_SPLIT_ROOT:", TRAIN_SPLIT_ROOT)
print("TEST_SPLIT_ROOT:", TEST_SPLIT_ROOT)
print("TRAIN_SPLIT_LABELS:", TRAIN_SPLIT_LABELS)
print("TEST_SPLIT_LABELS:", TEST_SPLIT_LABELS)

datasets in data/train: 13
train datasets: ['amy_gardens', 'fbk_vineyard', 'imc2023_haiper', 'imc2023_heritage', 'imc2023_theather_imc2024_church', 'imc2024_dioscuri_baalshamin', 'imc2024_lizard_pond', 'pt_brandenburg_british_buckingham', 'pt_piazzasanmarco_grandplace', 'stairs']
test datasets: ['ETs', 'pt_sacrecoeur_trevi_tajmahal', 'pt_stpeters_stpauls']
[ok] split ready
TRAIN_SPLIT_ROOT: /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/data/train_split_holdout_ets_sacrecoeur_stpeters
TEST_SPLIT_ROOT: /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/data/test_split_holdout_ets_sacrecoeur_stpeters
TRAIN_SPLIT_LABELS: /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/data/train_split_labels_holdout_ets_sacrecoeur_stpeters.csv
TEST_SPLIT_LABELS: /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/data/test_split_labels_holdout_ets_sacrecoeur_stpeters.csv

## 2) Scoring utilities (mAA / Clustering Score / Final)

We score each dataset with a greedy **one-to-one** scene↔cluster assignment that prioritizes mAA (ties broken by clustering score).

In [21]:
def _image_keys_in_dir(ds_dir: Path) -> set[str]:
    if not ds_dir.exists():
        return set()
    out = set()
    for p in ds_dir.iterdir():
        if p.is_file() or p.is_symlink():
            if p.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tif", ".tiff"}:
                out.add(p.stem)
    return out


def normalize_image_key(dataset: str, *, image_id: Optional[str] = None, image: Optional[str] = None) -> str:
    if isinstance(image, str) and image.strip() and image.lower() != "nan":
        return Path(image).stem
    if not isinstance(image_id, str) or not image_id.strip():
        raise ValueError("Need either `image` or `image_id` to derive an image key")
    s = image_id.strip()
    if s.endswith("_public") or s.endswith("_private"):
        s = s.rsplit("_", 1)[0]
    prefix = f"{dataset}_"
    if s.startswith(prefix):
        s = s[len(prefix) :]
    return Path(s).stem


def load_ground_truth(*, labels_csv: Path, data_root: Path, drop_outliers_scene: bool) -> Tuple[Dict[str, Dict[str, set[str]]], Dict[str, set[str]]]:
    gt = pd.read_csv(labels_csv)
    required = {"dataset", "scene", "image"}
    missing = required - set(gt.columns)
    if missing:
        raise ValueError(f"Ground truth missing columns: {sorted(missing)}")

    gt = gt[["dataset", "scene", "image"]].copy()
    if drop_outliers_scene:
        gt = gt[gt["scene"].astype(str).str.lower() != "outliers"].copy()
    gt["image_key"] = gt["image"].map(lambda x: Path(str(x)).stem)

    scenes: Dict[str, Dict[str, set[str]]] = {}
    for (dataset, scene), g in gt.groupby(["dataset", "scene"], sort=True):
        scenes.setdefault(str(dataset), {})[str(scene)] = set(g["image_key"].tolist())

    all_images: Dict[str, set[str]] = {}
    for dataset in sorted(scenes.keys()):
        keys = _image_keys_in_dir(data_root / dataset)
        if not keys:
            keys = set(gt.loc[gt["dataset"] == dataset, "image_key"].tolist())
        all_images[dataset] = keys

    return scenes, all_images


def load_predictions(*, pred_csv: Path, expected_images: Dict[str, set[str]], outliers_label: str = "outliers") -> Dict[str, Dict[str, set[str]]]:
    df = pd.read_csv(pred_csv)
    cols = set(df.columns)
    if "dataset" not in cols:
        raise ValueError("Predictions CSV must contain a `dataset` column")

    cluster_col = None
    for c in ["scene", "cluster", "cluster_label"]:
        if c in cols:
            cluster_col = c
            break
    if cluster_col is None:
        raise ValueError("Predictions CSV must contain one of: scene / cluster / cluster_label")

    image_col = "image" if "image" in cols else None
    image_id_col = "image_id" if "image_id" in cols else None
    if image_col is None and image_id_col is None:
        raise ValueError("Predictions CSV must contain `image` or `image_id`")

    df = df[["dataset", cluster_col] + ([image_col] if image_col else []) + ([image_id_col] if image_id_col else [])].copy()
    df = df.rename(columns={cluster_col: "pred_cluster"})

    def _row_to_key(r) -> str:
        return normalize_image_key(
            str(r["dataset"]),
            image_id=str(r[image_id_col]) if image_id_col and pd.notna(r[image_id_col]) else None,
            image=str(r[image_col]) if image_col and pd.notna(r[image_col]) else None,
        )

    df["image_key"] = df.apply(_row_to_key, axis=1)

    kept = []
    for dataset, g in df.groupby("dataset", sort=False):
        exp = expected_images.get(str(dataset), set())
        kept.append(g[g["image_key"].isin(exp)] if exp else g)
    df = pd.concat(kept, ignore_index=True) if kept else df

    rows_missing = []
    for dataset, exp in expected_images.items():
        present = set(df.loc[df["dataset"] == dataset, "image_key"].tolist())
        missing = sorted(exp - present)
        rows_missing.extend({"dataset": dataset, "pred_cluster": outliers_label, "image_key": k} for k in missing)
    if rows_missing:
        df = pd.concat([df, pd.DataFrame(rows_missing)], ignore_index=True)

    pred: Dict[str, Dict[str, set[str]]] = {}
    for (dataset, cluster), g in df.groupby(["dataset", "pred_cluster"], sort=True):
        pred.setdefault(str(dataset), {})[str(cluster)] = set(g["image_key"].tolist())
    return pred


def harmonic_mean(a: float, b: float) -> float:
    if a <= 0 or b <= 0:
        return 0.0
    return 2.0 / (1.0 / a + 1.0 / b)


@dataclass(frozen=True)
class DatasetScore:
    dataset: str
    mAA: float
    clustering_score: float
    final_score: float
    n_scenes: int
    n_images_in_scenes: int
    n_correct: int
    n_cluster_images_summed: int


def score_dataset(*, dataset: str, gt_scenes: Dict[str, set[str]], pred_clusters: Dict[str, set[str]], outliers_label: str = "outliers") -> Tuple[DatasetScore, pd.DataFrame]:
    candidates = {k: v for k, v in pred_clusters.items() if k != outliers_label and len(v) > 0}

    edges: list[tuple[float, float, int, int, str, str]] = []
    for scene, scene_imgs in gt_scenes.items():
        n_scene = len(scene_imgs)
        if n_scene <= 0:
            continue
        for c_label, c_imgs in candidates.items():
            inter = len(scene_imgs & c_imgs)
            if inter <= 0:
                continue
            n_cluster = len(c_imgs)
            maa = inter / n_scene
            cs = inter / n_cluster if n_cluster else 0.0
            edges.append((maa, cs, int(inter), -int(n_cluster), str(scene), str(c_label)))

    edges.sort(key=lambda x: (x[0], x[1], x[2], x[3]), reverse=True)

    assigned_scene: dict[str, tuple[str, int, float, float, int]] = {}
    used_clusters: set[str] = set()
    for maa, cs, inter, neg_n_cluster, scene, c_label in edges:
        if scene in assigned_scene:
            continue
        if c_label in used_clusters:
            continue
        assigned_scene[scene] = (c_label, int(inter), float(maa), float(cs), int(-neg_n_cluster))
        used_clusters.add(c_label)

    rows = []
    total_correct = 0
    total_scene_images = 0
    total_cluster_images = 0

    for scene, scene_imgs in sorted(gt_scenes.items()):
        n_scene = len(scene_imgs)
        total_scene_images += n_scene

        if scene in assigned_scene:
            best_cluster, best_correct, best_maa, best_cs, best_cluster_size = assigned_scene[scene]
        else:
            best_cluster = "(none)"
            best_correct = 0
            best_maa = 0.0
            best_cs = 0.0
            best_cluster_size = 0

        total_correct += int(best_correct)
        total_cluster_images += int(best_cluster_size)

        rows.append(
            {
                "dataset": dataset,
                "gt_scene": scene,
                "assigned_cluster": best_cluster,
                "n_scene": n_scene,
                "n_cluster": int(best_cluster_size),
                "n_correct": int(best_correct),
                "mAA(scene)": float(best_maa),
                "CS(scene)": float(best_cs),
            }
        )

    maa = (total_correct / total_scene_images) if total_scene_images else 0.0
    cs = (total_correct / total_cluster_images) if total_cluster_images else 0.0
    final = harmonic_mean(maa, cs)

    ds_score = DatasetScore(
        dataset=dataset,
        mAA=float(maa),
        clustering_score=float(cs),
        final_score=float(final),
        n_scenes=len(gt_scenes),
        n_images_in_scenes=int(total_scene_images),
        n_correct=int(total_correct),
        n_cluster_images_summed=int(total_cluster_images),
    )

    return ds_score, pd.DataFrame(rows)


def score_predictions_csv(*, pred_csv: Path, labels_csv: Path, data_root: Path, outliers_label: str = "outliers", drop_outliers_scene: bool = False) -> Tuple[pd.DataFrame, pd.DataFrame, dict]:
    gt_scenes_by_dataset, all_images_by_dataset = load_ground_truth(labels_csv=labels_csv, data_root=data_root, drop_outliers_scene=drop_outliers_scene)
    pred_clusters_by_dataset = load_predictions(pred_csv=pred_csv, expected_images=all_images_by_dataset, outliers_label=outliers_label)

    datasets = sorted(set(gt_scenes_by_dataset.keys()) & set(pred_clusters_by_dataset.keys()))
    dataset_scores = []
    scene_tables = []

    for ds in datasets:
        ds_score, per_scene = score_dataset(
            dataset=ds,
            gt_scenes=gt_scenes_by_dataset[ds],
            pred_clusters=pred_clusters_by_dataset[ds],
            outliers_label=outliers_label,
        )
        dataset_scores.append(ds_score.__dict__)
        scene_tables.append(per_scene)

    scores_df = pd.DataFrame(dataset_scores).sort_values("dataset")
    scenes_df = pd.concat(scene_tables, ignore_index=True) if scene_tables else pd.DataFrame()

    overall = {
        "datasets": datasets,
        "macro_final_mean": float(scores_df["final_score"].mean()) if len(scores_df) else 0.0,
        "micro_mAA": 0.0,
        "micro_CS": 0.0,
        "micro_final": 0.0,
    }
    if len(scores_df):
        total_correct = int(scores_df["n_correct"].sum())
        total_scene_images = int(scores_df["n_images_in_scenes"].sum())
        total_cluster_images = int(scores_df["n_cluster_images_summed"].sum())
        micro_maa = total_correct / total_scene_images if total_scene_images else 0.0
        micro_cs = total_correct / total_cluster_images if total_cluster_images else 0.0
        overall["micro_mAA"] = float(micro_maa)
        overall["micro_CS"] = float(micro_cs)
        overall["micro_final"] = float(harmonic_mean(micro_maa, micro_cs))

    return scores_df, scenes_df, overall

## 3) Build inference-only (pretrained) embedding cache for the test split

This produces a cache compatible with `scripts/cluster_retrieval.py`:
- `meta.json`
- `embeddings.npy`

No fine-tuning is performed.

In [22]:
from imc25.train.retrieval_transforms import load_transform_spec, make_eval_transform
from transformers import AutoModel


MODEL_ID = "facebook/dinov2-small"

HF_ENDPOINT = None  # "https://hf-mirror.com"

OUT_ROOT = REPO_ROOT / "outputs" / f"ablation_{SPLIT_TAG}"
OUT_ROOT.mkdir(parents=True, exist_ok=True)

CACHE_PRETRAINED_TEST = OUT_ROOT / "cache_retrieval_pretrained_test"
CACHE_PRETRAINED_TEST.mkdir(parents=True, exist_ok=True)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", DEVICE)


class _PathDataset(torch.utils.data.Dataset):
    def __init__(self, paths: list[Path], *, transform) -> None:
        self.paths = paths
        self.transform = transform

    def __len__(self) -> int:
        return len(self.paths)

    def __getitem__(self, idx: int):
        from PIL import Image

        p = self.paths[int(idx)]
        with Image.open(p) as im:
            im = im.convert("RGB")
            x = self.transform(im)
        return x, str(p)


def _list_images(root: Path) -> list[Path]:
    exts = {".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tif", ".tiff"}
    out: list[Path] = []
    for p in sorted(root.iterdir()):
        if p.is_file() and p.suffix.lower() in exts:
            out.append(p)
    return out


@torch.inference_mode()
def _embed_pretrained_backbone(paths: list[Path], *, batch_size: int, num_workers: int) -> np.ndarray:
    if HF_ENDPOINT:
        os.environ["HF_ENDPOINT"] = str(HF_ENDPOINT)

    spec = load_transform_spec(model_id=MODEL_ID, hf_endpoint=HF_ENDPOINT)
    tf = make_eval_transform(spec)

    model = AutoModel.from_pretrained(MODEL_ID)
    model.eval().to(DEVICE)

    ds = _PathDataset(paths, transform=tf)
    loader = torch.utils.data.DataLoader(
        ds,
        batch_size=int(batch_size),
        shuffle=False,
        num_workers=int(num_workers),
        pin_memory=(DEVICE.type == "cuda"),
        drop_last=False,
    )

    zs: list[np.ndarray] = []
    for xb, _ in tqdm(loader, desc="embed(pretrained)", leave=False):
        xb = xb.to(DEVICE, non_blocking=True)
        out = model(pixel_values=xb)
        if hasattr(out, "pooler_output") and out.pooler_output is not None:
            x = out.pooler_output
        else:
            x = out.last_hidden_state[:, 0]
        z = F.normalize(x.float(), p=2, dim=1).cpu().numpy()
        zs.append(z.astype(np.float32, copy=False))
    if not zs:
        return np.zeros((0, 1), dtype=np.float32)
    return np.concatenate(zs, axis=0)


def build_cache_pretrained(*, data_root: Path, cache_root: Path, datasets: list[str], batch_size: int = 64, num_workers: int = 0, overwrite: bool = False) -> None:
    cache_root.mkdir(parents=True, exist_ok=True)
    for dataset in datasets:
        ds_dir = data_root / dataset
        out_dir = cache_root / dataset
        out_dir.mkdir(parents=True, exist_ok=True)
        meta_path = out_dir / "meta.json"
        emb_path = out_dir / "embeddings.npy"
        if meta_path.exists() and emb_path.exists() and not overwrite:
            print(f"[skip] pretrained cache exists: {dataset} -> {out_dir}")
            continue
        paths = _list_images(ds_dir)
        if not paths:
            print(f"[skip] no images: {ds_dir}")
            continue
        image_ids = [p.stem for p in paths]
        emb = _embed_pretrained_backbone(paths, batch_size=batch_size, num_workers=num_workers)
        np.save(emb_path, emb.astype(np.float32, copy=False))
        meta = {
            "dataset": dataset,
            "backend": "pretrained_backbone",
            "model": MODEL_ID,
            "embed_dim": int(emb.shape[1]) if emb.ndim == 2 else None,
            "image_ids": image_ids,
            "paths": [str(p) for p in paths],
        }
        meta_path.write_text(json.dumps(meta, indent=2))
        print(f"[ok] pretrained cache: {dataset} embeddings={emb.shape} -> {out_dir}")


# Build the inference-only cache for the HOLDOUT test datasets.
BUILD_PRETRAINED_CACHE = True
if BUILD_PRETRAINED_CACHE:
    build_cache_pretrained(
        data_root=TEST_SPLIT_ROOT,
        cache_root=CACHE_PRETRAINED_TEST,
        datasets=test_datasets,
        batch_size=64,
        # NOTE: keep num_workers=0 to avoid PyTorch DataLoader multiprocessing shutdown errors.
        num_workers=0,
        overwrite=False,
    )

device: cuda
[skip] pretrained cache exists: ETs -> /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_pretrained_test/ETs
[skip] pretrained cache exists: pt_sacrecoeur_trevi_tajmahal -> /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_pretrained_test/pt_sacrecoeur_trevi_tajmahal
[skip] pretrained cache exists: pt_stpeters_stpauls -> /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_pretrained_test/pt_stpeters_stpauls

## 4) Fine-tune retrieval embeddings (DINOv2 backbone + projection head)

This trains on the **train split** only, and produces a checkpoint for configurations (2)–(4).

In [23]:
TRAIN_OUTPUT_DIR = OUT_ROOT / "retrieval_finetune"
CHECKPOINT_FINETUNED = TRAIN_OUTPUT_DIR / "best.pt"

RUN_TRAINING = False  # set True if you want to (re)train now

env = os.environ.copy()
if HF_ENDPOINT:
    env["HF_ENDPOINT"] = str(HF_ENDPOINT)

if RUN_TRAINING or (not CHECKPOINT_FINETUNED.exists()):
    cmd = [
        sys.executable,
        "scripts/train_retrieval.py",
        "--data-root",
        str(TRAIN_SPLIT_ROOT),
        "--labels-csv",
        str(TRAIN_SPLIT_LABELS),
        "--output-dir",
        str(TRAIN_OUTPUT_DIR),
        "--model-id",
        str(MODEL_ID),
        "--embed-dim",
        "256",
        "--epochs",
        "6",
        "--batch-size",
        "48",
        "--num-workers",
        "4",
        "--freeze-backbone",
        "--no-include-outliers",
    ]
    run(cmd, env=env)
else:
    print("[skip] training:", CHECKPOINT_FINETUNED)

assert CHECKPOINT_FINETUNED.exists(), f"Missing checkpoint: {CHECKPOINT_FINETUNED}"
CHECKPOINT_FINETUNED

[skip] training: /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/retrieval_finetune/best.pt

PosixPath('/home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/retrieval_finetune/best.pt')

## 5) Build fine-tuned embedding caches (train + test split)

These caches are used for clustering and for training the EdgeMLP.

In [24]:
import sys

CACHE_FINETUNED_TRAIN = OUT_ROOT / "cache_retrieval_finetuned_train"
CACHE_FINETUNED_TEST = OUT_ROOT / "cache_retrieval_finetuned_test"

BUILD_FINETUNED_CACHES = True

if BUILD_FINETUNED_CACHES:
    # Train cache (for EdgeMLP training + hyperparam selection)
    cmd = [
        sys.executable,
        "scripts/build_retrieval_cache.py",
        "--data-root",
        str(TRAIN_SPLIT_ROOT),
        "--cache-root",
        str(CACHE_FINETUNED_TRAIN),
        "--checkpoint",
        str(CHECKPOINT_FINETUNED),
        "--topk",
        "30",
        "--mutual",
    ]
    if HF_ENDPOINT:
        cmd += ["--hf-endpoint", str(HF_ENDPOINT)]
    run(cmd, env=env)

    # Test cache (for evaluation)
    cmd = [
        sys.executable,
        "scripts/build_retrieval_cache.py",
        "--data-root",
        str(TEST_SPLIT_ROOT),
        "--cache-root",
        str(CACHE_FINETUNED_TEST),
        "--checkpoint",
        str(CHECKPOINT_FINETUNED),
        "--topk",
        "30",
        "--mutual",
    ]
    if HF_ENDPOINT:
        cmd += ["--hf-endpoint", str(HF_ENDPOINT)]
    run(cmd, env=env)

+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/build_retrieval_cache.py --data-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/data/train_split_holdout_ets_sacrecoeur_stpeters --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_finetuned_train --checkpoint /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/retrieval_finetune/best.pt --topk 30 --mutual

Traceback (most recent call last):
  File "/home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/scripts/build_retrieval_cache.py", line 12, in <module>
    from imc25.train.retrieval_cache import main
  File "/home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/src/imc25/train/retrieval_cache.py", line 9, in <module>
    import torch
  File "/home/shamika/miniconda3/envs/imc25/lib/python3.10/site-packages/torch/__init__.py", line 2161, in <module>
    from torch import _VF as _VF, functional as functional  # usort: skip
  File "/home/shamika/miniconda3/envs/imc25/lib/python3.10/site-packages/torch/functional.py", line 8, in <module>
    import torch.nn.functional as F
  File "/home/shamika/miniconda3/envs/imc25/lib/python3.10/site-packages/torch/nn/__init__.py", line 9, in <module>
    from torch.nn import (
  File "/home/shamika/miniconda3/envs/imc25/lib/python3.10/site-packages/torch/nn/attention/__init__.py", line 9, in <module>
    import torch.backends.cuda
  File "/home/shamika/miniconda3/envs/imc25/lib/python3.10/site-packages/torch/backends/__init__.py", line 127, in <module>
    from torch.backends import (
  File "/home/shamika/miniconda3/envs/imc25/lib/python3.10/site-packages/torch/backends/mps/__init__.py", line 5, in <module>

KeyboardInterrupt:

## 6) Train EdgeMLP on the train split (using fine-tuned embeddings)

This trains a lightweight classifier to score candidate KNN edges as "same-scene" vs "different-scene".

The saved checkpoint is then used in configurations (3)–(4).

In [ ]:
from imc25.models.edge_mlp import EdgeMLP

EDGE_MODELS_DIR = OUT_ROOT / "edge_models"
EDGE_MODELS_DIR.mkdir(parents=True, exist_ok=True)
EDGE_MLP_CKPT = EDGE_MODELS_DIR / "edge_mlp_split.pt"

RUN_EDGE_MLP_TRAINING = False  # set True to force retraining

EDGE_K = 30
EDGE_VAL_RATIO = 0.1
EDGE_EPOCHS = 12
EDGE_BATCH_SIZE = 2048
EDGE_LR = 1e-3
EDGE_SEED = 42


def _normalize_rows(x: np.ndarray) -> np.ndarray:
    x = x.astype(np.float32, copy=False)
    denom = np.linalg.norm(x, axis=1, keepdims=True) + 1e-12
    return x / denom


def _load_cache_embeddings(cache_root: Path, dataset: str) -> tuple[list[str], np.ndarray]:
    meta = json.loads((cache_root / dataset / "meta.json").read_text())
    image_ids = [str(x) for x in meta.get("image_ids", [])]
    emb = np.load(cache_root / dataset / "embeddings.npy")
    if len(image_ids) != int(emb.shape[0]):
        raise ValueError(f"{dataset}: meta/image_ids mismatch embeddings rows")
    return image_ids, emb.astype(np.float32, copy=False)


def _split_indices(n: int, *, val_ratio: float, seed: int) -> tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(int(seed))
    idx = np.arange(int(n))
    rng.shuffle(idx)
    n_val = int(round(float(val_ratio) * int(n)))
    val = np.sort(idx[:n_val])
    tr = np.sort(idx[n_val:])
    return tr, val


def _build_edge_dataset_for_dataset(
    *,
    dataset: str,
    cache_root: Path,
    labels_csv: Path,
    k: int,
    treat_outliers_as_negative: bool = True,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Return (i, j, y, emb) for one dataset, where i/j index into emb rows."""
    image_ids, emb = _load_cache_embeddings(cache_root, dataset)
    emb = _normalize_rows(emb)

    gt = pd.read_csv(labels_csv)
    gt = gt[gt["dataset"] == dataset].copy()
    gt["image_key"] = gt["image"].map(lambda x: Path(str(x)).stem)
    scene_of = {str(r.image_key): str(r.scene) for r in gt.itertuples(index=False)}
    scene = [scene_of.get(str(i), "(missing)") for i in image_ids]

    n = int(emb.shape[0])
    if n <= 1:
        return np.zeros((0,), np.int32), np.zeros((0,), np.int32), np.zeros((0,), np.float32), emb

    kk = int(min(int(k) + 1, n))
    nn = NearestNeighbors(n_neighbors=kk, metric="cosine")
    nn.fit(emb)
    _, ind = nn.kneighbors(emb, return_distance=True)
    neigh = ind[:, 1:]

    i_list: list[int] = []
    j_list: list[int] = []
    y_list: list[float] = []
    for i in range(n):
        si = scene[i]
        for j in neigh[i].tolist():
            j = int(j)
            if i == j:
                continue
            sj = scene[j]
            if treat_outliers_as_negative and (si.lower() == "outliers" or sj.lower() == "outliers"):
                y = 0.0
            else:
                y = 1.0 if si == sj else 0.0
            i_list.append(i)
            j_list.append(j)
            y_list.append(float(y))

    return (
        np.asarray(i_list, dtype=np.int32),
        np.asarray(j_list, dtype=np.int32),
        np.asarray(y_list, dtype=np.float32),
        emb,
    )


def train_edge_mlp(*, cache_root: Path, labels_csv: Path, datasets: list[str], out_path: Path) -> Path:
    # Gather all edges across datasets.
    all_i: list[np.ndarray] = []
    all_j: list[np.ndarray] = []
    all_y: list[np.ndarray] = []
    all_emb: list[np.ndarray] = []
    all_offsets: list[int] = []

    offset = 0
    for ds in datasets:
        i, j, y, emb = _build_edge_dataset_for_dataset(dataset=ds, cache_root=cache_root, labels_csv=labels_csv, k=EDGE_K)
        all_offsets.append(offset)
        all_i.append(i + offset)
        all_j.append(j + offset)
        all_y.append(y)
        all_emb.append(emb)
        offset += int(emb.shape[0])

    Z = np.concatenate(all_emb, axis=0) if all_emb else np.zeros((0, 256), dtype=np.float32)
    I = np.concatenate(all_i, axis=0) if all_i else np.zeros((0,), dtype=np.int32)
    J = np.concatenate(all_j, axis=0) if all_j else np.zeros((0,), dtype=np.int32)
    Y = np.concatenate(all_y, axis=0) if all_y else np.zeros((0,), dtype=np.float32)

    if len(Z) == 0 or len(I) == 0:
        raise RuntimeError("No edges/embeddings available to train EdgeMLP")

    # Split by embedding index (so we don't leak anchors between train/val).
    tr_idx, va_idx = _split_indices(len(Z), val_ratio=EDGE_VAL_RATIO, seed=EDGE_SEED)
    tr_set = set(tr_idx.tolist())
    va_set = set(va_idx.tolist())

    tr_mask = np.array([(int(i) in tr_set and int(j) in tr_set) for i, j in zip(I, J, strict=False)], dtype=bool)
    va_mask = np.array([(int(i) in va_set and int(j) in va_set) for i, j in zip(I, J, strict=False)], dtype=bool)

    I_tr, J_tr, Y_tr = I[tr_mask], J[tr_mask], Y[tr_mask]
    I_va, J_va, Y_va = I[va_mask], J[va_mask], Y[va_mask]

    print(f"EdgeMLP training edges: train={len(I_tr)} val={len(I_va)} (total={len(I)})")

    z_t = torch.from_numpy(Z).to(DEVICE)
    model = EdgeMLP(int(Z.shape[1])).to(DEVICE)
    opt = torch.optim.Adam(model.parameters(), lr=float(EDGE_LR))
    loss_fn = nn.BCELoss()

    best_auc = -1.0
    best_state = None

    rng = np.random.default_rng(EDGE_SEED)
    for epoch in range(1, int(EDGE_EPOCHS) + 1):
        model.train()
        order = rng.permutation(len(I_tr))
        losses = []
        for start in range(0, len(order), int(EDGE_BATCH_SIZE)):
            idx = order[start : start + int(EDGE_BATCH_SIZE)]
            ii = torch.from_numpy(I_tr[idx]).to(DEVICE)
            jj = torch.from_numpy(J_tr[idx]).to(DEVICE)
            yb = torch.from_numpy(Y_tr[idx]).to(DEVICE)

            opt.zero_grad(set_to_none=True)
            pred = model(z_t[ii], z_t[jj])
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            losses.append(float(loss.detach().cpu().item()))

        model.eval()
        with torch.no_grad():
            if len(I_va) > 0:
                ii = torch.from_numpy(I_va).to(DEVICE)
                jj = torch.from_numpy(J_va).to(DEVICE)
                yv = Y_va
                pv = model(z_t[ii], z_t[jj]).detach().cpu().numpy()
                auc = float(roc_auc_score(yv, pv)) if len(np.unique(yv)) > 1 else 0.0
                ap = float(average_precision_score(yv, pv)) if len(np.unique(yv)) > 1 else 0.0
            else:
                auc, ap = 0.0, 0.0

        print(f"Epoch {epoch:02d} | loss={np.mean(losses) if losses else 0:.4f} | val_auc={auc:.4f} | val_ap={ap:.4f}")
        if auc >= best_auc:
            best_auc = auc
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

    if best_state is None:
        best_state = model.state_dict()

    out_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save({"state_dict": best_state, "dim": int(Z.shape[1]), "K": int(EDGE_K)}, out_path)
    print(f"[ok] saved EdgeMLP: {out_path} (best_auc={best_auc:.4f})")
    return out_path


if RUN_EDGE_MLP_TRAINING or (not EDGE_MLP_CKPT.exists()):
    train_edge_mlp(cache_root=CACHE_FINETUNED_TRAIN, labels_csv=TRAIN_SPLIT_LABELS, datasets=train_datasets, out_path=EDGE_MLP_CKPT)
else:
    print("[skip] EdgeMLP exists:", EDGE_MLP_CKPT)

assert EDGE_MLP_CKPT.exists(), f"Missing EdgeMLP checkpoint: {EDGE_MLP_CKPT}"
EDGE_MLP_CKPT

EdgeMLP training edges: train=36455 val=473 (total=44940)
Epoch 01 | loss=0.6312 | val_auc=0.3228 | val_ap=0.8030
Epoch 02 | loss=0.5001 | val_auc=0.3450 | val_ap=0.8079
Epoch 03 | loss=0.4330 | val_auc=0.7933 | val_ap=0.9677
Epoch 04 | loss=0.3620 | val_auc=0.8196 | val_ap=0.9737
Epoch 05 | loss=0.3169 | val_auc=0.8742 | val_ap=0.9833
Epoch 06 | loss=0.2747 | val_auc=0.9289 | val_ap=0.9912
Epoch 07 | loss=0.2272 | val_auc=0.9724 | val_ap=0.9967
Epoch 08 | loss=0.1853 | val_auc=0.9817 | val_ap=0.9978
Epoch 09 | loss=0.1596 | val_auc=0.9826 | val_ap=0.9979
Epoch 10 | loss=0.1446 | val_auc=0.9848 | val_ap=0.9982
Epoch 11 | loss=0.1348 | val_auc=0.9854 | val_ap=0.9983
Epoch 12 | loss=0.1278 | val_auc=0.9862 | val_ap=0.9984
[ok] saved EdgeMLP: /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/edge_models/edge_mlp_split.pt (best_auc=0.9862)

PosixPath('/home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/edge_models/edge_mlp_split.pt')

## 7) Run the 4 configurations (cluster → score → visualize)

We keep the evaluation split fixed, and compare different components.

In [ ]:
@dataclass(frozen=True)
class ClusterCfg:
    topk: int = 30
    mutual: bool = True
    min_sim: float = 0.35
    method: str = "louvain"  # louvain|greedy|components
    min_cluster_size: int = 3
    edge_scorer: str = "cosine"  # cosine|mlp|gbdt
    edge_model: Path | None = None
    edge_topm: int | None = None


def run_cluster_retrieval(*, cache_root: Path, out_csv: Path, datasets: list[str], cfg: ClusterCfg) -> None:
    cmd = [
        sys.executable,
        "scripts/cluster_retrieval.py",
        "--cache-root",
        str(cache_root),
        "--out-csv",
        str(out_csv),
        "--topk",
        str(int(cfg.topk)),
        "--min-sim",
        str(float(cfg.min_sim)),
        "--method",
        str(cfg.method),
        "--min-cluster-size",
        str(int(cfg.min_cluster_size)),
        "--edge-scorer",
        str(cfg.edge_scorer),
    ]
    for ds in datasets:
        cmd += ["--dataset", str(ds)]

    if cfg.edge_scorer in {"mlp", "gbdt"}:
        if cfg.edge_model is None:
            raise ValueError("edge_model required when edge_scorer is mlp/gbdt")
        cmd += ["--edge-model", str(cfg.edge_model)]
        if cfg.edge_topm is not None:
            cmd += ["--edge-topm", str(int(cfg.edge_topm))]

    if cfg.mutual:
        cmd += ["--mutual"]
    else:
        cmd += ["--no-mutual"]

    run(cmd, env=env)


DROP_GT_OUTLIERS = True  # set False to include GT outliers scene in scoring
OUTLIERS_LABEL = "outliers"

RESULTS_DIR = OUT_ROOT / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)


def eval_clusters(*, name: str, clusters_csv: Path) -> dict:
    scores_df, scenes_df, overall = score_predictions_csv(
        pred_csv=clusters_csv,
        labels_csv=TEST_SPLIT_LABELS,
        data_root=TEST_SPLIT_ROOT,
        outliers_label=OUTLIERS_LABEL,
        drop_outliers_scene=DROP_GT_OUTLIERS,
    )
    scores_df.to_csv(RESULTS_DIR / f"{name}_dataset_scores.csv", index=False)
    scenes_df.to_csv(RESULTS_DIR / f"{name}_per_scene.csv", index=False)
    (RESULTS_DIR / f"{name}_overall.json").write_text(json.dumps(overall, indent=2))
    return {
        "name": name,
        "scores_df": scores_df,
        "scenes_df": scenes_df,
        "overall": overall,
    }


# --- Config 1: inference-only (pretrained backbone) ---
CFG1 = ClusterCfg(edge_scorer="cosine", min_sim=0.35, topk=30, mutual=True, method="louvain")
CLUSTERS1 = RESULTS_DIR / "clusters_cfg1_inference_only.csv"
run_cluster_retrieval(cache_root=CACHE_PRETRAINED_TEST, out_csv=CLUSTERS1, datasets=test_datasets, cfg=CFG1)
res1 = eval_clusters(name="cfg1_inference_only", clusters_csv=CLUSTERS1)

# --- Config 2: finetuned embeddings + cosine ---
CFG2 = ClusterCfg(edge_scorer="cosine", min_sim=0.35, topk=30, mutual=True, method="louvain")
CLUSTERS2 = RESULTS_DIR / "clusters_cfg2_finetuned_cosine.csv"
run_cluster_retrieval(cache_root=CACHE_FINETUNED_TEST, out_csv=CLUSTERS2, datasets=test_datasets, cfg=CFG2)
res2 = eval_clusters(name="cfg2_finetuned_cosine", clusters_csv=CLUSTERS2)

# --- Config 3: finetuned embeddings + EdgeMLP (fixed hyperparams) ---
CFG3 = ClusterCfg(edge_scorer="mlp", edge_model=EDGE_MLP_CKPT, edge_topm=5, min_sim=0.55, topk=30, mutual=True, method="louvain")
CLUSTERS3 = RESULTS_DIR / "clusters_cfg3_finetuned_edge_mlp.csv"
run_cluster_retrieval(cache_root=CACHE_FINETUNED_TEST, out_csv=CLUSTERS3, datasets=test_datasets, cfg=CFG3)
res3 = eval_clusters(name="cfg3_finetuned_edge_mlp", clusters_csv=CLUSTERS3)

+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/cluster_retrieval.py --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_pretrained_test --out-csv /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/clusters_cfg1_inference_only.csv --topk 30 --min-sim 0.35 --method louvain --min-cluster-size 3 --edge-scorer cosine --dataset ETs --dataset pt_sacrecoeur_trevi_tajmahal --dataset pt_stpeters_stpauls --mutual
Inference embeddings shape: (22, 384)
[ok] ETs: clusters=2 outliers=0 images=22
Inference embeddings shape: (225, 384)
[ok] pt_sacrecoeur_trevi_tajmahal: clusters=6 outliers=4 images=225
Inference embeddings shape: (200, 384)
[ok] pt_stpeters_stpauls: clusters=7 outliers=3 images=200
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/clusters_cfg1_inference_only.csv rows=447
+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/cluster_retrieval.py --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_finetuned_test --out-csv /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/clusters_cfg2_finetuned_cosine.csv --topk 30 --min-sim 0.35 --method louvain --min-cluster-size 3 --edge-scorer cosine --dataset ETs --dataset pt_sacrecoeur_trevi_tajmahal --dataset pt_stpeters_stpauls --mutual
Inference embeddings shape: (22, 256)
[ok] ETs: clusters=2 outliers=0 images=22
Inference embeddings shape: (225, 256)
[ok] pt_sacrecoeur_trevi_tajmahal: clusters=6 outliers=4 images=225
Inference embeddings shape: (200, 256)
[ok] pt_stpeters_stpauls: clusters=5 outliers=1 images=200
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/clusters_cfg2_finetuned_cosine.csv rows=447
+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/cluster_retrieval.py --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_finetuned_test --out-csv /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/clusters_cfg3_finetuned_edge_mlp.csv --topk 30 --min-sim 0.55 --method louvain --min-cluster-size 3 --edge-scorer mlp --dataset ETs --dataset pt_sacrecoeur_trevi_tajmahal --dataset pt_stpeters_stpauls --edge-model /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/edge_models/edge_mlp_split.pt --edge-topm 5 --mutual
Inference embeddings shape: (22, 256)
[ok] ETs: clusters=3 outliers=0 images=22
Inference embeddings shape: (225, 256)
[ok] pt_sacrecoeur_trevi_tajmahal: clusters=9 outliers=4 images=225
Inference embeddings shape: (200, 256)
[ok] pt_stpeters_stpauls: clusters=8 outliers=5 images=200
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/clusters_cfg3_finetuned_edge_mlp.csv rows=447

## 8) Config 4 ("everything"): select clustering hyperparameters on the train split, then evaluate on the test split

We do a small grid search using **train split** ground truth, pick the best config by overall micro Final Score, and then run it on the holdout test datasets.

In [ ]:
SWEEP = True

sweep_min_sim = [0.35, 0.45, 0.55, 0.65]
sweep_edge_topm = [None, 10, 5, 3]
sweep_method = ["louvain", "greedy"]

SWEEP_OUT = RESULTS_DIR / "sweep_cfg4_train_selection.csv"


def score_on_train_split(*, clusters_csv: Path) -> dict:
    scores_df, _scenes_df, overall = score_predictions_csv(
        pred_csv=clusters_csv,
        labels_csv=TRAIN_SPLIT_LABELS,
        data_root=TRAIN_SPLIT_ROOT,
        outliers_label=OUTLIERS_LABEL,
        drop_outliers_scene=DROP_GT_OUTLIERS,
    )
    return {
        "macro_final_mean": float(overall["macro_final_mean"]),
        "micro_mAA": float(overall["micro_mAA"]),
        "micro_CS": float(overall["micro_CS"]),
        "micro_final": float(overall["micro_final"]),
        "n_datasets": int(len(overall["datasets"])),
    }


best_cfg4: ClusterCfg | None = None
best_score = -1.0
rows = []

if SWEEP:
    for method in sweep_method:
        for min_sim in sweep_min_sim:
            for topm in sweep_edge_topm:
                cfg = ClusterCfg(
                    edge_scorer="mlp",
                    edge_model=EDGE_MLP_CKPT,
                    edge_topm=topm,
                    min_sim=float(min_sim),
                    topk=30,
                    mutual=True,
                    method=str(method),
                    min_cluster_size=3,
                )
                out_csv = RESULTS_DIR / f"tmp_cfg4_train_{method}_mins{min_sim}_topm{topm}.csv"
                run_cluster_retrieval(cache_root=CACHE_FINETUNED_TRAIN, out_csv=out_csv, datasets=train_datasets, cfg=cfg)
                m = score_on_train_split(clusters_csv=out_csv)
                row = {
                    "method": method,
                    "min_sim": float(min_sim),
                    "edge_topm": None if topm is None else int(topm),
                    **m,
                }
                rows.append(row)
                if float(m["micro_final"]) > best_score:
                    best_score = float(m["micro_final"])
                    best_cfg4 = cfg

    sweep_df = pd.DataFrame(rows).sort_values(["micro_final"], ascending=False)
    sweep_df.to_csv(SWEEP_OUT, index=False)
    print("[ok] sweep written:", SWEEP_OUT)
    print("best micro_final (train):", best_score)
else:
    # A reasonable default if you don't want to sweep.
    best_cfg4 = ClusterCfg(edge_scorer="mlp", edge_model=EDGE_MLP_CKPT, edge_topm=5, min_sim=0.55, topk=30, mutual=True, method="louvain")

assert best_cfg4 is not None
best_cfg4

+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/cluster_retrieval.py --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_finetuned_train --out-csv /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.35_topmNone.csv --topk 30 --min-sim 0.35 --method louvain --min-cluster-size 3 --edge-scorer mlp --dataset amy_gardens --dataset fbk_vineyard --dataset imc2023_haiper --dataset imc2023_heritage --dataset imc2023_theather_imc2024_church --dataset imc2024_dioscuri_baalshamin --dataset imc2024_lizard_pond --dataset pt_brandenburg_british_buckingham --dataset pt_piazzasanmarco_grandplace --dataset stairs --edge-model /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/edge_models/edge_mlp_split.pt --mutual
Inference embeddings shape: (200, 256)
[ok] amy_gardens: clusters=4 outliers=2 images=200
Inference embeddings shape: (163, 256)
[ok] fbk_vineyard: clusters=3 outliers=0 images=163
Inference embeddings shape: (54, 256)
[ok] imc2023_haiper: clusters=3 outliers=0 images=54
Inference embeddings shape: (209, 256)
[ok] imc2023_heritage: clusters=7 outliers=42 images=209
Inference embeddings shape: (76, 256)
[ok] imc2023_theather_imc2024_church: clusters=2 outliers=0 images=76
Inference embeddings shape: (138, 256)
[ok] imc2024_dioscuri_baalshamin: clusters=3 outliers=2 images=138
Inference embeddings shape: (214, 256)
[ok] imc2024_lizard_pond: clusters=7 outliers=5 images=214
Inference embeddings shape: (225, 256)
[ok] pt_brandenburg_british_buckingham: clusters=3 outliers=1 images=225
Inference embeddings shape: (168, 256)
[ok] pt_piazzasanmarco_grandplace: clusters=3 outliers=0 images=168
Inference embeddings shape: (51, 256)
[ok] stairs: clusters=3 outliers=0 images=51
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.35_topmNone.csv rows=1498
+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/cluster_retrieval.py --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_finetuned_train --out-csv /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.35_topm10.csv --topk 30 --min-sim 0.35 --method louvain --min-cluster-size 3 --edge-scorer mlp --dataset amy_gardens --dataset fbk_vineyard --dataset imc2023_haiper --dataset imc2023_heritage --dataset imc2023_theather_imc2024_church --dataset imc2024_dioscuri_baalshamin --dataset imc2024_lizard_pond --dataset pt_brandenburg_british_buckingham --dataset pt_piazzasanmarco_grandplace --dataset stairs --edge-model /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/edge_models/edge_mlp_split.pt --edge-topm 10 --mutual
Inference embeddings shape: (200, 256)
[ok] amy_gardens: clusters=6 outliers=6 images=200
Inference embeddings shape: (163, 256)
[ok] fbk_vineyard: clusters=5 outliers=0 images=163
Inference embeddings shape: (54, 256)
[ok] imc2023_haiper: clusters=3 outliers=0 images=54
Inference embeddings shape: (209, 256)
[ok] imc2023_heritage: clusters=8 outliers=42 images=209
Inference embeddings shape: (76, 256)
[ok] imc2023_theather_imc2024_church: clusters=3 outliers=0 images=76
Inference embeddings shape: (138, 256)
[ok] imc2024_dioscuri_baalshamin: clusters=6 outliers=3 images=138
Inference embeddings shape: (214, 256)
[ok] imc2024_lizard_pond: clusters=9 outliers=9 images=214
Inference embeddings shape: (225, 256)
[ok] pt_brandenburg_british_buckingham: clusters=3 outliers=3 images=225
Inference embeddings shape: (168, 256)
[ok] pt_piazzasanmarco_grandplace: clusters=3 outliers=0 images=168
Inference embeddings shape: (51, 256)
[ok] stairs: clusters=4 outliers=0 images=51
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.35_topm10.csv rows=1498
+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/cluster_retrieval.py --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_finetuned_train --out-csv /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.35_topm5.csv --topk 30 --min-sim 0.35 --method louvain --min-cluster-size 3 --edge-scorer mlp --dataset amy_gardens --dataset fbk_vineyard --dataset imc2023_haiper --dataset imc2023_heritage --dataset imc2023_theather_imc2024_church --dataset imc2024_dioscuri_baalshamin --dataset imc2024_lizard_pond --dataset pt_brandenburg_british_buckingham --dataset pt_piazzasanmarco_grandplace --dataset stairs --edge-model /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/edge_models/edge_mlp_split.pt --edge-topm 5 --mutual
Inference embeddings shape: (200, 256)
[ok] amy_gardens: clusters=8 outliers=11 images=200
Inference embeddings shape: (163, 256)
[ok] fbk_vineyard: clusters=6 outliers=3 images=163
Inference embeddings shape: (54, 256)
[ok] imc2023_haiper: clusters=4 outliers=1 images=54
Inference embeddings shape: (209, 256)
[ok] imc2023_heritage: clusters=10 outliers=46 images=209
Inference embeddings shape: (76, 256)
[ok] imc2023_theather_imc2024_church: clusters=4 outliers=3 images=76
Inference embeddings shape: (138, 256)
[ok] imc2024_dioscuri_baalshamin: clusters=7 outliers=5 images=138
Inference embeddings shape: (214, 256)
[ok] imc2024_lizard_pond: clusters=10 outliers=11 images=214
Inference embeddings shape: (225, 256)
[ok] pt_brandenburg_british_buckingham: clusters=3 outliers=6 images=225
Inference embeddings shape: (168, 256)
[ok] pt_piazzasanmarco_grandplace: clusters=6 outliers=2 images=168
Inference embeddings shape: (51, 256)
[ok] stairs: clusters=6 outliers=0 images=51
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.35_topm5.csv rows=1498
+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/cluster_retrieval.py --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_finetuned_train --out-csv /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.35_topm3.csv --topk 30 --min-sim 0.35 --method louvain --min-cluster-size 3 --edge-scorer mlp --dataset amy_gardens --dataset fbk_vineyard --dataset imc2023_haiper --dataset imc2023_heritage --dataset imc2023_theather_imc2024_church --dataset imc2024_dioscuri_baalshamin --dataset imc2024_lizard_pond --dataset pt_brandenburg_british_buckingham --dataset pt_piazzasanmarco_grandplace --dataset stairs --edge-model /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/edge_models/edge_mlp_split.pt --edge-topm 3 --mutual
Inference embeddings shape: (200, 256)
[ok] amy_gardens: clusters=9 outliers=23 images=200
Inference embeddings shape: (163, 256)
[ok] fbk_vineyard: clusters=9 outliers=5 images=163
Inference embeddings shape: (54, 256)
[ok] imc2023_haiper: clusters=5 outliers=4 images=54
Inference embeddings shape: (209, 256)
[ok] imc2023_heritage: clusters=12 outliers=51 images=209
Inference embeddings shape: (76, 256)
[ok] imc2023_theather_imc2024_church: clusters=7 outliers=10 images=76
Inference embeddings shape: (138, 256)
[ok] imc2024_dioscuri_baalshamin: clusters=10 outliers=10 images=138
Inference embeddings shape: (214, 256)
[ok] imc2024_lizard_pond: clusters=14 outliers=20 images=214
Inference embeddings shape: (225, 256)
[ok] pt_brandenburg_british_buckingham: clusters=7 outliers=11 images=225
Inference embeddings shape: (168, 256)
[ok] pt_piazzasanmarco_grandplace: clusters=9 outliers=12 images=168
Inference embeddings shape: (51, 256)
[ok] stairs: clusters=7 outliers=0 images=51
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.35_topm3.csv rows=1498
+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/cluster_retrieval.py --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_finetuned_train --out-csv /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.45_topmNone.csv --topk 30 --min-sim 0.45 --method louvain --min-cluster-size 3 --edge-scorer mlp --dataset amy_gardens --dataset fbk_vineyard --dataset imc2023_haiper --dataset imc2023_heritage --dataset imc2023_theather_imc2024_church --dataset imc2024_dioscuri_baalshamin --dataset imc2024_lizard_pond --dataset pt_brandenburg_british_buckingham --dataset pt_piazzasanmarco_grandplace --dataset stairs --edge-model /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/edge_models/edge_mlp_split.pt --mutual
Inference embeddings shape: (200, 256)
[ok] amy_gardens: clusters=4 outliers=2 images=200
Inference embeddings shape: (163, 256)
[ok] fbk_vineyard: clusters=4 outliers=0 images=163
Inference embeddings shape: (54, 256)
[ok] imc2023_haiper: clusters=3 outliers=0 images=54
Inference embeddings shape: (209, 256)
[ok] imc2023_heritage: clusters=6 outliers=49 images=209
Inference embeddings shape: (76, 256)
[ok] imc2023_theather_imc2024_church: clusters=2 outliers=0 images=76
Inference embeddings shape: (138, 256)
[ok] imc2024_dioscuri_baalshamin: clusters=5 outliers=6 images=138
Inference embeddings shape: (214, 256)
[ok] imc2024_lizard_pond: clusters=6 outliers=13 images=214
Inference embeddings shape: (225, 256)
[ok] pt_brandenburg_british_buckingham: clusters=3 outliers=1 images=225
Inference embeddings shape: (168, 256)
[ok] pt_piazzasanmarco_grandplace: clusters=3 outliers=0 images=168
Inference embeddings shape: (51, 256)
[ok] stairs: clusters=3 outliers=0 images=51
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.45_topmNone.csv rows=1498
+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/cluster_retrieval.py --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_finetuned_train --out-csv /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.45_topm10.csv --topk 30 --min-sim 0.45 --method louvain --min-cluster-size 3 --edge-scorer mlp --dataset amy_gardens --dataset fbk_vineyard --dataset imc2023_haiper --dataset imc2023_heritage --dataset imc2023_theather_imc2024_church --dataset imc2024_dioscuri_baalshamin --dataset imc2024_lizard_pond --dataset pt_brandenburg_british_buckingham --dataset pt_piazzasanmarco_grandplace --dataset stairs --edge-model /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/edge_models/edge_mlp_split.pt --edge-topm 10 --mutual
Inference embeddings shape: (200, 256)
[ok] amy_gardens: clusters=6 outliers=6 images=200
Inference embeddings shape: (163, 256)
[ok] fbk_vineyard: clusters=5 outliers=0 images=163
Inference embeddings shape: (54, 256)
[ok] imc2023_haiper: clusters=3 outliers=0 images=54
Inference embeddings shape: (209, 256)
[ok] imc2023_heritage: clusters=7 outliers=49 images=209
Inference embeddings shape: (76, 256)
[ok] imc2023_theather_imc2024_church: clusters=3 outliers=0 images=76
Inference embeddings shape: (138, 256)
[ok] imc2024_dioscuri_baalshamin: clusters=7 outliers=7 images=138
Inference embeddings shape: (214, 256)
[ok] imc2024_lizard_pond: clusters=8 outliers=17 images=214
Inference embeddings shape: (225, 256)
[ok] pt_brandenburg_british_buckingham: clusters=3 outliers=3 images=225
Inference embeddings shape: (168, 256)
[ok] pt_piazzasanmarco_grandplace: clusters=3 outliers=0 images=168
Inference embeddings shape: (51, 256)
[ok] stairs: clusters=4 outliers=0 images=51
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.45_topm10.csv rows=1498
+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/cluster_retrieval.py --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_finetuned_train --out-csv /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.45_topm5.csv --topk 30 --min-sim 0.45 --method louvain --min-cluster-size 3 --edge-scorer mlp --dataset amy_gardens --dataset fbk_vineyard --dataset imc2023_haiper --dataset imc2023_heritage --dataset imc2023_theather_imc2024_church --dataset imc2024_dioscuri_baalshamin --dataset imc2024_lizard_pond --dataset pt_brandenburg_british_buckingham --dataset pt_piazzasanmarco_grandplace --dataset stairs --edge-model /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/edge_models/edge_mlp_split.pt --edge-topm 5 --mutual
Inference embeddings shape: (200, 256)
[ok] amy_gardens: clusters=8 outliers=11 images=200
Inference embeddings shape: (163, 256)
[ok] fbk_vineyard: clusters=6 outliers=3 images=163
Inference embeddings shape: (54, 256)
[ok] imc2023_haiper: clusters=4 outliers=1 images=54
Inference embeddings shape: (209, 256)
[ok] imc2023_heritage: clusters=9 outliers=53 images=209
Inference embeddings shape: (76, 256)
[ok] imc2023_theather_imc2024_church: clusters=4 outliers=3 images=76
Inference embeddings shape: (138, 256)
[ok] imc2024_dioscuri_baalshamin: clusters=7 outliers=9 images=138
Inference embeddings shape: (214, 256)
[ok] imc2024_lizard_pond: clusters=8 outliers=19 images=214
Inference embeddings shape: (225, 256)
[ok] pt_brandenburg_british_buckingham: clusters=3 outliers=6 images=225
Inference embeddings shape: (168, 256)
[ok] pt_piazzasanmarco_grandplace: clusters=6 outliers=2 images=168
Inference embeddings shape: (51, 256)
[ok] stairs: clusters=5 outliers=0 images=51
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.45_topm5.csv rows=1498
+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/cluster_retrieval.py --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_finetuned_train --out-csv /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.45_topm3.csv --topk 30 --min-sim 0.45 --method louvain --min-cluster-size 3 --edge-scorer mlp --dataset amy_gardens --dataset fbk_vineyard --dataset imc2023_haiper --dataset imc2023_heritage --dataset imc2023_theather_imc2024_church --dataset imc2024_dioscuri_baalshamin --dataset imc2024_lizard_pond --dataset pt_brandenburg_british_buckingham --dataset pt_piazzasanmarco_grandplace --dataset stairs --edge-model /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/edge_models/edge_mlp_split.pt --edge-topm 3 --mutual
Inference embeddings shape: (200, 256)
[ok] amy_gardens: clusters=9 outliers=23 images=200
Inference embeddings shape: (163, 256)
[ok] fbk_vineyard: clusters=9 outliers=5 images=163
Inference embeddings shape: (54, 256)
[ok] imc2023_haiper: clusters=5 outliers=4 images=54
Inference embeddings shape: (209, 256)
[ok] imc2023_heritage: clusters=11 outliers=58 images=209
Inference embeddings shape: (76, 256)
[ok] imc2023_theather_imc2024_church: clusters=7 outliers=10 images=76
Inference embeddings shape: (138, 256)
[ok] imc2024_dioscuri_baalshamin: clusters=10 outliers=14 images=138
Inference embeddings shape: (214, 256)
[ok] imc2024_lizard_pond: clusters=13 outliers=28 images=214
Inference embeddings shape: (225, 256)
[ok] pt_brandenburg_british_buckingham: clusters=7 outliers=11 images=225
Inference embeddings shape: (168, 256)
[ok] pt_piazzasanmarco_grandplace: clusters=9 outliers=12 images=168
Inference embeddings shape: (51, 256)
[ok] stairs: clusters=7 outliers=0 images=51
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.45_topm3.csv rows=1498
+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/cluster_retrieval.py --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_finetuned_train --out-csv /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.55_topmNone.csv --topk 30 --min-sim 0.55 --method louvain --min-cluster-size 3 --edge-scorer mlp --dataset amy_gardens --dataset fbk_vineyard --dataset imc2023_haiper --dataset imc2023_heritage --dataset imc2023_theather_imc2024_church --dataset imc2024_dioscuri_baalshamin --dataset imc2024_lizard_pond --dataset pt_brandenburg_british_buckingham --dataset pt_piazzasanmarco_grandplace --dataset stairs --edge-model /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/edge_models/edge_mlp_split.pt --mutual
Inference embeddings shape: (200, 256)
[ok] amy_gardens: clusters=4 outliers=2 images=200
Inference embeddings shape: (163, 256)
[ok] fbk_vineyard: clusters=3 outliers=1 images=163
Inference embeddings shape: (54, 256)
[ok] imc2023_haiper: clusters=3 outliers=0 images=54
Inference embeddings shape: (209, 256)
[ok] imc2023_heritage: clusters=5 outliers=55 images=209
Inference embeddings shape: (76, 256)
[ok] imc2023_theather_imc2024_church: clusters=3 outliers=0 images=76
Inference embeddings shape: (138, 256)
[ok] imc2024_dioscuri_baalshamin: clusters=5 outliers=7 images=138
Inference embeddings shape: (214, 256)
[ok] imc2024_lizard_pond: clusters=6 outliers=20 images=214
Inference embeddings shape: (225, 256)
[ok] pt_brandenburg_british_buckingham: clusters=3 outliers=1 images=225
Inference embeddings shape: (168, 256)
[ok] pt_piazzasanmarco_grandplace: clusters=3 outliers=0 images=168
Inference embeddings shape: (51, 256)
[ok] stairs: clusters=3 outliers=0 images=51
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/tmp_cfg4_train_louvain_mins0.55_topmNone.csv rows=1498

ClusterCfg(topk=30, mutual=True, min_sim=0.35, method='greedy', min_cluster_size=3, edge_scorer='mlp', edge_model=PosixPath('/home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/edge_models/edge_mlp_split.pt'), edge_topm=None)

In [ ]:
# Run config 4 on the holdout test datasets using the selected hyperparams.
CFG4 = best_cfg4
CLUSTERS4 = RESULTS_DIR / "clusters_cfg4_everything_selected.csv"
run_cluster_retrieval(cache_root=CACHE_FINETUNED_TEST, out_csv=CLUSTERS4, datasets=test_datasets, cfg=CFG4)
res4 = eval_clusters(name="cfg4_everything_selected", clusters_csv=CLUSTERS4)

res4["overall"]

+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/cluster_retrieval.py --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_finetuned_test --out-csv /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/clusters_cfg4_everything_selected.csv --topk 30 --min-sim 0.35 --method greedy --min-cluster-size 3 --edge-scorer mlp --dataset ETs --dataset pt_sacrecoeur_trevi_tajmahal --dataset pt_stpeters_stpauls --edge-model /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/edge_models/edge_mlp_split.pt --mutual
Inference embeddings shape: (22, 256)
[ok] ETs: clusters=3 outliers=0 images=22
Inference embeddings shape: (225, 256)
[ok] pt_sacrecoeur_trevi_tajmahal: clusters=3 outliers=1 images=225
Inference embeddings shape: (200, 256)
[ok] pt_stpeters_stpauls: clusters=2 outliers=0 images=200
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/clusters_cfg4_everything_selected.csv rows=447

{'datasets': ['ETs', 'pt_sacrecoeur_trevi_tajmahal', 'pt_stpeters_stpauls'],
 'macro_final_mean': 0.9345278797728686,
 'micro_mAA': 0.9864864864864865,
 'micro_CS': 0.9909502262443439,
 'micro_final': 0.9887133182844244}

## 9) Aggregate results + visuals

In [ ]:
def _stack_scores(name: str, res: dict) -> pd.DataFrame:
    df = res["scores_df"].copy()
    df.insert(0, "config", name)
    return df[["config", "dataset", "mAA", "clustering_score", "final_score", "n_images_in_scenes", "n_correct"]]


scores_all = pd.concat(
    [
        _stack_scores("1) inference-only", res1),
        _stack_scores("2) finetuned DINO", res2),
        _stack_scores("3) finetuned + EdgeMLP", res3),
        _stack_scores("4) everything (selected)", res4),
    ],
    ignore_index=True,
)
scores_all.to_csv(RESULTS_DIR / "ablation_scores_by_dataset.csv", index=False)
scores_all

,config,dataset,mAA,clustering_score,final_score,n_images_in_scenes,n_correct
0,1) inference-only,ETs,1.000000,0.863636,0.926829,19,19
1,1) inference-only,pt_sacrecoeur_trevi_tajmahal,0.675556,1.000000,0.806366,225,152
2,1) inference-only,pt_stpeters_stpauls,0.535000,1.000000,0.697068,200,107
3,2) finetuned DINO,ETs,1.000000,0.863636,0.926829,19,19
4,2) finetuned DINO,pt_sacrecoeur_trevi_tajmahal,0.715556,1.000000,0.834197,225,161
5,2) finetuned DINO,pt_stpeters_stpauls,0.580000,1.000000,0.734177,200,116
6,3) finetuned + EdgeMLP,ETs,0.789474,0.833333,0.810811,19,15
7,3) finetuned + EdgeMLP,pt_sacrecoeur_trevi_tajmahal,0.626667,1.000000,0.770492,225,141
8,3) finetuned + EdgeMLP,pt_stpeters_stpauls,0.315000,1.000000,0.479087,200,63
9,4) everything (selected),ETs,0.789474,0.833333,0.810811,19,15
10,4) everything (selected),pt_sacrecoeur_trevi_tajmahal,0.995556,1.000000,0.997773,225,224
11,4) everything (selected),pt_stpeters_stpauls,0.995000,0.995000,0.995000,200,199

In [ ]:
# Final score per dataset (grouped bars)
fig = px.bar(
    scores_all,
    x="dataset",
    y="final_score",
    color="config",
    barmode="group",
    title=f"Final Score by dataset ({SPLIT_TAG})",
)
fig.update_layout(xaxis_title="Dataset", yaxis_title="Final Score")
fig.show()

In [ ]:
# Final score per dataset (grouped bars)
fig = px.bar(
    scores_all,
    x="dataset",
    y="final_score",
    color="config",
    barmode="group",
    title=f"Final Score by dataset",
)
fig.update_layout(xaxis_title="Dataset", yaxis_title="Final Score")
fig.show()

In [ ]:
# mAA vs Clustering Score tradeoff
fig = px.scatter(
    scores_all,
    x="mAA",
    y="clustering_score",
    color="config",
    symbol="dataset",
    hover_data=["final_score", "n_correct", "n_images_in_scenes"],
    title="mAA vs Clustering Score",
)
fig.update_layout(xaxis_title="mAA (recall)", yaxis_title="Clustering Score (precision)")
fig.show()

In [ ]:
# Overall micro scores (one bar per config)
overall_rows = []
for name, res in [
    ("1) inference-only", res1),
    ("2) finetuned DINO", res2),
    ("3) finetuned + EdgeMLP", res3),
    ("4) everything (selected)", res4),
]:
    overall_rows.append(
        {
            "config": name,
            "micro_mAA": float(res["overall"]["micro_mAA"]),
            "micro_CS": float(res["overall"]["micro_CS"]),
            "micro_final": float(res["overall"]["micro_final"]),
        }
    )

overall_df = pd.DataFrame(overall_rows)
overall_df.to_csv(RESULTS_DIR / "ablation_overall_micro.csv", index=False)
fig = px.bar(overall_df, x="config", y="micro_final", title="Overall micro Final Score")
fig.update_layout(xaxis_title="Config", yaxis_title="micro Final")
fig.show()
overall_df

                     config  micro_mAA  micro_CS  micro_final
0         1) inference-only   0.626126  0.989324     0.766897
1         2) finetuned DINO   0.666667  0.989967     0.796770
2    3) finetuned + EdgeMLP   0.493243  0.986486     0.657658
3  4) everything (selected)   0.986486  0.990950     0.988713

In [ ]:
# If you ran the sweep: visualize the sweep surface (train split selection)
if SWEEP and SWEEP_OUT.exists():
    sweep_df = pd.read_csv(SWEEP_OUT)
    sweep_df["edge_topm"] = sweep_df["edge_topm"].fillna(-1).astype(int)
    sweep_df["edge_topm_label"] = sweep_df["edge_topm"].map(lambda x: "None" if x < 0 else str(x))
    fig = px.density_heatmap(
        sweep_df,
        x="min_sim",
        y="edge_topm_label",
        z="micro_final",
        facet_col="method",
        histfunc="avg",
        title="Train split sweep: micro Final (avg)",
    )
    fig.update_layout(xaxis_title="min_sim", yaxis_title="edge_topm")
    fig.show()
else:
    print("(skip) sweep not run")

## 10) Extra visuals (cluster sizes + GT↔cluster overlap heatmaps)

In [ ]:
def cluster_size_table(*, pred_csv: Path, config_name: str) -> pd.DataFrame:
    df = pd.read_csv(pred_csv)
    df = df.rename(columns={"scene": "pred_cluster"})
    df["pred_cluster"] = df["pred_cluster"].astype(str)
    df = df[df["pred_cluster"].str.lower() != OUTLIERS_LABEL.lower()].copy()
    out = (
        df.groupby(["dataset", "pred_cluster"], as_index=False)
        .size()
        .rename(columns={"size": "cluster_size"})
    )
    out.insert(0, "config", config_name)
    return out


sizes = pd.concat(
    [
        cluster_size_table(pred_csv=CLUSTERS1, config_name="1) inference-only"),
        cluster_size_table(pred_csv=CLUSTERS2, config_name="2) finetuned DINO"),
        cluster_size_table(pred_csv=CLUSTERS3, config_name="3) finetuned + EdgeMLP"),
        cluster_size_table(pred_csv=CLUSTERS4, config_name="4) everything (selected)"),
    ],
    ignore_index=True,
)

fig = px.box(
    sizes,
    x="dataset",
    y="cluster_size",
    color="config",
    points="all",
    title="Predicted cluster size distribution (excluding outliers)",
)
fig.update_layout(xaxis_title="Dataset", yaxis_title="Cluster size")
fig.show()

sizes.head()

              config                       dataset  pred_cluster  cluster_size
0  1) inference-only                           ETs  cluster_0001            12
1  1) inference-only                           ETs  cluster_0002            10
2  1) inference-only  pt_sacrecoeur_trevi_tajmahal  cluster_0001            59
3  1) inference-only  pt_sacrecoeur_trevi_tajmahal  cluster_0002            51
4  1) inference-only  pt_sacrecoeur_trevi_tajmahal  cluster_0003            42

In [ ]:
def overlap_heatmap(*, dataset: str, pred_csv: Path, config_name: str) -> None:
    gt = pd.read_csv(TEST_SPLIT_LABELS)
    gt = gt[gt["dataset"] == dataset].copy()
    if DROP_GT_OUTLIERS:
        gt = gt[gt["scene"].astype(str).str.lower() != OUTLIERS_LABEL.lower()].copy()
    gt["image_key"] = gt["image"].map(lambda x: Path(str(x)).stem)

    gt_scenes = {
        str(scene): set(g["image_key"].tolist()) for scene, g in gt.groupby("scene", sort=True)
    }

    pred = pd.read_csv(pred_csv)
    pred = pred[pred["dataset"] == dataset].copy()
    pred["pred_cluster"] = pred["scene"].astype(str)
    pred["image_key"] = pred["image_id"].map(lambda x: Path(str(x)).stem)
    pred = pred[pred["pred_cluster"].str.lower() != OUTLIERS_LABEL.lower()].copy()

    pred_clusters = {
        str(c): set(g["image_key"].tolist()) for c, g in pred.groupby("pred_cluster", sort=True)
    }

    # Sort clusters by size for readability.
    clusters_sorted = sorted(pred_clusters.keys(), key=lambda c: (-len(pred_clusters[c]), c))
    scenes_sorted = sorted(gt_scenes.keys())

    mat = []
    for s in scenes_sorted:
        row = []
        for c in clusters_sorted:
            row.append(len(gt_scenes[s] & pred_clusters[c]))
        mat.append(row)

    dfm = pd.DataFrame(mat, index=scenes_sorted, columns=clusters_sorted)
    fig = px.imshow(
        dfm,
        text_auto=True,
        aspect="auto",
        title=f"{dataset}: GT scenes vs predicted clusters ({config_name})",
    )
    fig.update_layout(xaxis_title="Predicted cluster", yaxis_title="GT scene")
    fig.show()


SHOW_HEATMAPS = True
if SHOW_HEATMAPS:
    for ds in test_datasets:
        overlap_heatmap(dataset=ds, pred_csv=CLUSTERS1, config_name="1) inference-only")
        overlap_heatmap(dataset=ds, pred_csv=CLUSTERS2, config_name="2) finetuned DINO")
        overlap_heatmap(dataset=ds, pred_csv=CLUSTERS3, config_name="3) finetuned + EdgeMLP")
        overlap_heatmap(dataset=ds, pred_csv=CLUSTERS4, config_name="4) everything (selected)")

## 11) SfM matcher comparison (COLMAP / DINO / Diffusion / LightGlue)

Optional: run sparse SfM on the **same clusters** using different matchers.
- COLMAP: classic SIFT matcher
- DINO: patch-descriptor matcher
- Diffusion: diffusion-feature matcher
- LightGlue: ALIKED + LightGlue matcher (optional dependency)

Notes:
- This section runs **sparse-only** SfM (faster).
- LightGlue requires the `lightglue` package + weights.
- Results are saved under `outputs/ablation_<split>/sfm_matcher_compare/`.

In [25]:
import shutil

SFM_OUT_ROOT = OUT_ROOT / "sfm_matcher_compare"
SFM_OUT_ROOT.mkdir(parents=True, exist_ok=True)

# Use the selected clustering (cfg4 by default).
CLUSTERS_FOR_SFM = CLUSTERS4

RUN_SFM_MATCHERS = True  # set True to run COLMAP/DINO/DIFFUSION
RUN_LIGHTGLUE = True  # set True to run ALIKED+LightGlue matcher

RUNNER = "auto"  # auto|local|docker (for colmap_dense_clusters)
OVERWRITE_SFM = False

LIGHTGLUE_CACHE = REPO_ROOT / "cache" / "lightglue_features"
LIGHTGLUE_MAX_KPTS = 2048
LIGHTGLUE_PAIRING = "auto"  # auto|exhaustive|topk
LIGHTGLUE_TOPK = 10
LIGHTGLUE_MIN_INLIERS = 15

def run_recon_matcher(*, matcher: str, out_root: Path) -> None:
    cmd = [
        sys.executable,
        "scripts/colmap_dense_clusters.py",
        "--clusters-csv",
        str(CLUSTERS_FOR_SFM),
        "--cache-root",
        str(CACHE_FINETUNED_TEST),
        "--data-root",
        str(TEST_SPLIT_ROOT),
        "--output-root",
        str(out_root),
        "--runner",
        str(RUNNER),
        "--matcher",
        str(matcher),
        "--sparse-only",
    ]
    if OVERWRITE_SFM:
        cmd += ["--overwrite"]
    run(cmd, env=env)

def _load_meta_map(cache_root: Path, dataset: str) -> dict[str, Path]:
    meta_path = cache_root / dataset / "meta.json"
    if not meta_path.exists():
        return {}
    meta = json.loads(meta_path.read_text())
    image_ids = meta.get("image_ids", [])
    paths = meta.get("paths", [])
    if not isinstance(image_ids, list) or not isinstance(paths, list) or len(image_ids) != len(paths):
        return {}
    out: dict[str, Path] = {}
    for image_id, p in zip(image_ids, paths, strict=False):
        out[str(image_id)] = Path(str(p))
    return out

def _resolve_image_path(*, dataset: str, image_id: str, meta_map: dict[str, Path]) -> Path | None:
    if image_id in meta_map:
        p = meta_map[image_id]
        p = p if p.is_absolute() else (REPO_ROOT / p)
        return p if p.exists() else None
    base = TEST_SPLIT_ROOT / dataset / image_id
    for ext in (".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tif", ".tiff"):
        p = base.with_suffix(ext)
        if p.exists():
            return p
    return None

def _prepare_images_dir(*, dataset: str, scene: str, image_ids: list[str], out_dir: Path, meta_map: dict[str, Path]) -> Path:
    images_dir = out_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)
    desired = set()
    for image_id in image_ids:
        p = _resolve_image_path(dataset=dataset, image_id=str(image_id), meta_map=meta_map)
        if p is None:
            print(f"[warn] missing image {dataset}/{scene}: {image_id}")
            continue
        dst = images_dir / p.name
        desired.add(dst.name)
        if not dst.exists():
            shutil.copy2(p, dst)
    for entry in images_dir.iterdir():
        if entry.is_file() and entry.name not in desired:
            entry.unlink(missing_ok=True)
    return images_dir

def run_lightglue_sfm(*, clusters_csv: Path, out_root: Path) -> None:
    import pandas as pd
    clusters = pd.read_csv(clusters_csv)
    clusters = clusters[clusters["scene"].astype(str).str.lower() != "outliers"].copy()

    for (dataset, scene), g in clusters.groupby(["dataset", "scene"], sort=True):
        image_ids = g["image_id"].astype(str).tolist()
        if len(image_ids) < 2:
            continue
        out_dir = out_root / f"{dataset}_{scene}"
        if out_dir.exists() and not OVERWRITE_SFM:
            print(f"[skip] lightglue {dataset}/{scene}: exists")
            continue
        if OVERWRITE_SFM and out_dir.exists():
            shutil.rmtree(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        meta_map = _load_meta_map(CACHE_FINETUNED_TEST, str(dataset))
        images_dir = _prepare_images_dir(dataset=str(dataset), scene=str(scene), image_ids=image_ids, out_dir=out_dir, meta_map=meta_map)

        db_path = out_dir / "colmap_lightglue.db"
        sparse_root = out_dir / "sparse"
        sparse_root.mkdir(parents=True, exist_ok=True)

        cmd = [
            sys.executable,
            "scripts/lightglue_to_colmap.py",
            "--images-dir",
            str(images_dir),
            "--db-path",
            str(db_path),
            "--cache-dir",
            str(LIGHTGLUE_CACHE),
            "--max-keypoints",
            str(int(LIGHTGLUE_MAX_KPTS)),
            "--pairing",
            str(LIGHTGLUE_PAIRING),
            "--topk",
            str(int(LIGHTGLUE_TOPK)),
            "--min-inliers",
            str(int(LIGHTGLUE_MIN_INLIERS)),
        ]
        if OVERWRITE_SFM:
            cmd += ["--overwrite"]
        run(cmd, env=env)

        mapper_cmd = [
            "colmap",
            "mapper",
            "--database_path",
            str(db_path),
            "--image_path",
            str(images_dir),
            "--output_path",
            str(sparse_root),
            "--Mapper.ba_refine_principal_point",
            "0",
        ]
        print("+", shlex.join(mapper_cmd), flush=True)
        subprocess.run(mapper_cmd, check=True, cwd=str(REPO_ROOT))

if RUN_SFM_MATCHERS:
    run_recon_matcher(matcher="colmap", out_root=SFM_OUT_ROOT / "recon_colmap")
    run_recon_matcher(matcher="dino", out_root=SFM_OUT_ROOT / "recon_dino")
    run_recon_matcher(matcher="diffusion", out_root=SFM_OUT_ROOT / "recon_diffusion")
else:
    print("[skip] COLMAP/DINO/Diffusion SfM (RUN_SFM_MATCHERS=False)")

if RUN_LIGHTGLUE:
    run_lightglue_sfm(clusters_csv=CLUSTERS_FOR_SFM, out_root=SFM_OUT_ROOT / "recon_lightglue")
else:
    print("[skip] LightGlue SfM (RUN_LIGHTGLUE=False)")

+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/colmap_dense_clusters.py --clusters-csv /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/clusters_cfg4_everything_selected.csv --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_finetuned_test --data-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/data/test_split_holdout_ets_sacrecoeur_stpeters --output-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap --runner auto --matcher colmap --sparse-only
[info] Docker COLMAP does not support --Mapper.local_ba_min_tri_angle; disabling it.
Runner: docker
Clusters: 8
[cluster] 1/8: ETs/cluster_0001
[run] ETs/cluster_0001: images=10 matcher=colmap
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap feature_extractor --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0001/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0001/images --ImageReader.camera_model SIMPLE_RADIAL --ImageReader.single_camera 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 14:56:50.396721    27 misc.cc:44]
==============================================================================
Feature extraction
==============================================================================
I20251230 14:56:50.399441    38 sift.cc:720] Creating SIFT GPU feature extractor
I20251230 14:56:52.046226    39 feature_extraction.cc:260] Processed file [1/10]
I20251230 14:56:52.046317    39 feature_extraction.cc:263]   Name:            et_et000.png
I20251230 14:56:52.046326    39 feature_extraction.cc:272]   Dimensions:      480 x 640
I20251230 14:56:52.046331    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:56:52.046336    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:56:52.046350    39 feature_extraction.cc:282]   Features:        2319 (SIFT)
I20251230 14:56:52.071269    39 feature_extraction.cc:260] Processed file [2/10]
I20251230 14:56:52.071337    39 feature_extraction.cc:263]   Name:            et_et001.png
I20251230 14:56:52.071345    39 feature_extraction.cc:272]   Dimensions:      480 x 640
I20251230 14:56:52.071350    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:56:52.071355    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:56:52.071367    39 feature_extraction.cc:282]   Features:        2130 (SIFT)
I20251230 14:56:52.091077    39 feature_extraction.cc:260] Processed file [3/10]
I20251230 14:56:52.091148    39 feature_extraction.cc:263]   Name:            et_et002.png
I20251230 14:56:52.091153    39 feature_extraction.cc:272]   Dimensions:      480 x 640
I20251230 14:56:52.091157    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:56:52.091161    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:56:52.091169    39 feature_extraction.cc:282]   Features:        1849 (SIFT)
I20251230 14:56:52.111764    39 feature_extraction.cc:260] Processed file [4/10]
I20251230 14:56:52.111845    39 feature_extraction.cc:263]   Name:            et_et003.png
I20251230 14:56:52.111855    39 feature_extraction.cc:272]   Dimensions:      480 x 640
I20251230 14:56:52.111857    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:56:52.111863    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:56:52.111872    39 feature_extraction.cc:282]   Features:        2504 (SIFT)
I20251230 14:56:52.139160    39 feature_extraction.cc:260] Processed file [5/10]
I20251230 14:56:52.139238    39 feature_extraction.cc:263]   Name:            et_et004.png
I20251230 14:56:52.139250    39 feature_extraction.cc:272]   Dimensions:      480 x 640
I20251230 14:56:52.139257    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:56:52.139264    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:56:52.139305    39 feature_extraction.cc:282]   Features:        3151 (SIFT)
I20251230 14:56:52.164741    39 feature_extraction.cc:260] Processed file [6/10]
I20251230 14:56:52.164822    39 feature_extraction.cc:263]   Name:            et_et005.png
I20251230 14:56:52.164830    39 feature_extraction.cc:272]   Dimensions:      480 x 640
I20251230 14:56:52.164835    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:56:52.164840    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:56:52.164850    39 feature_extraction.cc:282]   Features:        1998 (SIFT)
I20251230 14:56:52.188774    39 feature_extraction.cc:260] Processed file [7/10]
I20251230 14:56:52.188840    39 feature_extraction.cc:263]   Name:            et_et006.png
I20251230 14:56:52.188845    39 feature_extraction.cc:272]   Dimensions:      480 x 640
I20251230 14:56:52.188849    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:56:52.188853    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:56:52.188866    39 feature_extraction.cc:282]   Features:        1916 (SIFT)
I20251230 14:56:52.213129    39 feature_extraction.cc:260] Processed file [8/10]
I20251230 14:56:52.213204    39 feature_extraction.cc:263]   Name:            et_et007.png
I20251230 14:56:52.213213    39 feature_extraction.cc:272]   Dimensions:      480 x 640
I20251230 14:56:52.213219    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:56:52.213225    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:56:52.213235    39 feature_extraction.cc:282]   Features:        1744 (SIFT)
I20251230 14:56:52.237686    39 feature_extraction.cc:260] Processed file [9/10]
I20251230 14:56:52.237756    39 feature_extraction.cc:263]   Name:            et_et008.png
I20251230 14:56:52.237762    39 feature_extraction.cc:272]   Dimensions:      480 x 640
I20251230 14:56:52.237766    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:56:52.237771    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:56:52.237780    39 feature_extraction.cc:282]   Features:        2048 (SIFT)
I20251230 14:56:52.238471    39 feature_extraction.cc:260] Processed file [10/10]
I20251230 14:56:52.238517    39 feature_extraction.cc:263]   Name:            outliers_out_et001.png
E20251230 14:56:52.238524    39 feature_extraction.cc:267] outliers_out_et001.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:56:52.258145    27 timer.cc:90] Elapsed time: 0.031 [minutes]

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap exhaustive_matcher --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0001/colmap.db

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 14:57:05.148552    27 misc.cc:44]
==============================================================================
Feature matching & geometric verification
==============================================================================
I20251230 14:57:05.257699    28 feature_matching_utils.cc:78] Bind FeatureMatcherWorker to GPU device 0
I20251230 14:57:05.257848    28 sift.cc:1446] Creating SIFT GPU feature matcher
I20251230 14:57:05.305814    27 pairing.cc:180] Generating exhaustive image pairs...
I20251230 14:57:05.305876    27 pairing.cc:213] Processing block [1/1, 1/1]
I20251230 14:57:06.473440    27 feature_matching.cc:117] in 1.168s
I20251230 14:57:06.473507    27 timer.cc:90] Elapsed time: 0.022 [minutes]

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0001/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0001/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0001/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 3 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 2.0 --Mapper.tri_min_angle 1.5 --Mapper.filter_min_tri_angle 1.5 --Mapper.tri_ignore_two_view_tracks 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 14:57:20.223659     1 incremental_pipeline.cc:264] Loading database
I20251230 14:57:20.292372     1 database_cache.cc:67] Loading rigs...
I20251230 14:57:20.292428     1 database_cache.cc:77]  1 in 0.000s
I20251230 14:57:20.292436     1 database_cache.cc:85] Loading cameras...
I20251230 14:57:20.292445     1 database_cache.cc:103]  1 in 0.000s
I20251230 14:57:20.292449     1 database_cache.cc:111] Loading frames...
I20251230 14:57:20.292469     1 database_cache.cc:126]  9 in 0.000s
I20251230 14:57:20.292472     1 database_cache.cc:134] Loading matches...
I20251230 14:57:20.292555     1 database_cache.cc:139]  31 in 0.000s
I20251230 14:57:20.292575     1 database_cache.cc:155] Loading images...
I20251230 14:57:20.293197     1 database_cache.cc:239]  9 in 0.001s (connected 9)
I20251230 14:57:20.293231     1 database_cache.cc:250] Building correspondence graph...
I20251230 14:57:20.312335     1 database_cache.cc:277]  in 0.019s (ignored 0)
I20251230 14:57:20.312608     1 timer.cc:90] Elapsed time: 0.000 [minutes]
I20251230 14:57:20.316761     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 14:57:20.632671     1 incremental_pipeline.cc:335] Registering initial image pair #2 and #3
I20251230 14:57:20.651057     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 14:57:21.509022     1 incremental_pipeline.cc:439] Registering image #1 (num_reg_frames=2)
I20251230 14:57:21.509078     1 incremental_pipeline.cc:442] => Image sees 205 / 1152 points
I20251230 14:57:21.677800     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 14:57:21.703361     1 incremental_pipeline.cc:439] Registering image #4 (num_reg_frames=3)
I20251230 14:57:21.703434     1 incremental_pipeline.cc:442] => Image sees 299 / 936 points
I20251230 14:57:21.751188     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 14:57:21.793596     1 incremental_pipeline.cc:439] Registering image #5 (num_reg_frames=4)
I20251230 14:57:21.793699     1 incremental_pipeline.cc:442] => Image sees 376 / 838 points
I20251230 14:57:21.860966     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 14:57:21.892660     1 incremental_pipeline.cc:439] Registering image #6 (num_reg_frames=5)
I20251230 14:57:21.892719     1 incremental_pipeline.cc:442] => Image sees 76 / 877 points
I20251230 14:57:21.939011     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 14:57:21.972229     1 incremental_pipeline.cc:439] Registering image #9 (num_reg_frames=6)
I20251230 14:57:21.972332     1 incremental_pipeline.cc:442] => Image sees 84 / 534 points
I20251230 14:57:22.022800     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 14:57:22.059363     1 incremental_pipeline.cc:439] Registering image #8 (num_reg_frames=7)
I20251230 14:57:22.059419     1 incremental_pipeline.cc:442] => Image sees 169 / 933 points
I20251230 14:57:22.093389     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 14:57:22.142506     1 incremental_pipeline.cc:439] Registering image #7 (num_reg_frames=8)
I20251230 14:57:22.142585     1 incremental_pipeline.cc:442] => Image sees 442 / 892 points
I20251230 14:57:22.204180     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 14:57:22.256901     1 incremental_pipeline.cc:597] Keeping successful reconstruction
I20251230 14:57:22.343168     1 timer.cc:90] Elapsed time: 0.035 [minutes]

[ok] ETs/cluster_0001: sparse model ready at /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0001/sparse/0
[cluster] 2/8: ETs/cluster_0002
[run] ETs/cluster_0002: images=8 matcher=colmap
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap feature_extractor --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0002/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0002/images --ImageReader.camera_model SIMPLE_RADIAL --ImageReader.single_camera 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 14:57:31.109764    27 misc.cc:44]
==============================================================================
Feature extraction
==============================================================================
I20251230 14:57:31.110997    38 sift.cc:720] Creating SIFT GPU feature extractor
I20251230 14:57:32.456312    39 feature_extraction.cc:260] Processed file [1/8]
I20251230 14:57:32.456374    39 feature_extraction.cc:263]   Name:            another_et_another_et001.png
I20251230 14:57:32.456380    39 feature_extraction.cc:272]   Dimensions:      360 x 640
I20251230 14:57:32.456383    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:57:32.456387    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:57:32.456394    39 feature_extraction.cc:282]   Features:        2372 (SIFT)
I20251230 14:57:32.457970    39 feature_extraction.cc:260] Processed file [2/8]
I20251230 14:57:32.458019    39 feature_extraction.cc:263]   Name:            another_et_another_et002.png
I20251230 14:57:32.458025    39 feature_extraction.cc:272]   Dimensions:      360 x 640
I20251230 14:57:32.458029    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:57:32.458032    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:57:32.458043    39 feature_extraction.cc:282]   Features:        2360 (SIFT)
I20251230 14:57:32.459901    39 feature_extraction.cc:260] Processed file [3/8]
I20251230 14:57:32.459934    39 feature_extraction.cc:263]   Name:            another_et_another_et003.png
I20251230 14:57:32.459940    39 feature_extraction.cc:272]   Dimensions:      360 x 640
I20251230 14:57:32.459944    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:57:32.459947    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:57:32.459954    39 feature_extraction.cc:282]   Features:        2413 (SIFT)
I20251230 14:57:32.481040    39 feature_extraction.cc:260] Processed file [4/8]
I20251230 14:57:32.481104    39 feature_extraction.cc:263]   Name:            another_et_another_et004.png
I20251230 14:57:32.481112    39 feature_extraction.cc:272]   Dimensions:      360 x 640
I20251230 14:57:32.481117    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:57:32.481119    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:57:32.481127    39 feature_extraction.cc:282]   Features:        2388 (SIFT)
I20251230 14:57:32.503078    39 feature_extraction.cc:260] Processed file [5/8]
I20251230 14:57:32.503167    39 feature_extraction.cc:263]   Name:            another_et_another_et005.png
I20251230 14:57:32.503177    39 feature_extraction.cc:272]   Dimensions:      360 x 640
I20251230 14:57:32.503183    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:57:32.503189    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:57:32.503202    39 feature_extraction.cc:282]   Features:        2311 (SIFT)
I20251230 14:57:32.529379    39 feature_extraction.cc:260] Processed file [6/8]
I20251230 14:57:32.529444    39 feature_extraction.cc:263]   Name:            another_et_another_et006.png
I20251230 14:57:32.529455    39 feature_extraction.cc:272]   Dimensions:      360 x 640
I20251230 14:57:32.529458    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:57:32.529469    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:57:32.529476    39 feature_extraction.cc:282]   Features:        2080 (SIFT)
I20251230 14:57:32.530359    39 feature_extraction.cc:260] Processed file [7/8]
I20251230 14:57:32.530400    39 feature_extraction.cc:263]   Name:            outliers_out_et002.png
E20251230 14:57:32.530407    39 feature_extraction.cc:267] outliers_out_et002.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:57:32.530413    39 feature_extraction.cc:260] Processed file [8/8]
I20251230 14:57:32.530416    39 feature_extraction.cc:263]   Name:            outliers_out_et003.png
E20251230 14:57:32.530419    39 feature_extraction.cc:267] outliers_out_et003.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:57:32.539141    27 timer.cc:90] Elapsed time: 0.024 [minutes]

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap exhaustive_matcher --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0002/colmap.db

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 14:57:50.023433    27 misc.cc:44]
==============================================================================
Feature matching & geometric verification
==============================================================================
I20251230 14:57:50.150503    28 feature_matching_utils.cc:78] Bind FeatureMatcherWorker to GPU device 0
I20251230 14:57:50.150636    28 sift.cc:1446] Creating SIFT GPU feature matcher
I20251230 14:57:50.176129    27 pairing.cc:180] Generating exhaustive image pairs...
I20251230 14:57:50.176203    27 pairing.cc:213] Processing block [1/1, 1/1]
I20251230 14:57:52.096077    27 feature_matching.cc:117] in 1.920s
I20251230 14:57:52.096131    27 timer.cc:90] Elapsed time: 0.035 [minutes]

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0002/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0002/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0002/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 3 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 2.0 --Mapper.tri_min_angle 1.5 --Mapper.filter_min_tri_angle 1.5 --Mapper.tri_ignore_two_view_tracks 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 14:58:01.712941     1 incremental_pipeline.cc:264] Loading database
I20251230 14:58:01.922322     1 database_cache.cc:67] Loading rigs...
I20251230 14:58:01.991984     1 database_cache.cc:77]  1 in 0.070s
I20251230 14:58:01.992063     1 database_cache.cc:85] Loading cameras...
I20251230 14:58:02.161273     1 database_cache.cc:103]  1 in 0.169s
I20251230 14:58:02.161357     1 database_cache.cc:111] Loading frames...
I20251230 14:58:02.161417     1 database_cache.cc:126]  6 in 0.000s
I20251230 14:58:02.161422     1 database_cache.cc:134] Loading matches...
I20251230 14:58:02.161509     1 database_cache.cc:139]  15 in 0.000s
I20251230 14:58:02.161545     1 database_cache.cc:155] Loading images...
I20251230 14:58:02.340837     1 database_cache.cc:239]  6 in 0.179s (connected 6)
I20251230 14:58:02.340914     1 database_cache.cc:250] Building correspondence graph...
I20251230 14:58:02.345234     1 database_cache.cc:277]  in 0.004s (ignored 0)
I20251230 14:58:02.345757     1 timer.cc:90] Elapsed time: 0.010 [minutes]
I20251230 14:58:02.406697     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 14:58:02.594163     1 incremental_pipeline.cc:335] Registering initial image pair #2 and #5
I20251230 14:58:02.595587     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 14:58:03.447440     1 incremental_pipeline.cc:439] Registering image #4 (num_reg_frames=2)
I20251230 14:58:03.447500     1 incremental_pipeline.cc:442] => Image sees 249 / 963 points
I20251230 14:58:03.584177     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 14:58:03.605286     1 incremental_pipeline.cc:439] Registering image #1 (num_reg_frames=3)
I20251230 14:58:03.605340     1 incremental_pipeline.cc:442] => Image sees 367 / 1190 points
I20251230 14:58:03.662138     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 14:58:03.710234     1 incremental_pipeline.cc:439] Registering image #3 (num_reg_frames=4)
I20251230 14:58:03.710297     1 incremental_pipeline.cc:442] => Image sees 312 / 677 points
I20251230 14:58:03.779706     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 14:58:03.812091     1 incremental_pipeline.cc:439] Registering image #6 (num_reg_frames=5)
I20251230 14:58:03.812152     1 incremental_pipeline.cc:442] => Image sees 226 / 358 points
I20251230 14:58:03.877084     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 14:58:03.908775     1 incremental_pipeline.cc:597] Keeping successful reconstruction
I20251230 14:58:03.937840     1 timer.cc:90] Elapsed time: 0.037 [minutes]

[ok] ETs/cluster_0002: sparse model ready at /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0002/sparse/0
[cluster] 3/8: ETs/cluster_0003
[run] ETs/cluster_0003: images=4 matcher=colmap
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap feature_extractor --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0003/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0003/images --ImageReader.camera_model SIMPLE_RADIAL --ImageReader.single_camera 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 14:58:12.584882    27 misc.cc:44]
==============================================================================
Feature extraction
==============================================================================
I20251230 14:58:12.585947    38 sift.cc:720] Creating SIFT GPU feature extractor
I20251230 14:58:13.675930    39 feature_extraction.cc:260] Processed file [1/4]
I20251230 14:58:13.676007    39 feature_extraction.cc:263]   Name:            another_et_another_et007.png
I20251230 14:58:13.676013    39 feature_extraction.cc:272]   Dimensions:      360 x 640
I20251230 14:58:13.676016    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:58:13.676020    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:58:13.676028    39 feature_extraction.cc:282]   Features:        2279 (SIFT)
I20251230 14:58:13.697433    39 feature_extraction.cc:260] Processed file [2/4]
I20251230 14:58:13.697516    39 feature_extraction.cc:263]   Name:            another_et_another_et008.png
I20251230 14:58:13.697525    39 feature_extraction.cc:272]   Dimensions:      360 x 640
I20251230 14:58:13.697530    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:58:13.697535    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:58:13.697547    39 feature_extraction.cc:282]   Features:        2076 (SIFT)
I20251230 14:58:13.721379    39 feature_extraction.cc:260] Processed file [3/4]
I20251230 14:58:13.721454    39 feature_extraction.cc:263]   Name:            another_et_another_et009.png
I20251230 14:58:13.721462    39 feature_extraction.cc:272]   Dimensions:      360 x 640
I20251230 14:58:13.721465    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:58:13.721470    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:58:13.721479    39 feature_extraction.cc:282]   Features:        1538 (SIFT)
I20251230 14:58:13.744062    39 feature_extraction.cc:260] Processed file [4/4]
I20251230 14:58:13.744163    39 feature_extraction.cc:263]   Name:            another_et_another_et010.png
I20251230 14:58:13.744170    39 feature_extraction.cc:272]   Dimensions:      360 x 640
I20251230 14:58:13.744174    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:58:13.744179    39 feature_extraction.cc:278]   Focal Length:    768.00px
I20251230 14:58:13.744191    39 feature_extraction.cc:282]   Features:        1234 (SIFT)
I20251230 14:58:13.755849    27 timer.cc:90] Elapsed time: 0.020 [minutes]

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap exhaustive_matcher --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0003/colmap.db

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 14:58:25.790400    27 misc.cc:44]
==============================================================================
Feature matching & geometric verification
==============================================================================
I20251230 14:58:25.944976    28 feature_matching_utils.cc:78] Bind FeatureMatcherWorker to GPU device 0
I20251230 14:58:25.945115    28 sift.cc:1446] Creating SIFT GPU feature matcher
I20251230 14:58:25.946209    27 pairing.cc:180] Generating exhaustive image pairs...
I20251230 14:58:25.946249    27 pairing.cc:213] Processing block [1/1, 1/1]
I20251230 14:58:27.541229    27 feature_matching.cc:117] in 1.595s
I20251230 14:58:27.541339    27 timer.cc:90] Elapsed time: 0.029 [minutes]

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0003/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0003/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0003/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 3 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 2.0 --Mapper.tri_min_angle 1.5 --Mapper.filter_min_tri_angle 1.5 --Mapper.tri_ignore_two_view_tracks 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 14:58:39.246235     1 incremental_pipeline.cc:264] Loading database
I20251230 14:58:39.608975     1 database_cache.cc:67] Loading rigs...
I20251230 14:58:39.609170     1 database_cache.cc:77]  1 in 0.000s
I20251230 14:58:39.609201     1 database_cache.cc:85] Loading cameras...
I20251230 14:58:39.609215     1 database_cache.cc:103]  1 in 0.000s
I20251230 14:58:39.609220     1 database_cache.cc:111] Loading frames...
I20251230 14:58:39.609239     1 database_cache.cc:126]  4 in 0.000s
I20251230 14:58:39.609244     1 database_cache.cc:134] Loading matches...
I20251230 14:58:39.609288     1 database_cache.cc:139]  6 in 0.000s
I20251230 14:58:39.609305     1 database_cache.cc:155] Loading images...
I20251230 14:58:39.693377     1 database_cache.cc:239]  4 in 0.084s (connected 4)
I20251230 14:58:39.693459     1 database_cache.cc:250] Building correspondence graph...
I20251230 14:58:39.693629     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 14:58:39.693946     1 timer.cc:90] Elapsed time: 0.003 [minutes]
I20251230 14:58:39.694123     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 14:58:39.700059     1 incremental_pipeline.cc:335] Registering initial image pair #2 and #1
I20251230 14:58:39.700428     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 14:58:39.715761     1 incremental_pipeline.cc:439] Registering image #3 (num_reg_frames=2)
I20251230 14:58:39.715822     1 incremental_pipeline.cc:442] => Image sees 40 / 136 points
I20251230 14:58:39.724017     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 14:58:39.732831     1 incremental_pipeline.cc:439] Registering image #4 (num_reg_frames=3)
I20251230 14:58:39.732882     1 incremental_pipeline.cc:442] => Image sees 30 / 76 points
I20251230 14:58:39.740552     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 14:58:39.747678     1 incremental_pipeline.cc:597] Keeping successful reconstruction
I20251230 14:58:39.748970     1 timer.cc:90] Elapsed time: 0.008 [minutes]

[ok] ETs/cluster_0003: sparse model ready at /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/ETs_cluster_0003/sparse/0
[cluster] 4/8: pt_sacrecoeur_trevi_tajmahal/cluster_0001
[run] pt_sacrecoeur_trevi_tajmahal/cluster_0001: images=75 matcher=colmap
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap feature_extractor --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0001/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0001/images --ImageReader.camera_model SIMPLE_RADIAL --ImageReader.single_camera 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 14:59:03.647066    27 misc.cc:44]
==============================================================================
Feature extraction
==============================================================================
I20251230 14:59:03.648125    38 sift.cc:720] Creating SIFT GPU feature extractor
I20251230 14:59:04.884588    39 feature_extraction.cc:260] Processed file [1/75]
I20251230 14:59:04.884655    39 feature_extraction.cc:263]   Name:            taj_mahal_02760416_4808737899.png
I20251230 14:59:04.884660    39 feature_extraction.cc:272]   Dimensions:      1060 x 781
I20251230 14:59:04.884663    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 14:59:04.884667    39 feature_extraction.cc:278]   Focal Length:    1272.00px
I20251230 14:59:04.884675    39 feature_extraction.cc:282]   Features:        4664 (SIFT)
I20251230 14:59:05.005071    39 feature_extraction.cc:260] Processed file [2/75]
I20251230 14:59:05.005144    39 feature_extraction.cc:263]   Name:            taj_mahal_03779515_11822031593.png
E20251230 14:59:05.005153    39 feature_extraction.cc:267] taj_mahal_03779515_11822031593.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.005191    39 feature_extraction.cc:260] Processed file [3/75]
I20251230 14:59:05.005198    39 feature_extraction.cc:263]   Name:            taj_mahal_05099279_2123782505.png
E20251230 14:59:05.005203    39 feature_extraction.cc:267] taj_mahal_05099279_2123782505.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.005208    39 feature_extraction.cc:260] Processed file [4/75]
I20251230 14:59:05.005213    39 feature_extraction.cc:263]   Name:            taj_mahal_05644193_4809375226.png
E20251230 14:59:05.005215    39 feature_extraction.cc:267] taj_mahal_05644193_4809375226.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.005228    39 feature_extraction.cc:260] Processed file [5/75]
I20251230 14:59:05.005234    39 feature_extraction.cc:263]   Name:            taj_mahal_07292828_6865863886.png
E20251230 14:59:05.005239    39 feature_extraction.cc:267] taj_mahal_07292828_6865863886.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.005342    39 feature_extraction.cc:260] Processed file [6/75]
I20251230 14:59:05.005378    39 feature_extraction.cc:263]   Name:            taj_mahal_07295255_5949580464.png
E20251230 14:59:05.005384    39 feature_extraction.cc:267] taj_mahal_07295255_5949580464.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.005399    39 feature_extraction.cc:260] Processed file [7/75]
I20251230 14:59:05.005405    39 feature_extraction.cc:263]   Name:            taj_mahal_09748237_4479958542.png
E20251230 14:59:05.005409    39 feature_extraction.cc:267] taj_mahal_09748237_4479958542.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.005412    39 feature_extraction.cc:260] Processed file [8/75]
I20251230 14:59:05.005414    39 feature_extraction.cc:263]   Name:            taj_mahal_15626988_320395276.png
E20251230 14:59:05.005417    39 feature_extraction.cc:267] taj_mahal_15626988_320395276.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.005461    39 feature_extraction.cc:260] Processed file [9/75]
I20251230 14:59:05.005489    39 feature_extraction.cc:263]   Name:            taj_mahal_16773607_5525472114.png
E20251230 14:59:05.005496    39 feature_extraction.cc:267] taj_mahal_16773607_5525472114.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.005499    39 feature_extraction.cc:260] Processed file [10/75]
I20251230 14:59:05.005503    39 feature_extraction.cc:263]   Name:            taj_mahal_17911381_11822031993.png
E20251230 14:59:05.005506    39 feature_extraction.cc:267] taj_mahal_17911381_11822031993.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.005571    39 feature_extraction.cc:260] Processed file [11/75]
I20251230 14:59:05.005597    39 feature_extraction.cc:263]   Name:            taj_mahal_21749909_452666809.png
E20251230 14:59:05.005604    39 feature_extraction.cc:267] taj_mahal_21749909_452666809.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.005607    39 feature_extraction.cc:260] Processed file [12/75]
I20251230 14:59:05.005611    39 feature_extraction.cc:263]   Name:            taj_mahal_23360557_2453971988.png
E20251230 14:59:05.005614    39 feature_extraction.cc:267] taj_mahal_23360557_2453971988.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.005654    39 feature_extraction.cc:260] Processed file [13/75]
I20251230 14:59:05.005686    39 feature_extraction.cc:263]   Name:            taj_mahal_25038173_427948647.png
E20251230 14:59:05.005693    39 feature_extraction.cc:267] taj_mahal_25038173_427948647.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.005699    39 feature_extraction.cc:260] Processed file [14/75]
I20251230 14:59:05.005704    39 feature_extraction.cc:263]   Name:            taj_mahal_28658320_3250275528.png
E20251230 14:59:05.005710    39 feature_extraction.cc:267] taj_mahal_28658320_3250275528.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.005714    39 feature_extraction.cc:260] Processed file [15/75]
I20251230 14:59:05.005719    39 feature_extraction.cc:263]   Name:            taj_mahal_33243562_4772593759.png
E20251230 14:59:05.005723    39 feature_extraction.cc:267] taj_mahal_33243562_4772593759.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.005728    39 feature_extraction.cc:260] Processed file [16/75]
I20251230 14:59:05.005733    39 feature_extraction.cc:263]   Name:            taj_mahal_33561486_8345882977.png
E20251230 14:59:05.005736    39 feature_extraction.cc:267] taj_mahal_33561486_8345882977.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.016002    39 feature_extraction.cc:260] Processed file [17/75]
I20251230 14:59:05.016052    39 feature_extraction.cc:263]   Name:            taj_mahal_33878661_5337234382.png
E20251230 14:59:05.016057    39 feature_extraction.cc:267] taj_mahal_33878661_5337234382.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.027364    39 feature_extraction.cc:260] Processed file [18/75]
I20251230 14:59:05.027412    39 feature_extraction.cc:263]   Name:            taj_mahal_34892661_4479236831.png
E20251230 14:59:05.027419    39 feature_extraction.cc:267] taj_mahal_34892661_4479236831.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.041800    39 feature_extraction.cc:260] Processed file [19/75]
I20251230 14:59:05.041846    39 feature_extraction.cc:263]   Name:            taj_mahal_35012799_233724898.png
E20251230 14:59:05.041852    39 feature_extraction.cc:267] taj_mahal_35012799_233724898.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.055380    39 feature_extraction.cc:260] Processed file [20/75]
I20251230 14:59:05.055438    39 feature_extraction.cc:263]   Name:            taj_mahal_35310867_4710497352.png
E20251230 14:59:05.055444    39 feature_extraction.cc:267] taj_mahal_35310867_4710497352.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.064841    39 feature_extraction.cc:260] Processed file [21/75]
I20251230 14:59:05.064891    39 feature_extraction.cc:263]   Name:            taj_mahal_35871047_6486466789.png
E20251230 14:59:05.064898    39 feature_extraction.cc:267] taj_mahal_35871047_6486466789.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.076013    39 feature_extraction.cc:260] Processed file [22/75]
I20251230 14:59:05.076064    39 feature_extraction.cc:263]   Name:            taj_mahal_36670333_3773568633.png
E20251230 14:59:05.076071    39 feature_extraction.cc:267] taj_mahal_36670333_3773568633.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.085294    39 feature_extraction.cc:260] Processed file [23/75]
I20251230 14:59:05.085333    39 feature_extraction.cc:263]   Name:            taj_mahal_40047213_6060347747.png
E20251230 14:59:05.085340    39 feature_extraction.cc:267] taj_mahal_40047213_6060347747.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.099784    39 feature_extraction.cc:260] Processed file [24/75]
I20251230 14:59:05.099853    39 feature_extraction.cc:263]   Name:            taj_mahal_40301482_6349100470.png
E20251230 14:59:05.099861    39 feature_extraction.cc:267] taj_mahal_40301482_6349100470.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.121032    39 feature_extraction.cc:260] Processed file [25/75]
I20251230 14:59:05.121093    39 feature_extraction.cc:263]   Name:            taj_mahal_40357326_9141483717.png
E20251230 14:59:05.121105    39 feature_extraction.cc:267] taj_mahal_40357326_9141483717.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.132860    39 feature_extraction.cc:260] Processed file [26/75]
I20251230 14:59:05.132915    39 feature_extraction.cc:263]   Name:            taj_mahal_40461214_8192836476.png
E20251230 14:59:05.132921    39 feature_extraction.cc:267] taj_mahal_40461214_8192836476.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.145865    39 feature_extraction.cc:260] Processed file [27/75]
I20251230 14:59:05.145921    39 feature_extraction.cc:263]   Name:            taj_mahal_41314954_4418442825.png
E20251230 14:59:05.145927    39 feature_extraction.cc:267] taj_mahal_41314954_4418442825.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.156430    39 feature_extraction.cc:260] Processed file [28/75]
I20251230 14:59:05.156483    39 feature_extraction.cc:263]   Name:            taj_mahal_45203396_7995388605.png
E20251230 14:59:05.156489    39 feature_extraction.cc:267] taj_mahal_45203396_7995388605.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.162627    39 feature_extraction.cc:260] Processed file [29/75]
I20251230 14:59:05.162668    39 feature_extraction.cc:263]   Name:            taj_mahal_46195638_3569985892.png
E20251230 14:59:05.162674    39 feature_extraction.cc:267] taj_mahal_46195638_3569985892.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.177569    39 feature_extraction.cc:260] Processed file [30/75]
I20251230 14:59:05.177623    39 feature_extraction.cc:263]   Name:            taj_mahal_46483850_3092227510.png
E20251230 14:59:05.177629    39 feature_extraction.cc:267] taj_mahal_46483850_3092227510.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.193001    39 feature_extraction.cc:260] Processed file [31/75]
I20251230 14:59:05.193050    39 feature_extraction.cc:263]   Name:            taj_mahal_47981545_2123782613.png
E20251230 14:59:05.193056    39 feature_extraction.cc:267] taj_mahal_47981545_2123782613.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.198524    39 feature_extraction.cc:260] Processed file [32/75]
I20251230 14:59:05.198571    39 feature_extraction.cc:263]   Name:            taj_mahal_48590156_9372591744.png
E20251230 14:59:05.198577    39 feature_extraction.cc:267] taj_mahal_48590156_9372591744.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.210076    39 feature_extraction.cc:260] Processed file [33/75]
I20251230 14:59:05.210145    39 feature_extraction.cc:263]   Name:            taj_mahal_51297211_3293524007.png
E20251230 14:59:05.210152    39 feature_extraction.cc:267] taj_mahal_51297211_3293524007.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.224205    39 feature_extraction.cc:260] Processed file [34/75]
I20251230 14:59:05.224262    39 feature_extraction.cc:263]   Name:            taj_mahal_52650931_8268706459.png
E20251230 14:59:05.224270    39 feature_extraction.cc:267] taj_mahal_52650931_8268706459.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.237921    39 feature_extraction.cc:260] Processed file [35/75]
I20251230 14:59:05.237985    39 feature_extraction.cc:263]   Name:            taj_mahal_53757432_11494604856.png
E20251230 14:59:05.237994    39 feature_extraction.cc:267] taj_mahal_53757432_11494604856.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.252532    39 feature_extraction.cc:260] Processed file [36/75]
I20251230 14:59:05.252590    39 feature_extraction.cc:263]   Name:            taj_mahal_54900410_4709458745.png
E20251230 14:59:05.252597    39 feature_extraction.cc:267] taj_mahal_54900410_4709458745.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.270563    39 feature_extraction.cc:260] Processed file [37/75]
I20251230 14:59:05.270624    39 feature_extraction.cc:263]   Name:            taj_mahal_57532696_297637106.png
E20251230 14:59:05.270632    39 feature_extraction.cc:267] taj_mahal_57532696_297637106.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.288523    39 feature_extraction.cc:260] Processed file [38/75]
I20251230 14:59:05.288589    39 feature_extraction.cc:263]   Name:            taj_mahal_66281696_4846036976.png
E20251230 14:59:05.288595    39 feature_extraction.cc:267] taj_mahal_66281696_4846036976.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.304338    39 feature_extraction.cc:260] Processed file [39/75]
I20251230 14:59:05.304414    39 feature_extraction.cc:263]   Name:            taj_mahal_67319805_2215339300.png
E20251230 14:59:05.304423    39 feature_extraction.cc:267] taj_mahal_67319805_2215339300.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.320631    39 feature_extraction.cc:260] Processed file [40/75]
I20251230 14:59:05.320695    39 feature_extraction.cc:263]   Name:            taj_mahal_68263048_3884219324.png
E20251230 14:59:05.320703    39 feature_extraction.cc:267] taj_mahal_68263048_3884219324.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.325275    39 feature_extraction.cc:260] Processed file [41/75]
I20251230 14:59:05.325330    39 feature_extraction.cc:263]   Name:            taj_mahal_68284397_7307804012.png
E20251230 14:59:05.325335    39 feature_extraction.cc:267] taj_mahal_68284397_7307804012.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.342537    39 feature_extraction.cc:260] Processed file [42/75]
I20251230 14:59:05.342604    39 feature_extraction.cc:263]   Name:            taj_mahal_70456501_320396748.png
E20251230 14:59:05.342612    39 feature_extraction.cc:267] taj_mahal_70456501_320396748.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.356206    39 feature_extraction.cc:260] Processed file [43/75]
I20251230 14:59:05.356266    39 feature_extraction.cc:263]   Name:            taj_mahal_70518655_6429111743.png
E20251230 14:59:05.356274    39 feature_extraction.cc:267] taj_mahal_70518655_6429111743.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.360364    39 feature_extraction.cc:260] Processed file [44/75]
I20251230 14:59:05.360423    39 feature_extraction.cc:263]   Name:            taj_mahal_72418664_4552163871.png
E20251230 14:59:05.360431    39 feature_extraction.cc:267] taj_mahal_72418664_4552163871.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.377727    39 feature_extraction.cc:260] Processed file [45/75]
I20251230 14:59:05.377794    39 feature_extraction.cc:263]   Name:            taj_mahal_72721370_6780643247.png
E20251230 14:59:05.377800    39 feature_extraction.cc:267] taj_mahal_72721370_6780643247.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.395018    39 feature_extraction.cc:260] Processed file [46/75]
I20251230 14:59:05.395074    39 feature_extraction.cc:263]   Name:            taj_mahal_73045053_2123874963.png
E20251230 14:59:05.395081    39 feature_extraction.cc:267] taj_mahal_73045053_2123874963.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.409673    39 feature_extraction.cc:260] Processed file [47/75]
I20251230 14:59:05.409729    39 feature_extraction.cc:263]   Name:            taj_mahal_73346411_11842150495.png
E20251230 14:59:05.409736    39 feature_extraction.cc:267] taj_mahal_73346411_11842150495.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.420377    39 feature_extraction.cc:260] Processed file [48/75]
I20251230 14:59:05.420444    39 feature_extraction.cc:263]   Name:            taj_mahal_75694348_4552162843.png
E20251230 14:59:05.420451    39 feature_extraction.cc:267] taj_mahal_75694348_4552162843.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.430718    39 feature_extraction.cc:260] Processed file [49/75]
I20251230 14:59:05.430774    39 feature_extraction.cc:263]   Name:            taj_mahal_75960124_233048597.png
E20251230 14:59:05.430783    39 feature_extraction.cc:267] taj_mahal_75960124_233048597.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.443110    39 feature_extraction.cc:260] Processed file [50/75]
I20251230 14:59:05.443194    39 feature_extraction.cc:263]   Name:            taj_mahal_78595827_6619694947.png
E20251230 14:59:05.443230    39 feature_extraction.cc:267] taj_mahal_78595827_6619694947.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.455838    39 feature_extraction.cc:260] Processed file [51/75]
I20251230 14:59:05.455893    39 feature_extraction.cc:263]   Name:            taj_mahal_79695821_354966524.png
E20251230 14:59:05.455900    39 feature_extraction.cc:267] taj_mahal_79695821_354966524.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 14:59:05.467414    39 feature_extraction.cc:260] Processed file [52/75]
I20251230 14:59:05.467461    39 feature_extraction.cc:263]   Name:            taj_mahal_80209116_3299258442.png
E20251230 14:59:05.467468    39 feature_extraction.cc:267] taj_mahal_80209116_3299258442.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap exhaustive_matcher --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0001/colmap.db

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 14:59:14.719632    27 misc.cc:44]
==============================================================================
Feature matching & geometric verification
==============================================================================
I20251230 14:59:14.839397    28 feature_matching_utils.cc:78] Bind FeatureMatcherWorker to GPU device 0
I20251230 14:59:14.839524    28 sift.cc:1446] Creating SIFT GPU feature matcher
I20251230 14:59:14.842119    27 pairing.cc:180] Generating exhaustive image pairs...
I20251230 14:59:14.842170    27 pairing.cc:213] Processing block [1/1, 1/1]
I20251230 14:59:14.842191    27 feature_matching.cc:117] in 0.000s
I20251230 14:59:14.842198    27 timer.cc:90] Elapsed time: 0.002 [minutes]

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0001/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0001/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0001/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 3 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 2.0 --Mapper.tri_min_angle 1.5 --Mapper.filter_min_tri_angle 1.5 --Mapper.tri_ignore_two_view_tracks 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 14:59:29.968729     1 incremental_pipeline.cc:264] Loading database
I20251230 14:59:31.077212     1 database_cache.cc:67] Loading rigs...
I20251230 14:59:31.308795     1 database_cache.cc:77]  1 in 0.232s
I20251230 14:59:31.308866     1 database_cache.cc:85] Loading cameras...
I20251230 14:59:31.792076     1 database_cache.cc:103]  1 in 0.483s
I20251230 14:59:31.792166     1 database_cache.cc:111] Loading frames...
I20251230 14:59:31.892779     1 database_cache.cc:126]  1 in 0.101s
I20251230 14:59:31.892844     1 database_cache.cc:134] Loading matches...
I20251230 14:59:32.456759     1 database_cache.cc:139]  0 in 0.564s
I20251230 14:59:32.456822     1 database_cache.cc:155] Loading images...
I20251230 14:59:33.030719     1 database_cache.cc:239]  1 in 0.574s (connected 0)
I20251230 14:59:33.030791     1 database_cache.cc:250] Building correspondence graph...
I20251230 14:59:33.030810     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 14:59:33.031069     1 timer.cc:90] Elapsed time: 0.050 [minutes]
W20251230 14:59:33.031096     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 14:59:33.031102     1 sfm.cc:278] failed to create sparse model

[retry] pt_sacrecoeur_trevi_tajmahal/cluster_0001: mapper attempt 2 (min_model_size=2, init_min_inliers=15, init_min_tri_angle=1.0, tri_min_angle=0.25, local_ba_min_tri_angle=0.25, tri_ignore_two_view_tracks=0)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0001/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0001/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0001/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 2 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 1.0 --Mapper.tri_min_angle 0.25 --Mapper.filter_min_tri_angle 0.25 --Mapper.tri_ignore_two_view_tracks 0

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 14:59:42.411754     1 incremental_pipeline.cc:264] Loading database
I20251230 14:59:42.412902     1 database_cache.cc:67] Loading rigs...
I20251230 14:59:42.412966     1 database_cache.cc:77]  1 in 0.000s
I20251230 14:59:42.412974     1 database_cache.cc:85] Loading cameras...
I20251230 14:59:42.412983     1 database_cache.cc:103]  1 in 0.000s
I20251230 14:59:42.413000     1 database_cache.cc:111] Loading frames...
I20251230 14:59:42.413020     1 database_cache.cc:126]  1 in 0.000s
I20251230 14:59:42.413036     1 database_cache.cc:134] Loading matches...
I20251230 14:59:42.413046     1 database_cache.cc:139]  0 in 0.000s
I20251230 14:59:42.413051     1 database_cache.cc:155] Loading images...
I20251230 14:59:42.413069     1 database_cache.cc:239]  1 in 0.000s (connected 0)
I20251230 14:59:42.413086     1 database_cache.cc:250] Building correspondence graph...
I20251230 14:59:42.413097     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 14:59:42.413244     1 timer.cc:90] Elapsed time: 0.000 [minutes]
W20251230 14:59:42.413266     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 14:59:42.413272     1 sfm.cc:278] failed to create sparse model

[retry] pt_sacrecoeur_trevi_tajmahal/cluster_0001: mapper attempt 3 (min_model_size=2, init_min_inliers=8, init_min_tri_angle=0.5, tri_min_angle=0.05, local_ba_min_tri_angle=0.05, tri_ignore_two_view_tracks=0)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0001/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0001/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0001/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 8 --Mapper.min_model_size 2 --Mapper.init_min_num_inliers 8 --Mapper.init_min_tri_angle 0.5 --Mapper.tri_min_angle 0.05 --Mapper.filter_min_tri_angle 0.05 --Mapper.tri_ignore_two_view_tracks 0

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:00:01.457099     1 incremental_pipeline.cc:264] Loading database
I20251230 15:00:01.995492     1 database_cache.cc:67] Loading rigs...
I20251230 15:00:02.492892     1 database_cache.cc:77]  1 in 0.497s
I20251230 15:00:02.492988     1 database_cache.cc:85] Loading cameras...
I20251230 15:00:02.543025     1 database_cache.cc:103]  1 in 0.050s
I20251230 15:00:02.543131     1 database_cache.cc:111] Loading frames...
I20251230 15:00:02.552963     1 database_cache.cc:126]  1 in 0.010s
I20251230 15:00:02.553041     1 database_cache.cc:134] Loading matches...
I20251230 15:00:02.921494     1 database_cache.cc:139]  0 in 0.368s
I20251230 15:00:02.921561     1 database_cache.cc:155] Loading images...
I20251230 15:00:03.150238     1 database_cache.cc:239]  1 in 0.229s (connected 0)
I20251230 15:00:03.150352     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:00:03.167450     1 database_cache.cc:277]  in 0.017s (ignored 0)
I20251230 15:00:03.168066     1 timer.cc:90] Elapsed time: 0.028 [minutes]
W20251230 15:00:03.168113     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 15:00:03.168130     1 sfm.cc:278] failed to create sparse model

[retry] pt_sacrecoeur_trevi_tajmahal/cluster_0001: mapper attempt 4 (min_model_size=2, init_min_inliers=4, init_min_tri_angle=0.1, tri_min_angle=0.01, local_ba_min_tri_angle=0.01, tri_ignore_two_view_tracks=0)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0001/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0001/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0001/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 4 --Mapper.min_model_size 2 --Mapper.init_min_num_inliers 4 --Mapper.init_min_tri_angle 0.1 --Mapper.tri_min_angle 0.01 --Mapper.filter_min_tri_angle 0.01 --Mapper.tri_ignore_two_view_tracks 0

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:00:24.937521     1 incremental_pipeline.cc:264] Loading database
I20251230 15:00:25.074172     1 database_cache.cc:67] Loading rigs...
I20251230 15:00:25.074246     1 database_cache.cc:77]  1 in 0.000s
I20251230 15:00:25.074256     1 database_cache.cc:85] Loading cameras...
I20251230 15:00:25.074265     1 database_cache.cc:103]  1 in 0.000s
I20251230 15:00:25.074270     1 database_cache.cc:111] Loading frames...
I20251230 15:00:25.074281     1 database_cache.cc:126]  1 in 0.000s
I20251230 15:00:25.074285     1 database_cache.cc:134] Loading matches...
I20251230 15:00:25.074291     1 database_cache.cc:139]  0 in 0.000s
I20251230 15:00:25.074295     1 database_cache.cc:155] Loading images...
I20251230 15:00:25.074350     1 database_cache.cc:239]  1 in 0.000s (connected 0)
I20251230 15:00:25.074369     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:00:25.074379     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:00:25.074571     1 timer.cc:90] Elapsed time: 0.002 [minutes]
W20251230 15:00:25.074594     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 15:00:25.074600     1 sfm.cc:278] failed to create sparse model

[fail] pt_sacrecoeur_trevi_tajmahal/cluster_0001: COLMAP mapper failed after 4 attempts
[cluster] 5/8: pt_sacrecoeur_trevi_tajmahal/cluster_0002
[run] pt_sacrecoeur_trevi_tajmahal/cluster_0002: images=75 matcher=colmap
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap feature_extractor --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0002/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0002/images --ImageReader.camera_model SIMPLE_RADIAL --ImageReader.single_camera 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:01:04.851824    27 misc.cc:44]
==============================================================================
Feature extraction
==============================================================================
I20251230 15:01:04.852869    38 sift.cc:720] Creating SIFT GPU feature extractor
I20251230 15:01:06.602044    39 feature_extraction.cc:260] Processed file [1/75]
I20251230 15:01:06.602116    39 feature_extraction.cc:263]   Name:            trevi_fountain_00358444_4165248133.png
I20251230 15:01:06.602123    39 feature_extraction.cc:272]   Dimensions:      782 x 1061
I20251230 15:01:06.602126    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 15:01:06.602130    39 feature_extraction.cc:278]   Focal Length:    1273.20px
I20251230 15:01:06.602138    39 feature_extraction.cc:282]   Features:        10680 (SIFT)
I20251230 15:01:06.650218    39 feature_extraction.cc:260] Processed file [2/75]
I20251230 15:01:06.650285    39 feature_extraction.cc:263]   Name:            trevi_fountain_01241225_4293371290.png
E20251230 15:01:06.650301    39 feature_extraction.cc:267] trevi_fountain_01241225_4293371290.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.650329    39 feature_extraction.cc:260] Processed file [3/75]
I20251230 15:01:06.650336    39 feature_extraction.cc:263]   Name:            trevi_fountain_01404558_5160423697.png
E20251230 15:01:06.650339    39 feature_extraction.cc:267] trevi_fountain_01404558_5160423697.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.650367    39 feature_extraction.cc:260] Processed file [4/75]
I20251230 15:01:06.650370    39 feature_extraction.cc:263]   Name:            trevi_fountain_09071644_2938441433.png
E20251230 15:01:06.650374    39 feature_extraction.cc:267] trevi_fountain_09071644_2938441433.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.650379    39 feature_extraction.cc:260] Processed file [5/75]
I20251230 15:01:06.650382    39 feature_extraction.cc:263]   Name:            trevi_fountain_14195208_276265172.png
E20251230 15:01:06.650384    39 feature_extraction.cc:267] trevi_fountain_14195208_276265172.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.650388    39 feature_extraction.cc:260] Processed file [6/75]
I20251230 15:01:06.650391    39 feature_extraction.cc:263]   Name:            trevi_fountain_15038544_3727504813.png
E20251230 15:01:06.650395    39 feature_extraction.cc:267] trevi_fountain_15038544_3727504813.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.650398    39 feature_extraction.cc:260] Processed file [7/75]
I20251230 15:01:06.650403    39 feature_extraction.cc:263]   Name:            trevi_fountain_16517106_11484965983.png
E20251230 15:01:06.650405    39 feature_extraction.cc:267] trevi_fountain_16517106_11484965983.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.650473    39 feature_extraction.cc:260] Processed file [8/75]
I20251230 15:01:06.650487    39 feature_extraction.cc:263]   Name:            trevi_fountain_16771025_6187661240.png
E20251230 15:01:06.650491    39 feature_extraction.cc:267] trevi_fountain_16771025_6187661240.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.650496    39 feature_extraction.cc:260] Processed file [9/75]
I20251230 15:01:06.650499    39 feature_extraction.cc:263]   Name:            trevi_fountain_17378230_8657377873.png
E20251230 15:01:06.650502    39 feature_extraction.cc:267] trevi_fountain_17378230_8657377873.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.650559    39 feature_extraction.cc:260] Processed file [10/75]
I20251230 15:01:06.650570    39 feature_extraction.cc:263]   Name:            trevi_fountain_17750259_5579050866.png
E20251230 15:01:06.650578    39 feature_extraction.cc:267] trevi_fountain_17750259_5579050866.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.650592    39 feature_extraction.cc:260] Processed file [11/75]
I20251230 15:01:06.650597    39 feature_extraction.cc:263]   Name:            trevi_fountain_17804574_3525103748.png
E20251230 15:01:06.650600    39 feature_extraction.cc:267] trevi_fountain_17804574_3525103748.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.650775    39 feature_extraction.cc:260] Processed file [12/75]
I20251230 15:01:06.650811    39 feature_extraction.cc:263]   Name:            trevi_fountain_17973182_5956257468.png
E20251230 15:01:06.650820    39 feature_extraction.cc:267] trevi_fountain_17973182_5956257468.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.650839    39 feature_extraction.cc:260] Processed file [13/75]
I20251230 15:01:06.650846    39 feature_extraction.cc:263]   Name:            trevi_fountain_18865921_5109712344.png
E20251230 15:01:06.650866    39 feature_extraction.cc:267] trevi_fountain_18865921_5109712344.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.650877    39 feature_extraction.cc:260] Processed file [14/75]
I20251230 15:01:06.650897    39 feature_extraction.cc:263]   Name:            trevi_fountain_19939802_5963665770.png
E20251230 15:01:06.650904    39 feature_extraction.cc:267] trevi_fountain_19939802_5963665770.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.650924    39 feature_extraction.cc:260] Processed file [15/75]
I20251230 15:01:06.650931    39 feature_extraction.cc:263]   Name:            trevi_fountain_21017479_3693575843.png
E20251230 15:01:06.650936    39 feature_extraction.cc:267] trevi_fountain_21017479_3693575843.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.650941    39 feature_extraction.cc:260] Processed file [16/75]
I20251230 15:01:06.650946    39 feature_extraction.cc:263]   Name:            trevi_fountain_21324671_251787492.png
E20251230 15:01:06.650950    39 feature_extraction.cc:267] trevi_fountain_21324671_251787492.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.666888    39 feature_extraction.cc:260] Processed file [17/75]
I20251230 15:01:06.666937    39 feature_extraction.cc:263]   Name:            trevi_fountain_22494549_5871994022.png
E20251230 15:01:06.666958    39 feature_extraction.cc:267] trevi_fountain_22494549_5871994022.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.682271    39 feature_extraction.cc:260] Processed file [18/75]
I20251230 15:01:06.682318    39 feature_extraction.cc:263]   Name:            trevi_fountain_22555231_8007352373.png
E20251230 15:01:06.682324    39 feature_extraction.cc:267] trevi_fountain_22555231_8007352373.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.697631    39 feature_extraction.cc:260] Processed file [19/75]
I20251230 15:01:06.697675    39 feature_extraction.cc:263]   Name:            trevi_fountain_26921609_5411058517.png
E20251230 15:01:06.697681    39 feature_extraction.cc:267] trevi_fountain_26921609_5411058517.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.714311    39 feature_extraction.cc:260] Processed file [20/75]
I20251230 15:01:06.714358    39 feature_extraction.cc:263]   Name:            trevi_fountain_27009206_5185352408.png
E20251230 15:01:06.714365    39 feature_extraction.cc:267] trevi_fountain_27009206_5185352408.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.731549    39 feature_extraction.cc:260] Processed file [21/75]
I20251230 15:01:06.731604    39 feature_extraction.cc:263]   Name:            trevi_fountain_29250228_5522743340.png
E20251230 15:01:06.731611    39 feature_extraction.cc:267] trevi_fountain_29250228_5522743340.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.748219    39 feature_extraction.cc:260] Processed file [22/75]
I20251230 15:01:06.748296    39 feature_extraction.cc:263]   Name:            trevi_fountain_29511430_5519433926.png
E20251230 15:01:06.748306    39 feature_extraction.cc:267] trevi_fountain_29511430_5519433926.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.766211    39 feature_extraction.cc:260] Processed file [23/75]
I20251230 15:01:06.766263    39 feature_extraction.cc:263]   Name:            trevi_fountain_30002765_4759346847.png
E20251230 15:01:06.766268    39 feature_extraction.cc:267] trevi_fountain_30002765_4759346847.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.781363    39 feature_extraction.cc:260] Processed file [24/75]
I20251230 15:01:06.781422    39 feature_extraction.cc:263]   Name:            trevi_fountain_30069642_3966141600.png
E20251230 15:01:06.781428    39 feature_extraction.cc:267] trevi_fountain_30069642_3966141600.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.797447    39 feature_extraction.cc:260] Processed file [25/75]
I20251230 15:01:06.797493    39 feature_extraction.cc:263]   Name:            trevi_fountain_30910735_201249046.png
E20251230 15:01:06.797499    39 feature_extraction.cc:267] trevi_fountain_30910735_201249046.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.811005    39 feature_extraction.cc:260] Processed file [26/75]
I20251230 15:01:06.811076    39 feature_extraction.cc:263]   Name:            trevi_fountain_33816922_8591444000.png
E20251230 15:01:06.811084    39 feature_extraction.cc:267] trevi_fountain_33816922_8591444000.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.831300    39 feature_extraction.cc:260] Processed file [27/75]
I20251230 15:01:06.831362    39 feature_extraction.cc:263]   Name:            trevi_fountain_34630714_3685665828.png
E20251230 15:01:06.831370    39 feature_extraction.cc:267] trevi_fountain_34630714_3685665828.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.848731    39 feature_extraction.cc:260] Processed file [28/75]
I20251230 15:01:06.848781    39 feature_extraction.cc:263]   Name:            trevi_fountain_38993702_4733402071.png
E20251230 15:01:06.848788    39 feature_extraction.cc:267] trevi_fountain_38993702_4733402071.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.868244    39 feature_extraction.cc:260] Processed file [29/75]
I20251230 15:01:06.868304    39 feature_extraction.cc:263]   Name:            trevi_fountain_40184297_2989394429.png
E20251230 15:01:06.868311    39 feature_extraction.cc:267] trevi_fountain_40184297_2989394429.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.886389    39 feature_extraction.cc:260] Processed file [30/75]
I20251230 15:01:06.886484    39 feature_extraction.cc:263]   Name:            trevi_fountain_41815199_3578791286.png
E20251230 15:01:06.886492    39 feature_extraction.cc:267] trevi_fountain_41815199_3578791286.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.903743    39 feature_extraction.cc:260] Processed file [31/75]
I20251230 15:01:06.903793    39 feature_extraction.cc:263]   Name:            trevi_fountain_42098841_2972162031.png
E20251230 15:01:06.903800    39 feature_extraction.cc:267] trevi_fountain_42098841_2972162031.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.918694    39 feature_extraction.cc:260] Processed file [32/75]
I20251230 15:01:06.918740    39 feature_extraction.cc:263]   Name:            trevi_fountain_43321508_5715952972.png
E20251230 15:01:06.918746    39 feature_extraction.cc:267] trevi_fountain_43321508_5715952972.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.931619    39 feature_extraction.cc:260] Processed file [33/75]
I20251230 15:01:06.931667    39 feature_extraction.cc:263]   Name:            trevi_fountain_48230932_8038671426.png
E20251230 15:01:06.931674    39 feature_extraction.cc:267] trevi_fountain_48230932_8038671426.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.935979    39 feature_extraction.cc:260] Processed file [34/75]
I20251230 15:01:06.936024    39 feature_extraction.cc:263]   Name:            trevi_fountain_50357199_8205859052.png
E20251230 15:01:06.936030    39 feature_extraction.cc:267] trevi_fountain_50357199_8205859052.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.952677    39 feature_extraction.cc:260] Processed file [35/75]
I20251230 15:01:06.952737    39 feature_extraction.cc:263]   Name:            trevi_fountain_52144216_2711106071.png
E20251230 15:01:06.952744    39 feature_extraction.cc:267] trevi_fountain_52144216_2711106071.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.969954    39 feature_extraction.cc:260] Processed file [36/75]
I20251230 15:01:06.970012    39 feature_extraction.cc:263]   Name:            trevi_fountain_54470469_2296508341.png
E20251230 15:01:06.970019    39 feature_extraction.cc:267] trevi_fountain_54470469_2296508341.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:06.986047    39 feature_extraction.cc:260] Processed file [37/75]
I20251230 15:01:06.986091    39 feature_extraction.cc:263]   Name:            trevi_fountain_55838538_4636348360.png
E20251230 15:01:06.986097    39 feature_extraction.cc:267] trevi_fountain_55838538_4636348360.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:07.004246    39 feature_extraction.cc:260] Processed file [38/75]
I20251230 15:01:07.004343    39 feature_extraction.cc:263]   Name:            trevi_fountain_56026722_4376692497.png
E20251230 15:01:07.004352    39 feature_extraction.cc:267] trevi_fountain_56026722_4376692497.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:07.017906    39 feature_extraction.cc:260] Processed file [39/75]
I20251230 15:01:07.017967    39 feature_extraction.cc:263]   Name:            trevi_fountain_56493755_3454995877.png
E20251230 15:01:07.017974    39 feature_extraction.cc:267] trevi_fountain_56493755_3454995877.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:07.035622    39 feature_extraction.cc:260] Processed file [40/75]
I20251230 15:01:07.035707    39 feature_extraction.cc:263]   Name:            trevi_fountain_58525833_5956866479.png
E20251230 15:01:07.035715    39 feature_extraction.cc:267] trevi_fountain_58525833_5956866479.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:07.054860    39 feature_extraction.cc:260] Processed file [41/75]
I20251230 15:01:07.054916    39 feature_extraction.cc:263]   Name:            trevi_fountain_58732203_2711105477.png
E20251230 15:01:07.054937    39 feature_extraction.cc:267] trevi_fountain_58732203_2711105477.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:07.072244    39 feature_extraction.cc:260] Processed file [42/75]
I20251230 15:01:07.072294    39 feature_extraction.cc:263]   Name:            trevi_fountain_59883665_3581996971.png
E20251230 15:01:07.072299    39 feature_extraction.cc:267] trevi_fountain_59883665_3581996971.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:07.087365    39 feature_extraction.cc:260] Processed file [43/75]
I20251230 15:01:07.087553    39 feature_extraction.cc:263]   Name:            trevi_fountain_64273020_5411668132.png
E20251230 15:01:07.087571    39 feature_extraction.cc:267] trevi_fountain_64273020_5411668132.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:07.105564    39 feature_extraction.cc:260] Processed file [44/75]
I20251230 15:01:07.105619    39 feature_extraction.cc:263]   Name:            trevi_fountain_66347814_2029982255.png
E20251230 15:01:07.105626    39 feature_extraction.cc:267] trevi_fountain_66347814_2029982255.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:07.121891    39 feature_extraction.cc:260] Processed file [45/75]
I20251230 15:01:07.121934    39 feature_extraction.cc:263]   Name:            trevi_fountain_66677085_4725569846.png
E20251230 15:01:07.121940    39 feature_extraction.cc:267] trevi_fountain_66677085_4725569846.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:07.139492    39 feature_extraction.cc:260] Processed file [46/75]
I20251230 15:01:07.139539    39 feature_extraction.cc:263]   Name:            trevi_fountain_69481877_5327669439.png
E20251230 15:01:07.139560    39 feature_extraction.cc:267] trevi_fountain_69481877_5327669439.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:07.156052    39 feature_extraction.cc:260] Processed file [47/75]
I20251230 15:01:07.156112    39 feature_extraction.cc:263]   Name:            trevi_fountain_70315674_7178465185.png
E20251230 15:01:07.156118    39 feature_extraction.cc:267] trevi_fountain_70315674_7178465185.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:07.161520    39 feature_extraction.cc:260] Processed file [48/75]
I20251230 15:01:07.161571    39 feature_extraction.cc:263]   Name:            trevi_fountain_71421235_8100441323.png
E20251230 15:01:07.161576    39 feature_extraction.cc:267] trevi_fountain_71421235_8100441323.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:07.174997    39 feature_extraction.cc:260] Processed file [49/75]
I20251230 15:01:07.175053    39 feature_extraction.cc:263]   Name:            trevi_fountain_72669213_5987184866.png
E20251230 15:01:07.175061    39 feature_extraction.cc:267] trevi_fountain_72669213_5987184866.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:07.192786    39 feature_extraction.cc:260] Processed file [50/75]
I20251230 15:01:07.192836    39 feature_extraction.cc:263]   Name:            trevi_fountain_73284018_2156414038.png
E20251230 15:01:07.192843    39 feature_extraction.cc:267] trevi_fountain_73284018_2156414038.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:01:07.204576    39 feature_extraction.cc:260] Processed file [51/75]
I20251230 15:01:07.204629    39 feature_extraction.cc:263]   Name:            trevi_fountain_74305025_425098856.png

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap exhaustive_matcher --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0002/colmap.db

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:01:23.503638    27 misc.cc:44]
==============================================================================
Feature matching & geometric verification
==============================================================================
I20251230 15:01:23.677362    28 feature_matching_utils.cc:78] Bind FeatureMatcherWorker to GPU device 0
I20251230 15:01:23.775846    28 sift.cc:1446] Creating SIFT GPU feature matcher
I20251230 15:01:23.868088    27 pairing.cc:180] Generating exhaustive image pairs...
I20251230 15:01:23.868157    27 pairing.cc:213] Processing block [1/1, 1/1]
I20251230 15:01:23.868170    27 feature_matching.cc:117] in 0.000s
I20251230 15:01:23.868176    27 timer.cc:90] Elapsed time: 0.006 [minutes]

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0002/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0002/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0002/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 3 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 2.0 --Mapper.tri_min_angle 1.5 --Mapper.filter_min_tri_angle 1.5 --Mapper.tri_ignore_two_view_tracks 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:01:47.204798     1 incremental_pipeline.cc:264] Loading database
I20251230 15:01:47.593743     1 database_cache.cc:67] Loading rigs...
I20251230 15:01:47.663286     1 database_cache.cc:77]  1 in 0.070s
I20251230 15:01:47.663347     1 database_cache.cc:85] Loading cameras...
I20251230 15:01:48.290454     1 database_cache.cc:103]  1 in 0.627s
I20251230 15:01:48.290514     1 database_cache.cc:111] Loading frames...
I20251230 15:01:48.290551     1 database_cache.cc:126]  1 in 0.000s
I20251230 15:01:48.290556     1 database_cache.cc:134] Loading matches...
I20251230 15:01:48.290565     1 database_cache.cc:139]  0 in 0.000s
I20251230 15:01:48.290567     1 database_cache.cc:155] Loading images...
I20251230 15:01:48.290625     1 database_cache.cc:239]  1 in 0.000s (connected 0)
I20251230 15:01:48.290642     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:01:48.290654     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:01:48.290894     1 timer.cc:90] Elapsed time: 0.017 [minutes]
W20251230 15:01:48.290923     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 15:01:48.290934     1 sfm.cc:278] failed to create sparse model

[retry] pt_sacrecoeur_trevi_tajmahal/cluster_0002: mapper attempt 2 (min_model_size=2, init_min_inliers=15, init_min_tri_angle=1.0, tri_min_angle=0.25, local_ba_min_tri_angle=0.25, tri_ignore_two_view_tracks=0)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0002/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0002/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0002/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 2 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 1.0 --Mapper.tri_min_angle 0.25 --Mapper.filter_min_tri_angle 0.25 --Mapper.tri_ignore_two_view_tracks 0

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:02:02.782850     1 incremental_pipeline.cc:264] Loading database
I20251230 15:02:03.314314     1 database_cache.cc:67] Loading rigs...
I20251230 15:02:03.314447     1 database_cache.cc:77]  1 in 0.000s
I20251230 15:02:03.352458     1 database_cache.cc:85] Loading cameras...
I20251230 15:02:03.352548     1 database_cache.cc:103]  1 in 0.000s
I20251230 15:02:03.352555     1 database_cache.cc:111] Loading frames...
I20251230 15:02:03.352581     1 database_cache.cc:126]  1 in 0.000s
I20251230 15:02:03.352598     1 database_cache.cc:134] Loading matches...
I20251230 15:02:03.352609     1 database_cache.cc:139]  0 in 0.000s
I20251230 15:02:03.352612     1 database_cache.cc:155] Loading images...
I20251230 15:02:03.352654     1 database_cache.cc:239]  1 in 0.000s (connected 0)
I20251230 15:02:03.352658     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:02:03.352687     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:02:03.352980     1 timer.cc:90] Elapsed time: 0.010 [minutes]
W20251230 15:02:03.353015     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 15:02:03.353031     1 sfm.cc:278] failed to create sparse model

[retry] pt_sacrecoeur_trevi_tajmahal/cluster_0002: mapper attempt 3 (min_model_size=2, init_min_inliers=8, init_min_tri_angle=0.5, tri_min_angle=0.05, local_ba_min_tri_angle=0.05, tri_ignore_two_view_tracks=0)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0002/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0002/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0002/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 8 --Mapper.min_model_size 2 --Mapper.init_min_num_inliers 8 --Mapper.init_min_tri_angle 0.5 --Mapper.tri_min_angle 0.05 --Mapper.filter_min_tri_angle 0.05 --Mapper.tri_ignore_two_view_tracks 0

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:02:22.826793     1 incremental_pipeline.cc:264] Loading database
I20251230 15:02:23.718979     1 database_cache.cc:67] Loading rigs...
I20251230 15:02:23.719144     1 database_cache.cc:77]  1 in 0.000s
I20251230 15:02:23.719173     1 database_cache.cc:85] Loading cameras...
I20251230 15:02:23.719190     1 database_cache.cc:103]  1 in 0.000s
I20251230 15:02:23.719205     1 database_cache.cc:111] Loading frames...
I20251230 15:02:23.719226     1 database_cache.cc:126]  1 in 0.000s
I20251230 15:02:23.719242     1 database_cache.cc:134] Loading matches...
I20251230 15:02:24.246603     1 database_cache.cc:139]  0 in 0.527s
I20251230 15:02:24.246685     1 database_cache.cc:155] Loading images...
I20251230 15:02:24.246850     1 database_cache.cc:239]  1 in 0.000s (connected 0)
I20251230 15:02:24.246857     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:02:24.246862     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:02:24.247212     1 timer.cc:90] Elapsed time: 0.023 [minutes]
W20251230 15:02:24.247262     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 15:02:24.247269     1 sfm.cc:278] failed to create sparse model

[retry] pt_sacrecoeur_trevi_tajmahal/cluster_0002: mapper attempt 4 (min_model_size=2, init_min_inliers=4, init_min_tri_angle=0.1, tri_min_angle=0.01, local_ba_min_tri_angle=0.01, tri_ignore_two_view_tracks=0)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0002/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0002/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0002/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 4 --Mapper.min_model_size 2 --Mapper.init_min_num_inliers 4 --Mapper.init_min_tri_angle 0.1 --Mapper.tri_min_angle 0.01 --Mapper.filter_min_tri_angle 0.01 --Mapper.tri_ignore_two_view_tracks 0

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:02:45.165057     1 incremental_pipeline.cc:264] Loading database
I20251230 15:02:45.178237     1 database_cache.cc:67] Loading rigs...
I20251230 15:02:45.178357     1 database_cache.cc:77]  1 in 0.000s
I20251230 15:02:45.178373     1 database_cache.cc:85] Loading cameras...
I20251230 15:02:45.178387     1 database_cache.cc:103]  1 in 0.000s
I20251230 15:02:45.178391     1 database_cache.cc:111] Loading frames...
I20251230 15:02:45.178411     1 database_cache.cc:126]  1 in 0.000s
I20251230 15:02:45.178416     1 database_cache.cc:134] Loading matches...
I20251230 15:02:45.178426     1 database_cache.cc:139]  0 in 0.000s
I20251230 15:02:45.178433     1 database_cache.cc:155] Loading images...
I20251230 15:02:45.178464     1 database_cache.cc:239]  1 in 0.000s (connected 0)
I20251230 15:02:45.178489     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:02:45.178498     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:02:45.178755     1 timer.cc:90] Elapsed time: 0.000 [minutes]
W20251230 15:02:45.178795     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 15:02:45.178804     1 sfm.cc:278] failed to create sparse model

[fail] pt_sacrecoeur_trevi_tajmahal/cluster_0002: COLMAP mapper failed after 4 attempts
[cluster] 6/8: pt_sacrecoeur_trevi_tajmahal/cluster_0003
[run] pt_sacrecoeur_trevi_tajmahal/cluster_0003: images=74 matcher=colmap
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap feature_extractor --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0003/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0003/images --ImageReader.camera_model SIMPLE_RADIAL --ImageReader.single_camera 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:03:25.351661    27 misc.cc:44]
==============================================================================
Feature extraction
==============================================================================
I20251230 15:03:25.353947    38 sift.cc:720] Creating SIFT GPU feature extractor
I20251230 15:03:28.276538    39 feature_extraction.cc:260] Processed file [1/74]
I20251230 15:03:28.276600    39 feature_extraction.cc:263]   Name:            sacre_coeur_02928139_3448003521.png
I20251230 15:03:28.276607    39 feature_extraction.cc:272]   Dimensions:      780 x 1063
I20251230 15:03:28.276610    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 15:03:28.276614    39 feature_extraction.cc:278]   Focal Length:    1275.60px
I20251230 15:03:28.276623    39 feature_extraction.cc:282]   Features:        10124 (SIFT)
I20251230 15:03:28.812598    39 feature_extraction.cc:260] Processed file [2/74]
I20251230 15:03:28.812659    39 feature_extraction.cc:263]   Name:            sacre_coeur_04739785_8198592553.png
E20251230 15:03:28.812664    39 feature_extraction.cc:267] sacre_coeur_04739785_8198592553.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.812690    39 feature_extraction.cc:260] Processed file [3/74]
I20251230 15:03:28.812696    39 feature_extraction.cc:263]   Name:            sacre_coeur_04822190_12621366523.png
E20251230 15:03:28.812700    39 feature_extraction.cc:267] sacre_coeur_04822190_12621366523.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.812739    39 feature_extraction.cc:260] Processed file [4/74]
I20251230 15:03:28.812745    39 feature_extraction.cc:263]   Name:            sacre_coeur_10474405_6093717701.png
E20251230 15:03:28.812748    39 feature_extraction.cc:267] sacre_coeur_10474405_6093717701.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.812752    39 feature_extraction.cc:260] Processed file [5/74]
I20251230 15:03:28.812754    39 feature_extraction.cc:263]   Name:            sacre_coeur_11626754_2718827730.png
E20251230 15:03:28.812757    39 feature_extraction.cc:267] sacre_coeur_11626754_2718827730.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.812829    39 feature_extraction.cc:260] Processed file [6/74]
I20251230 15:03:28.812857    39 feature_extraction.cc:263]   Name:            sacre_coeur_16385535_4660789205.png
E20251230 15:03:28.812863    39 feature_extraction.cc:267] sacre_coeur_16385535_4660789205.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.812867    39 feature_extraction.cc:260] Processed file [7/74]
I20251230 15:03:28.812870    39 feature_extraction.cc:263]   Name:            sacre_coeur_16537684_4545274148.png
E20251230 15:03:28.812873    39 feature_extraction.cc:267] sacre_coeur_16537684_4545274148.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.812928    39 feature_extraction.cc:260] Processed file [8/74]
I20251230 15:03:28.812964    39 feature_extraction.cc:263]   Name:            sacre_coeur_16776129_4239663609.png
E20251230 15:03:28.812973    39 feature_extraction.cc:267] sacre_coeur_16776129_4239663609.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.812978    39 feature_extraction.cc:260] Processed file [9/74]
I20251230 15:03:28.812981    39 feature_extraction.cc:263]   Name:            sacre_coeur_16971221_7856309770.png
E20251230 15:03:28.812984    39 feature_extraction.cc:267] sacre_coeur_16971221_7856309770.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.813048    39 feature_extraction.cc:260] Processed file [10/74]
I20251230 15:03:28.813071    39 feature_extraction.cc:263]   Name:            sacre_coeur_18725380_2402129328.png
E20251230 15:03:28.813079    39 feature_extraction.cc:267] sacre_coeur_18725380_2402129328.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.813084    39 feature_extraction.cc:260] Processed file [11/74]
I20251230 15:03:28.813090    39 feature_extraction.cc:263]   Name:            sacre_coeur_23327088_8208333914.png
E20251230 15:03:28.813095    39 feature_extraction.cc:267] sacre_coeur_23327088_8208333914.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.813108    39 feature_extraction.cc:260] Processed file [12/74]
I20251230 15:03:28.813113    39 feature_extraction.cc:263]   Name:            sacre_coeur_24292909_11972893303.png
E20251230 15:03:28.813118    39 feature_extraction.cc:267] sacre_coeur_24292909_11972893303.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.813206    39 feature_extraction.cc:260] Processed file [13/74]
I20251230 15:03:28.813235    39 feature_extraction.cc:263]   Name:            sacre_coeur_28088482_1061487806.png
E20251230 15:03:28.813241    39 feature_extraction.cc:267] sacre_coeur_28088482_1061487806.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.813254    39 feature_extraction.cc:260] Processed file [14/74]
I20251230 15:03:28.813258    39 feature_extraction.cc:263]   Name:            sacre_coeur_30642459_5864476232.png
E20251230 15:03:28.813263    39 feature_extraction.cc:267] sacre_coeur_30642459_5864476232.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.813269    39 feature_extraction.cc:260] Processed file [15/74]
I20251230 15:03:28.813278    39 feature_extraction.cc:263]   Name:            sacre_coeur_32069695_13023252634.png
E20251230 15:03:28.813282    39 feature_extraction.cc:267] sacre_coeur_32069695_13023252634.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.813287    39 feature_extraction.cc:260] Processed file [16/74]
I20251230 15:03:28.813292    39 feature_extraction.cc:263]   Name:            sacre_coeur_32086795_402359870.png
E20251230 15:03:28.813297    39 feature_extraction.cc:267] sacre_coeur_32086795_402359870.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.826148    39 feature_extraction.cc:260] Processed file [17/74]
I20251230 15:03:28.826195    39 feature_extraction.cc:263]   Name:            sacre_coeur_32188921_4453876221.png
E20251230 15:03:28.826201    39 feature_extraction.cc:267] sacre_coeur_32188921_4453876221.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.843729    39 feature_extraction.cc:260] Processed file [18/74]
I20251230 15:03:28.843804    39 feature_extraction.cc:263]   Name:            sacre_coeur_33340964_112626481.png
E20251230 15:03:28.843811    39 feature_extraction.cc:267] sacre_coeur_33340964_112626481.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.854228    39 feature_extraction.cc:260] Processed file [19/74]
I20251230 15:03:28.854326    39 feature_extraction.cc:263]   Name:            sacre_coeur_34264811_99184810.png
E20251230 15:03:28.854339    39 feature_extraction.cc:267] sacre_coeur_34264811_99184810.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.873764    39 feature_extraction.cc:260] Processed file [20/74]
I20251230 15:03:28.873829    39 feature_extraction.cc:263]   Name:            sacre_coeur_34904068_5083153.png
E20251230 15:03:28.873835    39 feature_extraction.cc:267] sacre_coeur_34904068_5083153.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.890919    39 feature_extraction.cc:260] Processed file [21/74]
I20251230 15:03:28.891000    39 feature_extraction.cc:263]   Name:            sacre_coeur_35905283_32603557.png
E20251230 15:03:28.891007    39 feature_extraction.cc:267] sacre_coeur_35905283_32603557.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.896770    39 feature_extraction.cc:260] Processed file [22/74]
I20251230 15:03:28.896835    39 feature_extraction.cc:263]   Name:            sacre_coeur_37175111_6635304477.png
E20251230 15:03:28.896842    39 feature_extraction.cc:267] sacre_coeur_37175111_6635304477.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.915571    39 feature_extraction.cc:260] Processed file [23/74]
I20251230 15:03:28.915638    39 feature_extraction.cc:263]   Name:            sacre_coeur_38755762_4239668423.png
E20251230 15:03:28.915645    39 feature_extraction.cc:267] sacre_coeur_38755762_4239668423.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.934998    39 feature_extraction.cc:260] Processed file [24/74]
I20251230 15:03:28.935065    39 feature_extraction.cc:263]   Name:            sacre_coeur_39172134_3155998144.png
E20251230 15:03:28.935072    39 feature_extraction.cc:267] sacre_coeur_39172134_3155998144.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.953610    39 feature_extraction.cc:260] Processed file [25/74]
I20251230 15:03:28.953672    39 feature_extraction.cc:263]   Name:            sacre_coeur_39702035_1808089104.png
E20251230 15:03:28.953680    39 feature_extraction.cc:267] sacre_coeur_39702035_1808089104.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.970324    39 feature_extraction.cc:260] Processed file [26/74]
I20251230 15:03:28.970423    39 feature_extraction.cc:263]   Name:            sacre_coeur_39852107_3868092306.png
E20251230 15:03:28.970433    39 feature_extraction.cc:267] sacre_coeur_39852107_3868092306.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:28.988835    39 feature_extraction.cc:260] Processed file [27/74]
I20251230 15:03:28.988917    39 feature_extraction.cc:263]   Name:            sacre_coeur_41224690_4580747259.png
E20251230 15:03:28.988941    39 feature_extraction.cc:267] sacre_coeur_41224690_4580747259.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.009320    39 feature_extraction.cc:260] Processed file [28/74]
I20251230 15:03:29.009390    39 feature_extraction.cc:263]   Name:            sacre_coeur_42287322_536307676.png
E20251230 15:03:29.009397    39 feature_extraction.cc:267] sacre_coeur_42287322_536307676.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.028483    39 feature_extraction.cc:260] Processed file [29/74]
I20251230 15:03:29.028560    39 feature_extraction.cc:263]   Name:            sacre_coeur_45927449_5904684394.png
E20251230 15:03:29.028568    39 feature_extraction.cc:267] sacre_coeur_45927449_5904684394.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.040987    39 feature_extraction.cc:260] Processed file [30/74]
I20251230 15:03:29.041054    39 feature_extraction.cc:263]   Name:            sacre_coeur_46031506_3822251715.png
E20251230 15:03:29.041060    39 feature_extraction.cc:267] sacre_coeur_46031506_3822251715.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.056298    39 feature_extraction.cc:260] Processed file [31/74]
I20251230 15:03:29.056361    39 feature_extraction.cc:263]   Name:            sacre_coeur_46459330_5716002401.png
E20251230 15:03:29.056368    39 feature_extraction.cc:267] sacre_coeur_46459330_5716002401.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.072810    39 feature_extraction.cc:260] Processed file [32/74]
I20251230 15:03:29.072901    39 feature_extraction.cc:263]   Name:            sacre_coeur_47029087_8959697396.png
E20251230 15:03:29.072911    39 feature_extraction.cc:267] sacre_coeur_47029087_8959697396.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.091046    39 feature_extraction.cc:260] Processed file [33/74]
I20251230 15:03:29.091133    39 feature_extraction.cc:263]   Name:            sacre_coeur_47042061_9637017399.png
E20251230 15:03:29.091145    39 feature_extraction.cc:267] sacre_coeur_47042061_9637017399.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.110411    39 feature_extraction.cc:260] Processed file [34/74]
I20251230 15:03:29.110479    39 feature_extraction.cc:263]   Name:            sacre_coeur_47788810_3531619701.png
E20251230 15:03:29.110487    39 feature_extraction.cc:267] sacre_coeur_47788810_3531619701.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.130103    39 feature_extraction.cc:260] Processed file [35/74]
I20251230 15:03:29.130160    39 feature_extraction.cc:263]   Name:            sacre_coeur_48325951_2932818065.png
E20251230 15:03:29.130167    39 feature_extraction.cc:267] sacre_coeur_48325951_2932818065.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.134871    39 feature_extraction.cc:260] Processed file [36/74]
I20251230 15:03:29.134934    39 feature_extraction.cc:263]   Name:            sacre_coeur_49896012_2400282601.png
E20251230 15:03:29.134943    39 feature_extraction.cc:267] sacre_coeur_49896012_2400282601.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.152714    39 feature_extraction.cc:260] Processed file [37/74]
I20251230 15:03:29.152791    39 feature_extraction.cc:263]   Name:            sacre_coeur_52914810_3288295639.png
E20251230 15:03:29.152801    39 feature_extraction.cc:267] sacre_coeur_52914810_3288295639.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.166476    39 feature_extraction.cc:260] Processed file [38/74]
I20251230 15:03:29.166536    39 feature_extraction.cc:263]   Name:            sacre_coeur_55167859_91653543.png
E20251230 15:03:29.166544    39 feature_extraction.cc:267] sacre_coeur_55167859_91653543.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.185644    39 feature_extraction.cc:260] Processed file [39/74]
I20251230 15:03:29.185703    39 feature_extraction.cc:263]   Name:            sacre_coeur_55297752_267282770.png
E20251230 15:03:29.185710    39 feature_extraction.cc:267] sacre_coeur_55297752_267282770.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.196305    39 feature_extraction.cc:260] Processed file [40/74]
I20251230 15:03:29.196369    39 feature_extraction.cc:263]   Name:            sacre_coeur_55640818_3363877988.png
E20251230 15:03:29.196377    39 feature_extraction.cc:267] sacre_coeur_55640818_3363877988.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.211321    39 feature_extraction.cc:260] Processed file [41/74]
I20251230 15:03:29.211411    39 feature_extraction.cc:263]   Name:            sacre_coeur_55695069_9640098822.png
E20251230 15:03:29.211418    39 feature_extraction.cc:267] sacre_coeur_55695069_9640098822.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.225759    39 feature_extraction.cc:260] Processed file [42/74]
I20251230 15:03:29.225822    39 feature_extraction.cc:263]   Name:            sacre_coeur_61531052_7402696624.png
E20251230 15:03:29.225829    39 feature_extraction.cc:267] sacre_coeur_61531052_7402696624.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.239061    39 feature_extraction.cc:260] Processed file [43/74]
I20251230 15:03:29.239132    39 feature_extraction.cc:263]   Name:            sacre_coeur_66573940_9624143830.png
E20251230 15:03:29.239141    39 feature_extraction.cc:267] sacre_coeur_66573940_9624143830.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.258059    39 feature_extraction.cc:260] Processed file [44/74]
I20251230 15:03:29.258140    39 feature_extraction.cc:263]   Name:            sacre_coeur_67466492_5056065534.png
E20251230 15:03:29.258149    39 feature_extraction.cc:267] sacre_coeur_67466492_5056065534.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.275925    39 feature_extraction.cc:260] Processed file [45/74]
I20251230 15:03:29.275995    39 feature_extraction.cc:263]   Name:            sacre_coeur_68663909_1356782012.png
E20251230 15:03:29.276002    39 feature_extraction.cc:267] sacre_coeur_68663909_1356782012.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.291944    39 feature_extraction.cc:260] Processed file [46/74]
I20251230 15:03:29.292001    39 feature_extraction.cc:263]   Name:            sacre_coeur_68688218_4738908453.png
E20251230 15:03:29.292011    39 feature_extraction.cc:267] sacre_coeur_68688218_4738908453.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.308725    39 feature_extraction.cc:260] Processed file [47/74]
I20251230 15:03:29.308785    39 feature_extraction.cc:263]   Name:            sacre_coeur_69399539_4178098151.png
E20251230 15:03:29.308807    39 feature_extraction.cc:267] sacre_coeur_69399539_4178098151.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.327502    39 feature_extraction.cc:260] Processed file [48/74]
I20251230 15:03:29.327579    39 feature_extraction.cc:263]   Name:            sacre_coeur_70116109_2697195876.png
E20251230 15:03:29.327600    39 feature_extraction.cc:267] sacre_coeur_70116109_2697195876.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.347282    39 feature_extraction.cc:260] Processed file [49/74]
I20251230 15:03:29.347383    39 feature_extraction.cc:263]   Name:            sacre_coeur_70118605_5991576631.png
E20251230 15:03:29.347393    39 feature_extraction.cc:267] sacre_coeur_70118605_5991576631.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.365530    39 feature_extraction.cc:260] Processed file [50/74]
I20251230 15:03:29.365618    39 feature_extraction.cc:263]   Name:            sacre_coeur_70724808_2779990339.png
E20251230 15:03:29.365628    39 feature_extraction.cc:267] sacre_coeur_70724808_2779990339.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.386652    39 feature_extraction.cc:260] Processed file [51/74]
I20251230 15:03:29.386755    39 feature_extraction.cc:263]   Name:            sacre_coeur_70970334_5790897082.png
E20251230 15:03:29.386766    39 feature_extraction.cc:267] sacre_coeur_70970334_5790897082.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:03:29.409127    39 feature_extraction.cc:260] Processed file [52/74]
I20251230 15:03:29.409199    39 feature_extraction.cc:263]   Name:            sacre_coeur_71955478_140210696.png

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap exhaustive_matcher --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0003/colmap.db

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:03:47.684937    27 misc.cc:44]
==============================================================================
Feature matching & geometric verification
==============================================================================
I20251230 15:03:47.871745    28 feature_matching_utils.cc:78] Bind FeatureMatcherWorker to GPU device 0
I20251230 15:03:47.871964    28 sift.cc:1446] Creating SIFT GPU feature matcher
I20251230 15:03:47.952584    27 pairing.cc:180] Generating exhaustive image pairs...
I20251230 15:03:47.952663    27 pairing.cc:213] Processing block [1/1, 1/1]
I20251230 15:03:47.952682    27 feature_matching.cc:117] in 0.000s
I20251230 15:03:47.952692    27 timer.cc:90] Elapsed time: 0.004 [minutes]

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0003/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0003/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0003/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 3 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 2.0 --Mapper.tri_min_angle 1.5 --Mapper.filter_min_tri_angle 1.5 --Mapper.tri_ignore_two_view_tracks 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:04:03.252810     1 incremental_pipeline.cc:264] Loading database
I20251230 15:04:03.254388     1 database_cache.cc:67] Loading rigs...
I20251230 15:04:03.254460     1 database_cache.cc:77]  1 in 0.000s
I20251230 15:04:03.254475     1 database_cache.cc:85] Loading cameras...
I20251230 15:04:03.254488     1 database_cache.cc:103]  1 in 0.000s
I20251230 15:04:03.254492     1 database_cache.cc:111] Loading frames...
I20251230 15:04:03.254508     1 database_cache.cc:126]  1 in 0.000s
I20251230 15:04:03.254526     1 database_cache.cc:134] Loading matches...
I20251230 15:04:03.254537     1 database_cache.cc:139]  0 in 0.000s
I20251230 15:04:03.254554     1 database_cache.cc:155] Loading images...
I20251230 15:04:03.254581     1 database_cache.cc:239]  1 in 0.000s (connected 0)
I20251230 15:04:03.254598     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:04:03.254611     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:04:03.254822     1 timer.cc:90] Elapsed time: 0.000 [minutes]
W20251230 15:04:03.254849     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 15:04:03.254855     1 sfm.cc:278] failed to create sparse model

[retry] pt_sacrecoeur_trevi_tajmahal/cluster_0003: mapper attempt 2 (min_model_size=2, init_min_inliers=15, init_min_tri_angle=1.0, tri_min_angle=0.25, local_ba_min_tri_angle=0.25, tri_ignore_two_view_tracks=0)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0003/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0003/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0003/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 2 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 1.0 --Mapper.tri_min_angle 0.25 --Mapper.filter_min_tri_angle 0.25 --Mapper.tri_ignore_two_view_tracks 0

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:04:17.437808     1 incremental_pipeline.cc:264] Loading database
I20251230 15:04:17.494640     1 database_cache.cc:67] Loading rigs...
I20251230 15:04:17.524469     1 database_cache.cc:77]  1 in 0.030s
I20251230 15:04:17.524533     1 database_cache.cc:85] Loading cameras...
I20251230 15:04:17.554369     1 database_cache.cc:103]  1 in 0.030s
I20251230 15:04:17.554437     1 database_cache.cc:111] Loading frames...
I20251230 15:04:17.554472     1 database_cache.cc:126]  1 in 0.000s
I20251230 15:04:17.554476     1 database_cache.cc:134] Loading matches...
I20251230 15:04:17.566985     1 database_cache.cc:139]  0 in 0.013s
I20251230 15:04:17.567049     1 database_cache.cc:155] Loading images...
I20251230 15:04:17.567116     1 database_cache.cc:239]  1 in 0.000s (connected 0)
I20251230 15:04:17.567121     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:04:17.567134     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:04:17.567353     1 timer.cc:90] Elapsed time: 0.002 [minutes]
W20251230 15:04:17.567378     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 15:04:17.567385     1 sfm.cc:278] failed to create sparse model

[retry] pt_sacrecoeur_trevi_tajmahal/cluster_0003: mapper attempt 3 (min_model_size=2, init_min_inliers=8, init_min_tri_angle=0.5, tri_min_angle=0.05, local_ba_min_tri_angle=0.05, tri_ignore_two_view_tracks=0)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0003/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0003/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0003/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 8 --Mapper.min_model_size 2 --Mapper.init_min_num_inliers 8 --Mapper.init_min_tri_angle 0.5 --Mapper.tri_min_angle 0.05 --Mapper.filter_min_tri_angle 0.05 --Mapper.tri_ignore_two_view_tracks 0

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:04:32.189975     1 incremental_pipeline.cc:264] Loading database
I20251230 15:04:32.193334     1 database_cache.cc:67] Loading rigs...
I20251230 15:04:32.193408     1 database_cache.cc:77]  1 in 0.000s
I20251230 15:04:32.193418     1 database_cache.cc:85] Loading cameras...
I20251230 15:04:32.193428     1 database_cache.cc:103]  1 in 0.000s
I20251230 15:04:32.193434     1 database_cache.cc:111] Loading frames...
I20251230 15:04:32.193450     1 database_cache.cc:126]  1 in 0.000s
I20251230 15:04:32.193454     1 database_cache.cc:134] Loading matches...
I20251230 15:04:32.193461     1 database_cache.cc:139]  0 in 0.000s
I20251230 15:04:32.193464     1 database_cache.cc:155] Loading images...
I20251230 15:04:32.193483     1 database_cache.cc:239]  1 in 0.000s (connected 0)
I20251230 15:04:32.193487     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:04:32.193495     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:04:32.193663     1 timer.cc:90] Elapsed time: 0.000 [minutes]
W20251230 15:04:32.193693     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 15:04:32.193699     1 sfm.cc:278] failed to create sparse model

[retry] pt_sacrecoeur_trevi_tajmahal/cluster_0003: mapper attempt 4 (min_model_size=2, init_min_inliers=4, init_min_tri_angle=0.1, tri_min_angle=0.01, local_ba_min_tri_angle=0.01, tri_ignore_two_view_tracks=0)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0003/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0003/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_sacrecoeur_trevi_tajmahal_cluster_0003/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 4 --Mapper.min_model_size 2 --Mapper.init_min_num_inliers 4 --Mapper.init_min_tri_angle 0.1 --Mapper.tri_min_angle 0.01 --Mapper.filter_min_tri_angle 0.01 --Mapper.tri_ignore_two_view_tracks 0

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:04:45.875229     1 incremental_pipeline.cc:264] Loading database
I20251230 15:04:45.876276     1 database_cache.cc:67] Loading rigs...
I20251230 15:04:45.876348     1 database_cache.cc:77]  1 in 0.000s
I20251230 15:04:45.876356     1 database_cache.cc:85] Loading cameras...
I20251230 15:04:45.876365     1 database_cache.cc:103]  1 in 0.000s
I20251230 15:04:45.876382     1 database_cache.cc:111] Loading frames...
I20251230 15:04:45.876400     1 database_cache.cc:126]  1 in 0.000s
I20251230 15:04:45.876416     1 database_cache.cc:134] Loading matches...
I20251230 15:04:45.876427     1 database_cache.cc:139]  0 in 0.000s
I20251230 15:04:45.876441     1 database_cache.cc:155] Loading images...
I20251230 15:04:45.876466     1 database_cache.cc:239]  1 in 0.000s (connected 0)
I20251230 15:04:45.876482     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:04:45.876487     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:04:45.876688     1 timer.cc:90] Elapsed time: 0.000 [minutes]
W20251230 15:04:45.876710     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 15:04:45.876716     1 sfm.cc:278] failed to create sparse model

[fail] pt_sacrecoeur_trevi_tajmahal/cluster_0003: COLMAP mapper failed after 4 attempts
[cluster] 7/8: pt_stpeters_stpauls/cluster_0001
[run] pt_stpeters_stpauls/cluster_0001: images=101 matcher=colmap
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap feature_extractor --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0001/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0001/images --ImageReader.camera_model SIMPLE_RADIAL --ImageReader.single_camera 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:05:20.651937    27 misc.cc:44]
==============================================================================
Feature extraction
==============================================================================
I20251230 15:05:20.653440    38 sift.cc:720] Creating SIFT GPU feature extractor
I20251230 15:05:22.808178    39 feature_extraction.cc:260] Processed file [1/101]
I20251230 15:05:22.808259    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_22051479_11389229645.png
I20251230 15:05:22.808270    39 feature_extraction.cc:272]   Dimensions:      489 x 489
I20251230 15:05:22.808274    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 15:05:22.808279    39 feature_extraction.cc:278]   Focal Length:    586.80px
I20251230 15:05:22.808287    39 feature_extraction.cc:282]   Features:        3613 (SIFT)
I20251230 15:05:22.832305    39 feature_extraction.cc:260] Processed file [2/101]
I20251230 15:05:22.832362    39 feature_extraction.cc:263]   Name:            st_peters_square_01086691_5427945640.png
E20251230 15:05:22.832367    39 feature_extraction.cc:267] st_peters_square_01086691_5427945640.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.832372    39 feature_extraction.cc:260] Processed file [3/101]
I20251230 15:05:22.832376    39 feature_extraction.cc:263]   Name:            st_peters_square_01113045_2151200754.png
E20251230 15:05:22.832377    39 feature_extraction.cc:267] st_peters_square_01113045_2151200754.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.832381    39 feature_extraction.cc:260] Processed file [4/101]
I20251230 15:05:22.832384    39 feature_extraction.cc:263]   Name:            st_peters_square_03091803_3301752366.png
E20251230 15:05:22.832387    39 feature_extraction.cc:267] st_peters_square_03091803_3301752366.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.832497    39 feature_extraction.cc:260] Processed file [5/101]
I20251230 15:05:22.832530    39 feature_extraction.cc:263]   Name:            st_peters_square_03746789_4463922325.png
E20251230 15:05:22.832535    39 feature_extraction.cc:267] st_peters_square_03746789_4463922325.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.832648    39 feature_extraction.cc:260] Processed file [6/101]
I20251230 15:05:22.832667    39 feature_extraction.cc:263]   Name:            st_peters_square_03988695_8001663418.png
E20251230 15:05:22.832674    39 feature_extraction.cc:267] st_peters_square_03988695_8001663418.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.832677    39 feature_extraction.cc:260] Processed file [7/101]
I20251230 15:05:22.832680    39 feature_extraction.cc:263]   Name:            st_peters_square_04610226_4103646673.png
E20251230 15:05:22.832683    39 feature_extraction.cc:267] st_peters_square_04610226_4103646673.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.832741    39 feature_extraction.cc:260] Processed file [8/101]
I20251230 15:05:22.832760    39 feature_extraction.cc:263]   Name:            st_peters_square_04687924_2163037290.png
E20251230 15:05:22.832763    39 feature_extraction.cc:267] st_peters_square_04687924_2163037290.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.832767    39 feature_extraction.cc:260] Processed file [9/101]
I20251230 15:05:22.832770    39 feature_extraction.cc:263]   Name:            st_peters_square_05036686_9559490324.png
E20251230 15:05:22.832772    39 feature_extraction.cc:267] st_peters_square_05036686_9559490324.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.832942    39 feature_extraction.cc:260] Processed file [10/101]
I20251230 15:05:22.832973    39 feature_extraction.cc:263]   Name:            st_peters_square_05894880_3961210476.png
E20251230 15:05:22.832978    39 feature_extraction.cc:267] st_peters_square_05894880_3961210476.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.833001    39 feature_extraction.cc:260] Processed file [11/101]
I20251230 15:05:22.833009    39 feature_extraction.cc:263]   Name:            st_peters_square_07459783_2116496273.png
E20251230 15:05:22.833019    39 feature_extraction.cc:267] st_peters_square_07459783_2116496273.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.833022    39 feature_extraction.cc:260] Processed file [12/101]
I20251230 15:05:22.833025    39 feature_extraction.cc:263]   Name:            st_peters_square_09150846_12806538585.png
E20251230 15:05:22.833029    39 feature_extraction.cc:267] st_peters_square_09150846_12806538585.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.833031    39 feature_extraction.cc:260] Processed file [13/101]
I20251230 15:05:22.833034    39 feature_extraction.cc:263]   Name:            st_peters_square_11170243_108218811.png
E20251230 15:05:22.833036    39 feature_extraction.cc:267] st_peters_square_11170243_108218811.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.833158    39 feature_extraction.cc:260] Processed file [14/101]
I20251230 15:05:22.833194    39 feature_extraction.cc:263]   Name:            st_peters_square_12334689_522974921.png
E20251230 15:05:22.833199    39 feature_extraction.cc:267] st_peters_square_12334689_522974921.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.833293    39 feature_extraction.cc:260] Processed file [15/101]
I20251230 15:05:22.833317    39 feature_extraction.cc:263]   Name:            st_peters_square_14434211_3241927710.png
E20251230 15:05:22.833323    39 feature_extraction.cc:267] st_peters_square_14434211_3241927710.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.833328    39 feature_extraction.cc:260] Processed file [16/101]
I20251230 15:05:22.833330    39 feature_extraction.cc:263]   Name:            st_peters_square_16459160_169609859.png
E20251230 15:05:22.833333    39 feature_extraction.cc:267] st_peters_square_16459160_169609859.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.846498    39 feature_extraction.cc:260] Processed file [17/101]
I20251230 15:05:22.846553    39 feature_extraction.cc:263]   Name:            st_peters_square_16560660_87393276.png
E20251230 15:05:22.846560    39 feature_extraction.cc:267] st_peters_square_16560660_87393276.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.860689    39 feature_extraction.cc:260] Processed file [18/101]
I20251230 15:05:22.860738    39 feature_extraction.cc:263]   Name:            st_peters_square_17992917_296706864.png
E20251230 15:05:22.860744    39 feature_extraction.cc:267] st_peters_square_17992917_296706864.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.875175    39 feature_extraction.cc:260] Processed file [19/101]
I20251230 15:05:22.875226    39 feature_extraction.cc:263]   Name:            st_peters_square_18412179_6172244512.png
E20251230 15:05:22.875232    39 feature_extraction.cc:267] st_peters_square_18412179_6172244512.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.885010    39 feature_extraction.cc:260] Processed file [20/101]
I20251230 15:05:22.885052    39 feature_extraction.cc:263]   Name:            st_peters_square_18948310_1391071648.png
E20251230 15:05:22.885058    39 feature_extraction.cc:267] st_peters_square_18948310_1391071648.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.898172    39 feature_extraction.cc:260] Processed file [21/101]
I20251230 15:05:22.898224    39 feature_extraction.cc:263]   Name:            st_peters_square_20328156_5873219320.png
E20251230 15:05:22.898231    39 feature_extraction.cc:267] st_peters_square_20328156_5873219320.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.911701    39 feature_extraction.cc:260] Processed file [22/101]
I20251230 15:05:22.911754    39 feature_extraction.cc:263]   Name:            st_peters_square_21905075_5452965061.png
E20251230 15:05:22.911761    39 feature_extraction.cc:267] st_peters_square_21905075_5452965061.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.924131    39 feature_extraction.cc:260] Processed file [23/101]
I20251230 15:05:22.924190    39 feature_extraction.cc:263]   Name:            st_peters_square_22421524_4050930227.png
E20251230 15:05:22.924197    39 feature_extraction.cc:267] st_peters_square_22421524_4050930227.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.935289    39 feature_extraction.cc:260] Processed file [24/101]
I20251230 15:05:22.935331    39 feature_extraction.cc:263]   Name:            st_peters_square_22746486_9560856076.png
E20251230 15:05:22.935336    39 feature_extraction.cc:267] st_peters_square_22746486_9560856076.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.946229    39 feature_extraction.cc:260] Processed file [25/101]
I20251230 15:05:22.946287    39 feature_extraction.cc:263]   Name:            st_peters_square_24059795_9603235434.png
E20251230 15:05:22.946295    39 feature_extraction.cc:267] st_peters_square_24059795_9603235434.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.951720    39 feature_extraction.cc:260] Processed file [26/101]
I20251230 15:05:22.951766    39 feature_extraction.cc:263]   Name:            st_peters_square_24636762_4089050891.png
E20251230 15:05:22.951773    39 feature_extraction.cc:267] st_peters_square_24636762_4089050891.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.955834    39 feature_extraction.cc:260] Processed file [27/101]
I20251230 15:05:22.955897    39 feature_extraction.cc:263]   Name:            st_peters_square_24719115_774461939.png
E20251230 15:05:22.955904    39 feature_extraction.cc:267] st_peters_square_24719115_774461939.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.970616    39 feature_extraction.cc:260] Processed file [28/101]
I20251230 15:05:22.970678    39 feature_extraction.cc:263]   Name:            st_peters_square_27722146_2540992403.png
E20251230 15:05:22.970685    39 feature_extraction.cc:267] st_peters_square_27722146_2540992403.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.980369    39 feature_extraction.cc:260] Processed file [29/101]
I20251230 15:05:22.980425    39 feature_extraction.cc:263]   Name:            st_peters_square_27821246_220471245.png
E20251230 15:05:22.980433    39 feature_extraction.cc:267] st_peters_square_27821246_220471245.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:22.993991    39 feature_extraction.cc:260] Processed file [30/101]
I20251230 15:05:22.994046    39 feature_extraction.cc:263]   Name:            st_peters_square_29679303_181377461.png
E20251230 15:05:22.994055    39 feature_extraction.cc:267] st_peters_square_29679303_181377461.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.008637    39 feature_extraction.cc:260] Processed file [31/101]
I20251230 15:05:23.008692    39 feature_extraction.cc:263]   Name:            st_peters_square_32164473_4104406816.png
E20251230 15:05:23.008698    39 feature_extraction.cc:267] st_peters_square_32164473_4104406816.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.021462    39 feature_extraction.cc:260] Processed file [32/101]
I20251230 15:05:23.021519    39 feature_extraction.cc:263]   Name:            st_peters_square_33011793_12700964863.png
E20251230 15:05:23.021526    39 feature_extraction.cc:267] st_peters_square_33011793_12700964863.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.034675    39 feature_extraction.cc:260] Processed file [33/101]
I20251230 15:05:23.034725    39 feature_extraction.cc:263]   Name:            st_peters_square_33563670_5242619236.png
E20251230 15:05:23.034750    39 feature_extraction.cc:267] st_peters_square_33563670_5242619236.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.049434    39 feature_extraction.cc:260] Processed file [34/101]
I20251230 15:05:23.078840    39 feature_extraction.cc:263]   Name:            st_peters_square_35727766_2927321004.png
E20251230 15:05:23.078848    39 feature_extraction.cc:267] st_peters_square_35727766_2927321004.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.094185    39 feature_extraction.cc:260] Processed file [35/101]
I20251230 15:05:23.094236    39 feature_extraction.cc:263]   Name:            st_peters_square_36268301_7354161880.png
E20251230 15:05:23.094242    39 feature_extraction.cc:267] st_peters_square_36268301_7354161880.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.108506    39 feature_extraction.cc:260] Processed file [36/101]
I20251230 15:05:23.108548    39 feature_extraction.cc:263]   Name:            st_peters_square_37466637_151112376.png
E20251230 15:05:23.108554    39 feature_extraction.cc:267] st_peters_square_37466637_151112376.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.121721    39 feature_extraction.cc:260] Processed file [37/101]
I20251230 15:05:23.121765    39 feature_extraction.cc:263]   Name:            st_peters_square_40696807_2666761892.png
E20251230 15:05:23.121773    39 feature_extraction.cc:267] st_peters_square_40696807_2666761892.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.131207    39 feature_extraction.cc:260] Processed file [38/101]
I20251230 15:05:23.131258    39 feature_extraction.cc:263]   Name:            st_peters_square_41659819_2070196997.png
E20251230 15:05:23.131264    39 feature_extraction.cc:267] st_peters_square_41659819_2070196997.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.147488    39 feature_extraction.cc:260] Processed file [39/101]
I20251230 15:05:23.147532    39 feature_extraction.cc:263]   Name:            st_peters_square_43335638_88784147.png
E20251230 15:05:23.147538    39 feature_extraction.cc:267] st_peters_square_43335638_88784147.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.162144    39 feature_extraction.cc:260] Processed file [40/101]
I20251230 15:05:23.162204    39 feature_extraction.cc:263]   Name:            st_peters_square_44390759_5115213112.png
E20251230 15:05:23.162209    39 feature_extraction.cc:267] st_peters_square_44390759_5115213112.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.176770    39 feature_extraction.cc:260] Processed file [41/101]
I20251230 15:05:23.176821    39 feature_extraction.cc:263]   Name:            st_peters_square_44455970_5746646894.png
E20251230 15:05:23.176829    39 feature_extraction.cc:267] st_peters_square_44455970_5746646894.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.194173    39 feature_extraction.cc:260] Processed file [42/101]
I20251230 15:05:23.194242    39 feature_extraction.cc:263]   Name:            st_peters_square_44478569_2733152198.png
E20251230 15:05:23.194248    39 feature_extraction.cc:267] st_peters_square_44478569_2733152198.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.213096    39 feature_extraction.cc:260] Processed file [43/101]
I20251230 15:05:23.213160    39 feature_extraction.cc:263]   Name:            st_peters_square_45146398_300508266.png
E20251230 15:05:23.213169    39 feature_extraction.cc:267] st_peters_square_45146398_300508266.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.230020    39 feature_extraction.cc:260] Processed file [44/101]
I20251230 15:05:23.230103    39 feature_extraction.cc:263]   Name:            st_peters_square_45336170_8518744916.png
E20251230 15:05:23.230120    39 feature_extraction.cc:267] st_peters_square_45336170_8518744916.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.245440    39 feature_extraction.cc:260] Processed file [45/101]
I20251230 15:05:23.245496    39 feature_extraction.cc:263]   Name:            st_peters_square_46268845_5210431.png
E20251230 15:05:23.245504    39 feature_extraction.cc:267] st_peters_square_46268845_5210431.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.262212    39 feature_extraction.cc:260] Processed file [46/101]
I20251230 15:05:23.262270    39 feature_extraction.cc:263]   Name:            st_peters_square_46663883_6534848061.png
E20251230 15:05:23.262279    39 feature_extraction.cc:267] st_peters_square_46663883_6534848061.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.277499    39 feature_extraction.cc:260] Processed file [47/101]
I20251230 15:05:23.277556    39 feature_extraction.cc:263]   Name:            st_peters_square_47361588_602059416.png
E20251230 15:05:23.277565    39 feature_extraction.cc:267] st_peters_square_47361588_602059416.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.294466    39 feature_extraction.cc:260] Processed file [48/101]
I20251230 15:05:23.294519    39 feature_extraction.cc:263]   Name:            st_peters_square_48141965_9536256202.png
E20251230 15:05:23.294529    39 feature_extraction.cc:267] st_peters_square_48141965_9536256202.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.308604    39 feature_extraction.cc:260] Processed file [49/101]
I20251230 15:05:23.308665    39 feature_extraction.cc:263]   Name:            st_peters_square_48496249_4257721183.png
E20251230 15:05:23.308696    39 feature_extraction.cc:267] st_peters_square_48496249_4257721183.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:05:23.323742    39 feature_extraction.cc:260] Processed file [50/101]
I20251230 15:05:23.323797    39 feature_extraction.cc:263]   Name:            st_peters_square_50829067_6827571714.png
E20251230 15:05:23.323807    39 feature_extraction.cc:267] st_peters_square_50829067_6827571714.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap exhaustive_matcher --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0001/colmap.db

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:05:39.752753    27 misc.cc:44]
==============================================================================
Feature matching & geometric verification
==============================================================================
I20251230 15:05:39.856480    28 feature_matching_utils.cc:78] Bind FeatureMatcherWorker to GPU device 0
I20251230 15:05:39.864503    28 sift.cc:1446] Creating SIFT GPU feature matcher
I20251230 15:05:39.900810    27 pairing.cc:180] Generating exhaustive image pairs...
I20251230 15:05:39.900878    27 pairing.cc:213] Processing block [1/1, 1/1]
I20251230 15:05:39.900892    27 feature_matching.cc:117] in 0.000s
I20251230 15:05:39.900897    27 timer.cc:90] Elapsed time: 0.002 [minutes]

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0001/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0001/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0001/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 3 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 2.0 --Mapper.tri_min_angle 1.5 --Mapper.filter_min_tri_angle 1.5 --Mapper.tri_ignore_two_view_tracks 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:05:48.857165     1 incremental_pipeline.cc:264] Loading database
I20251230 15:05:48.871476     1 database_cache.cc:67] Loading rigs...
I20251230 15:05:48.935966     1 database_cache.cc:77]  1 in 0.065s
I20251230 15:05:48.936021     1 database_cache.cc:85] Loading cameras...
I20251230 15:05:48.936041     1 database_cache.cc:103]  1 in 0.000s
I20251230 15:05:48.936045     1 database_cache.cc:111] Loading frames...
I20251230 15:05:48.936064     1 database_cache.cc:126]  1 in 0.000s
I20251230 15:05:48.936069     1 database_cache.cc:134] Loading matches...
I20251230 15:05:48.936075     1 database_cache.cc:139]  0 in 0.000s
I20251230 15:05:48.936079     1 database_cache.cc:155] Loading images...
I20251230 15:05:48.936138     1 database_cache.cc:239]  1 in 0.000s (connected 0)
I20251230 15:05:48.936156     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:05:48.936168     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:05:48.936417     1 timer.cc:90] Elapsed time: 0.001 [minutes]
W20251230 15:05:48.936440     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 15:05:48.936455     1 sfm.cc:278] failed to create sparse model

[retry] pt_stpeters_stpauls/cluster_0001: mapper attempt 2 (min_model_size=2, init_min_inliers=15, init_min_tri_angle=1.0, tri_min_angle=0.25, local_ba_min_tri_angle=0.25, tri_ignore_two_view_tracks=0)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0001/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0001/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0001/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 2 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 1.0 --Mapper.tri_min_angle 0.25 --Mapper.filter_min_tri_angle 0.25 --Mapper.tri_ignore_two_view_tracks 0

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:05:58.086889     1 incremental_pipeline.cc:264] Loading database
I20251230 15:05:58.298532     1 database_cache.cc:67] Loading rigs...
I20251230 15:05:58.940236     1 database_cache.cc:77]  1 in 0.642s
I20251230 15:05:58.940300     1 database_cache.cc:85] Loading cameras...
I20251230 15:05:58.940322     1 database_cache.cc:103]  1 in 0.000s
I20251230 15:05:58.940326     1 database_cache.cc:111] Loading frames...
I20251230 15:05:58.940346     1 database_cache.cc:126]  1 in 0.000s
I20251230 15:05:58.940349     1 database_cache.cc:134] Loading matches...
I20251230 15:05:58.940356     1 database_cache.cc:139]  0 in 0.000s
I20251230 15:05:58.940359     1 database_cache.cc:155] Loading images...
I20251230 15:05:58.940397     1 database_cache.cc:239]  1 in 0.000s (connected 0)
I20251230 15:05:58.940414     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:05:58.940426     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:05:58.940651     1 timer.cc:90] Elapsed time: 0.011 [minutes]
W20251230 15:05:58.940666     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 15:05:58.940670     1 sfm.cc:278] failed to create sparse model

[retry] pt_stpeters_stpauls/cluster_0001: mapper attempt 3 (min_model_size=2, init_min_inliers=8, init_min_tri_angle=0.5, tri_min_angle=0.05, local_ba_min_tri_angle=0.05, tri_ignore_two_view_tracks=0)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0001/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0001/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0001/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 8 --Mapper.min_model_size 2 --Mapper.init_min_num_inliers 8 --Mapper.init_min_tri_angle 0.5 --Mapper.tri_min_angle 0.05 --Mapper.filter_min_tri_angle 0.05 --Mapper.tri_ignore_two_view_tracks 0

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:06:14.291422     1 incremental_pipeline.cc:264] Loading database
I20251230 15:06:14.292675     1 database_cache.cc:67] Loading rigs...
I20251230 15:06:14.292740     1 database_cache.cc:77]  1 in 0.000s
I20251230 15:06:14.292763     1 database_cache.cc:85] Loading cameras...
I20251230 15:06:14.292773     1 database_cache.cc:103]  1 in 0.000s
I20251230 15:06:14.292788     1 database_cache.cc:111] Loading frames...
I20251230 15:06:14.292805     1 database_cache.cc:126]  1 in 0.000s
I20251230 15:06:14.292820     1 database_cache.cc:134] Loading matches...
I20251230 15:06:14.292830     1 database_cache.cc:139]  0 in 0.000s
I20251230 15:06:14.292845     1 database_cache.cc:155] Loading images...
I20251230 15:06:14.292867     1 database_cache.cc:239]  1 in 0.000s (connected 0)
I20251230 15:06:14.292905     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:06:14.292912     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:06:14.293100     1 timer.cc:90] Elapsed time: 0.000 [minutes]
W20251230 15:06:14.293123     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 15:06:14.293128     1 sfm.cc:278] failed to create sparse model

[retry] pt_stpeters_stpauls/cluster_0001: mapper attempt 4 (min_model_size=2, init_min_inliers=4, init_min_tri_angle=0.1, tri_min_angle=0.01, local_ba_min_tri_angle=0.01, tri_ignore_two_view_tracks=0)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0001/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0001/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0001/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 4 --Mapper.min_model_size 2 --Mapper.init_min_num_inliers 4 --Mapper.init_min_tri_angle 0.1 --Mapper.tri_min_angle 0.01 --Mapper.filter_min_tri_angle 0.01 --Mapper.tri_ignore_two_view_tracks 0

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:06:29.181628     1 incremental_pipeline.cc:264] Loading database
I20251230 15:06:29.663690     1 database_cache.cc:67] Loading rigs...
I20251230 15:06:30.026010     1 database_cache.cc:77]  1 in 0.362s
I20251230 15:06:30.026120     1 database_cache.cc:85] Loading cameras...
I20251230 15:06:30.026172     1 database_cache.cc:103]  1 in 0.000s
I20251230 15:06:30.026177     1 database_cache.cc:111] Loading frames...
I20251230 15:06:30.026228     1 database_cache.cc:126]  1 in 0.000s
I20251230 15:06:30.026232     1 database_cache.cc:134] Loading matches...
I20251230 15:06:30.026239     1 database_cache.cc:139]  0 in 0.000s
I20251230 15:06:30.026244     1 database_cache.cc:155] Loading images...
I20251230 15:06:30.026288     1 database_cache.cc:239]  1 in 0.000s (connected 0)
I20251230 15:06:30.026310     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:06:30.026322     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:06:30.026618     1 timer.cc:90] Elapsed time: 0.014 [minutes]
W20251230 15:06:30.026649     1 incremental_pipeline.cc:288] No images with matches found in the database
E20251230 15:06:30.026655     1 sfm.cc:278] failed to create sparse model

[fail] pt_stpeters_stpauls/cluster_0001: COLMAP mapper failed after 4 attempts
[cluster] 8/8: pt_stpeters_stpauls/cluster_0002
[run] pt_stpeters_stpauls/cluster_0002: images=99 matcher=colmap
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap feature_extractor --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0002/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0002/images --ImageReader.camera_model SIMPLE_RADIAL --ImageReader.single_camera 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:07:01.694137    27 misc.cc:44]
==============================================================================
Feature extraction
==============================================================================
I20251230 15:07:01.695250    38 sift.cc:720] Creating SIFT GPU feature extractor
I20251230 15:07:03.565017    39 feature_extraction.cc:260] Processed file [1/99]
I20251230 15:07:03.565089    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_00162897_2573777698.png
I20251230 15:07:03.565095    39 feature_extraction.cc:272]   Dimensions:      1050 x 778
I20251230 15:07:03.565099    39 feature_extraction.cc:275]   Camera:          #1 - SIMPLE_RADIAL
I20251230 15:07:03.565102    39 feature_extraction.cc:278]   Focal Length:    1260.00px
I20251230 15:07:03.602618    39 feature_extraction.cc:282]   Features:        7825 (SIFT)
I20251230 15:07:03.605420    39 feature_extraction.cc:260] Processed file [2/99]
I20251230 15:07:03.605477    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_00593112_5162872967.png
E20251230 15:07:03.605484    39 feature_extraction.cc:267] st_pauls_cathedral_00593112_5162872967.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.605501    39 feature_extraction.cc:260] Processed file [3/99]
I20251230 15:07:03.605507    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_01024897_4276850874.png
E20251230 15:07:03.605510    39 feature_extraction.cc:267] st_pauls_cathedral_01024897_4276850874.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.605517    39 feature_extraction.cc:260] Processed file [4/99]
I20251230 15:07:03.605520    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_01207461_5308976270.png
E20251230 15:07:03.605522    39 feature_extraction.cc:267] st_pauls_cathedral_01207461_5308976270.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.605535    39 feature_extraction.cc:260] Processed file [5/99]
I20251230 15:07:03.605537    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_01405760_428260779.png
E20251230 15:07:03.605540    39 feature_extraction.cc:267] st_pauls_cathedral_01405760_428260779.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.605676    39 feature_extraction.cc:260] Processed file [6/99]
I20251230 15:07:03.605718    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_08811062_7652433566.png
E20251230 15:07:03.605726    39 feature_extraction.cc:267] st_pauls_cathedral_08811062_7652433566.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.605731    39 feature_extraction.cc:260] Processed file [7/99]
I20251230 15:07:03.605736    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_02796054_3846089993.png
E20251230 15:07:03.605739    39 feature_extraction.cc:267] st_pauls_cathedral_02796054_3846089993.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.605770    39 feature_extraction.cc:260] Processed file [8/99]
I20251230 15:07:03.605800    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_02139247_2294669227.png
E20251230 15:07:03.605806    39 feature_extraction.cc:267] st_pauls_cathedral_02139247_2294669227.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.605822    39 feature_extraction.cc:260] Processed file [9/99]
I20251230 15:07:03.605840    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_04223687_109190093.png
E20251230 15:07:03.605847    39 feature_extraction.cc:267] st_pauls_cathedral_04223687_109190093.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.605867    39 feature_extraction.cc:260] Processed file [10/99]
I20251230 15:07:03.605875    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_05641764_12250203953.png
E20251230 15:07:03.605880    39 feature_extraction.cc:267] st_pauls_cathedral_05641764_12250203953.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.605885    39 feature_extraction.cc:260] Processed file [11/99]
I20251230 15:07:03.605903    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_06850079_5924336712.png
E20251230 15:07:03.605909    39 feature_extraction.cc:267] st_pauls_cathedral_06850079_5924336712.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.605914    39 feature_extraction.cc:260] Processed file [12/99]
I20251230 15:07:03.605919    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_07127770_6944612870.png
E20251230 15:07:03.605924    39 feature_extraction.cc:267] st_pauls_cathedral_07127770_6944612870.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.605976    39 feature_extraction.cc:260] Processed file [13/99]
I20251230 15:07:03.606009    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_07173502_9664669062.png
E20251230 15:07:03.606015    39 feature_extraction.cc:267] st_pauls_cathedral_07173502_9664669062.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.606019    39 feature_extraction.cc:260] Processed file [14/99]
I20251230 15:07:03.606022    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_08212369_4763831145.png
E20251230 15:07:03.606025    39 feature_extraction.cc:267] st_pauls_cathedral_08212369_4763831145.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.606164    39 feature_extraction.cc:260] Processed file [15/99]
I20251230 15:07:03.606195    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_15340635_6286567877.png
E20251230 15:07:03.606201    39 feature_extraction.cc:267] st_pauls_cathedral_15340635_6286567877.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.606206    39 feature_extraction.cc:260] Processed file [16/99]
I20251230 15:07:03.606210    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_04913236_119772663.png
E20251230 15:07:03.606215    39 feature_extraction.cc:267] st_pauls_cathedral_04913236_119772663.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.619216    39 feature_extraction.cc:260] Processed file [17/99]
I20251230 15:07:03.619278    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_15717585_5849870034.png
E20251230 15:07:03.619284    39 feature_extraction.cc:267] st_pauls_cathedral_15717585_5849870034.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.635632    39 feature_extraction.cc:260] Processed file [18/99]
I20251230 15:07:03.635676    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_15866879_138904614.png
E20251230 15:07:03.635682    39 feature_extraction.cc:267] st_pauls_cathedral_15866879_138904614.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.650864    39 feature_extraction.cc:260] Processed file [19/99]
I20251230 15:07:03.650923    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_16273036_6590036823.png
E20251230 15:07:03.650928    39 feature_extraction.cc:267] st_pauls_cathedral_16273036_6590036823.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.672605    39 feature_extraction.cc:260] Processed file [20/99]
I20251230 15:07:03.672685    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_16894231_3531570752.png
E20251230 15:07:03.672694    39 feature_extraction.cc:267] st_pauls_cathedral_16894231_3531570752.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.689625    39 feature_extraction.cc:260] Processed file [21/99]
I20251230 15:07:03.689708    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_16950686_8459946808.png
E20251230 15:07:03.689719    39 feature_extraction.cc:267] st_pauls_cathedral_16950686_8459946808.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.708806    39 feature_extraction.cc:260] Processed file [22/99]
I20251230 15:07:03.708863    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_18009039_2159636076.png
E20251230 15:07:03.708877    39 feature_extraction.cc:267] st_pauls_cathedral_18009039_2159636076.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.887598    39 feature_extraction.cc:260] Processed file [23/99]
I20251230 15:07:03.887665    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_18206585_1326228024.png
E20251230 15:07:03.887671    39 feature_extraction.cc:267] st_pauls_cathedral_18206585_1326228024.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.904157    39 feature_extraction.cc:260] Processed file [24/99]
I20251230 15:07:03.904228    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_19156543_414105990.png
E20251230 15:07:03.904237    39 feature_extraction.cc:267] st_pauls_cathedral_19156543_414105990.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.914505    39 feature_extraction.cc:260] Processed file [25/99]
I20251230 15:07:03.914600    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_19750027_343386986.png
E20251230 15:07:03.914609    39 feature_extraction.cc:267] st_pauls_cathedral_19750027_343386986.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.922259    39 feature_extraction.cc:260] Processed file [26/99]
I20251230 15:07:03.922317    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_20239254_119772598.png
E20251230 15:07:03.922324    39 feature_extraction.cc:267] st_pauls_cathedral_20239254_119772598.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.937131    39 feature_extraction.cc:260] Processed file [27/99]
I20251230 15:07:03.937188    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_22597499_4761259569.png
E20251230 15:07:03.937196    39 feature_extraction.cc:267] st_pauls_cathedral_22597499_4761259569.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.941391    39 feature_extraction.cc:260] Processed file [28/99]
I20251230 15:07:03.941445    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_23624636_5162872877.png
E20251230 15:07:03.941452    39 feature_extraction.cc:267] st_pauls_cathedral_23624636_5162872877.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.957057    39 feature_extraction.cc:260] Processed file [29/99]
I20251230 15:07:03.957118    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_28850329_4038914991.png
E20251230 15:07:03.957124    39 feature_extraction.cc:267] st_pauls_cathedral_28850329_4038914991.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.971686    39 feature_extraction.cc:260] Processed file [30/99]
I20251230 15:07:03.971756    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_29137875_1898785145.png
E20251230 15:07:03.971765    39 feature_extraction.cc:267] st_pauls_cathedral_29137875_1898785145.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.985145    39 feature_extraction.cc:260] Processed file [31/99]
I20251230 15:07:03.985212    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_29687506_6744340327.png
E20251230 15:07:03.985219    39 feature_extraction.cc:267] st_pauls_cathedral_29687506_6744340327.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:03.995486    39 feature_extraction.cc:260] Processed file [32/99]
I20251230 15:07:03.995544    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_31055607_5795560563.png
E20251230 15:07:03.995553    39 feature_extraction.cc:267] st_pauls_cathedral_31055607_5795560563.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.013577    39 feature_extraction.cc:260] Processed file [33/99]
I20251230 15:07:04.013690    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_34381859_7319928252.png
E20251230 15:07:04.013700    39 feature_extraction.cc:267] st_pauls_cathedral_34381859_7319928252.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.029601    39 feature_extraction.cc:260] Processed file [34/99]
I20251230 15:07:04.029668    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_35236682_3866876026.png
E20251230 15:07:04.029677    39 feature_extraction.cc:267] st_pauls_cathedral_35236682_3866876026.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.049614    39 feature_extraction.cc:260] Processed file [35/99]
I20251230 15:07:04.049670    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_36924691_6406659277.png
E20251230 15:07:04.049679    39 feature_extraction.cc:267] st_pauls_cathedral_36924691_6406659277.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.074846    39 feature_extraction.cc:260] Processed file [36/99]
I20251230 15:07:04.074901    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_37031536_5918950469.png
E20251230 15:07:04.074909    39 feature_extraction.cc:267] st_pauls_cathedral_37031536_5918950469.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.097757    39 feature_extraction.cc:260] Processed file [37/99]
I20251230 15:07:04.097857    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_37175263_9450449849.png
E20251230 15:07:04.097867    39 feature_extraction.cc:267] st_pauls_cathedral_37175263_9450449849.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.121680    39 feature_extraction.cc:260] Processed file [38/99]
I20251230 15:07:04.121731    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_37347628_10902811376.png
E20251230 15:07:04.121742    39 feature_extraction.cc:267] st_pauls_cathedral_37347628_10902811376.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.143568    39 feature_extraction.cc:260] Processed file [39/99]
I20251230 15:07:04.143631    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_37670824_2154551459.png
E20251230 15:07:04.143643    39 feature_extraction.cc:267] st_pauls_cathedral_37670824_2154551459.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.161942    39 feature_extraction.cc:260] Processed file [40/99]
I20251230 15:07:04.162012    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_37863559_4180603861.png
E20251230 15:07:04.162022    39 feature_extraction.cc:267] st_pauls_cathedral_37863559_4180603861.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.176671    39 feature_extraction.cc:260] Processed file [41/99]
I20251230 15:07:04.176756    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_37891131_11165782483.png
E20251230 15:07:04.176769    39 feature_extraction.cc:267] st_pauls_cathedral_37891131_11165782483.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.196841    39 feature_extraction.cc:260] Processed file [42/99]
I20251230 15:07:04.196919    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_43920096_10906605833.png
E20251230 15:07:04.196931    39 feature_extraction.cc:267] st_pauls_cathedral_43920096_10906605833.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.214385    39 feature_extraction.cc:260] Processed file [43/99]
I20251230 15:07:04.214457    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_44160609_6465554263.png
E20251230 15:07:04.214468    39 feature_extraction.cc:267] st_pauls_cathedral_44160609_6465554263.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.244031    39 feature_extraction.cc:260] Processed file [44/99]
I20251230 15:07:04.244112    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_45685596_2848901240.png
E20251230 15:07:04.244127    39 feature_extraction.cc:267] st_pauls_cathedral_45685596_2848901240.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.277266    39 feature_extraction.cc:260] Processed file [45/99]
I20251230 15:07:04.277351    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_47854767_3623008711.png
E20251230 15:07:04.277364    39 feature_extraction.cc:267] st_pauls_cathedral_47854767_3623008711.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.284329    39 feature_extraction.cc:260] Processed file [46/99]
I20251230 15:07:04.284426    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_49523263_2763776233.png
E20251230 15:07:04.284441    39 feature_extraction.cc:267] st_pauls_cathedral_49523263_2763776233.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.310827    39 feature_extraction.cc:260] Processed file [47/99]
I20251230 15:07:04.310913    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_50777283_4936535855.png
E20251230 15:07:04.310922    39 feature_extraction.cc:267] st_pauls_cathedral_50777283_4936535855.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.331671    39 feature_extraction.cc:260] Processed file [48/99]
I20251230 15:07:04.331768    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_51592699_1165340842.png
E20251230 15:07:04.331785    39 feature_extraction.cc:267] st_pauls_cathedral_51592699_1165340842.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.355377    39 feature_extraction.cc:260] Processed file [49/99]
I20251230 15:07:04.355463    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_57396867_1162831381.png
E20251230 15:07:04.355474    39 feature_extraction.cc:267] st_pauls_cathedral_57396867_1162831381.png CAMERA_SINGLE_DIM_ERROR: Single camera specified, but images have different dimensions.
I20251230 15:07:04.379135    39 feature_extraction.cc:260] Processed file [50/99]
I20251230 15:07:04.379228    39 feature_extraction.cc:263]   Name:            st_pauls_cathedral_59351891_5209994388.png

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap exhaustive_matcher --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0002/colmap.db

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:07:22.228760    27 misc.cc:44]
==============================================================================
Feature matching & geometric verification
==============================================================================
I20251230 15:07:22.472323    28 feature_matching_utils.cc:78] Bind FeatureMatcherWorker to GPU device 0
I20251230 15:07:22.472651    28 sift.cc:1446] Creating SIFT GPU feature matcher
I20251230 15:07:22.485158    27 pairing.cc:180] Generating exhaustive image pairs...
I20251230 15:07:22.485217    27 pairing.cc:213] Processing block [1/1, 1/1]
I20251230 15:07:24.170382    27 feature_matching.cc:117] in 1.685s
I20251230 15:07:24.170444    27 timer.cc:90] Elapsed time: 0.032 [minutes]

+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0002/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0002/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0002/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 3 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 2.0 --Mapper.tri_min_angle 1.5 --Mapper.filter_min_tri_angle 1.5 --Mapper.tri_ignore_two_view_tracks 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:07:31.391891     1 incremental_pipeline.cc:264] Loading database
I20251230 15:07:31.423249     1 database_cache.cc:67] Loading rigs...
I20251230 15:07:31.423949     1 database_cache.cc:77]  1 in 0.001s
I20251230 15:07:31.424008     1 database_cache.cc:85] Loading cameras...
I20251230 15:07:31.424388     1 database_cache.cc:103]  1 in 0.000s
I20251230 15:07:31.424435     1 database_cache.cc:111] Loading frames...
I20251230 15:07:31.424533     1 database_cache.cc:126]  2 in 0.000s
I20251230 15:07:31.424563     1 database_cache.cc:134] Loading matches...
I20251230 15:07:31.424638     1 database_cache.cc:139]  1 in 0.000s
I20251230 15:07:31.424657     1 database_cache.cc:155] Loading images...
I20251230 15:07:31.463973     1 database_cache.cc:239]  2 in 0.039s (connected 2)
I20251230 15:07:31.464032     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:07:31.464600     1 database_cache.cc:277]  in 0.001s (ignored 0)
I20251230 15:07:31.465072     1 timer.cc:90] Elapsed time: 0.001 [minutes]
I20251230 15:07:31.466650     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:07:31.541493     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #2
I20251230 15:07:31.542354     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:07:31.634307     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:07:31.634407     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:07:31.634737     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:07:31.634905     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:07:31.638342     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:07:31.638401     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:07:31.638446     1 incremental_pipeline.cc:245] => Relaxing the initialization constraints.
I20251230 15:07:31.638551     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:07:31.656816     1 incremental_pipeline.cc:335] Registering initial image pair #2 and #1
I20251230 15:07:31.657699     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:07:31.657821     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:07:31.657831     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:07:31.657855     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:07:31.657967     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:07:31.661599     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:07:31.661669     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:07:31.661698     1 incremental_pipeline.cc:254] => Relaxing the initialization constraints.
I20251230 15:07:31.661830     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:07:31.680575     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #2
I20251230 15:07:31.681612     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:07:31.681797     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:07:31.681841     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:07:31.681871     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:07:31.682003     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:07:31.683969     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:07:31.684005     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:07:31.684028     1 incremental_pipeline.cc:245] => Relaxing the initialization constraints.
I20251230 15:07:31.684185     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:07:31.699770     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #2
I20251230 15:07:31.700881     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:07:31.701117     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:07:31.701136     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:07:31.701160     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:07:31.701282     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:07:31.703114     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:07:31.703174     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:07:31.703199     1 incremental_pipeline.cc:254] => Relaxing the initialization constraints.
I20251230 15:07:31.703363     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:07:31.720479     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #2
I20251230 15:07:31.721419     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:07:31.721547     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:07:31.721560     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:07:31.721585     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:07:31.721735     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:07:31.726271     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:07:31.726365     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:07:31.726406     1 timer.cc:90] Elapsed time: 0.006 [minutes]
E20251230 15:07:31.726429     1 sfm.cc:278] failed to create sparse model

[retry] pt_stpeters_stpauls/cluster_0002: mapper attempt 2 (min_model_size=2, init_min_inliers=15, init_min_tri_angle=1.0, tri_min_angle=0.25, local_ba_min_tri_angle=0.25, tri_ignore_two_view_tracks=0)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0002/colmap.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0002/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0002/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 2 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 1.0 --Mapper.tri_min_angle 0.25 --Mapper.filter_min_tri_angle 0.25 --Mapper.tri_ignore_two_view_tracks 0

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:07:36.852065     1 incremental_pipeline.cc:264] Loading database
I20251230 15:07:36.853545     1 database_cache.cc:67] Loading rigs...
I20251230 15:07:36.853641     1 database_cache.cc:77]  1 in 0.000s
I20251230 15:07:36.853652     1 database_cache.cc:85] Loading cameras...
I20251230 15:07:36.853664     1 database_cache.cc:103]  1 in 0.000s
I20251230 15:07:36.853688     1 database_cache.cc:111] Loading frames...
I20251230 15:07:36.853714     1 database_cache.cc:126]  2 in 0.000s
I20251230 15:07:36.853734     1 database_cache.cc:134] Loading matches...
I20251230 15:07:36.853850     1 database_cache.cc:139]  1 in 0.000s
I20251230 15:07:36.853873     1 database_cache.cc:155] Loading images...
I20251230 15:07:36.854590     1 database_cache.cc:239]  2 in 0.001s (connected 2)
I20251230 15:07:36.854628     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:07:36.854833     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:07:36.855100     1 timer.cc:90] Elapsed time: 0.000 [minutes]
I20251230 15:07:36.902252     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:07:37.101042     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #2
I20251230 15:07:37.122049     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:07:37.593688     1 incremental_pipeline.cc:597] Keeping successful reconstruction
I20251230 15:07:37.612754     1 timer.cc:90] Elapsed time: 0.013 [minutes]

[ok] pt_stpeters_stpauls/cluster_0002: sparse model ready at /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_colmap/pt_stpeters_stpauls_cluster_0002/sparse/0
[done] ok=4 skipped=0 failed=4
[fail] pt_sacrecoeur_trevi_tajmahal/cluster_0001
[fail] pt_sacrecoeur_trevi_tajmahal/cluster_0002
[fail] pt_sacrecoeur_trevi_tajmahal/cluster_0003
[fail] pt_stpeters_stpauls/cluster_0001
+ /home/shamika/miniconda3/envs/imc25/bin/python scripts/colmap_dense_clusters.py --clusters-csv /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/results/clusters_cfg4_everything_selected.csv --cache-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/cache_retrieval_finetuned_test --data-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/data/test_split_holdout_ets_sacrecoeur_stpeters --output-root /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino --runner auto --matcher dino --sparse-only
[info] Docker COLMAP does not support --Mapper.local_ba_min_tri_angle; disabling it.
Runner: docker
Clusters: 8
[cluster] 1/8: ETs/cluster_0001
[run] ETs/cluster_0001: images=10 matcher=dino
[dino] lazy loading model...

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

[dino] build db=/home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0001/colmap_dino.db images=10 pairing=auto topk=10
[dino] cache_dir=cache/dino_features
[dino] model=facebook/dinov2-small layer=last max_side=512 fp16=True
[dino] matcher: keypoints=patch max_keypoints=2048 min_similarity=0.75 min_inliers=15
[warn] --single-camera requested but image sizes differ [(262, 450), (480, 640)]; using per-image cameras.
[dino] using preloaded model on device=cuda patch=14
[dino] image 1/10: et_et000.png
[dino] extracting: et_et000.png
[dino] cached: et_et000.png
[dino] image 2/10: et_et001.png
[dino] extracting: et_et001.png
[dino] cached: et_et001.png
[dino] image 3/10: et_et002.png
[dino] extracting: et_et002.png
[dino] cached: et_et002.png
[dino] image 4/10: et_et003.png
[dino] extracting: et_et003.png
[dino] cached: et_et003.png
[dino] image 5/10: et_et004.png
[dino] extracting: et_et004.png
[dino] cached: et_et004.png
[dino] image 6/10: et_et005.png
[dino] extracting: et_et005.png
[dino] cached: et_et005.png
[dino] image 7/10: et_et006.png
[dino] extracting: et_et006.png
[dino] cached: et_et006.png
[dino] image 8/10: et_et007.png
[dino] extracting: et_et007.png
[dino] cached: et_et007.png
[dino] image 9/10: et_et008.png
[dino] extracting: et_et008.png
[dino] cached: et_et008.png
[dino] image 10/10: outliers_out_et001.png
[dino] extracting: outliers_out_et001.png
[dino] cached: outliers_out_et001.png
[dino] matching pairs=45 (RANSAC)...
[dino] pair 25/45: et_et003.png ↔ et_et004.png (inliers=80)
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0001/colmap_dino.db (images=10 pairs=45 good_pairs=37, min_inliers=15)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0001/colmap_dino.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0001/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0001/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 3 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 2.0 --Mapper.tri_min_angle 1.5 --Mapper.filter_min_tri_angle 1.5 --Mapper.tri_ignore_two_view_tracks 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:11:49.605552     1 incremental_pipeline.cc:264] Loading database
I20251230 15:11:49.793020     1 database_cache.cc:67] Loading rigs...
I20251230 15:11:49.800305     1 database_cache.cc:77]  0 in 0.007s
I20251230 15:11:49.800377     1 database_cache.cc:85] Loading cameras...
I20251230 15:11:49.932170     1 database_cache.cc:103]  10 in 0.132s
I20251230 15:11:49.932233     1 database_cache.cc:111] Loading frames...
I20251230 15:11:49.932248     1 database_cache.cc:126]  0 in 0.000s
I20251230 15:11:49.932252     1 database_cache.cc:134] Loading matches...
I20251230 15:11:50.365968     1 database_cache.cc:139]  37 in 0.434s
I20251230 15:11:50.366153     1 database_cache.cc:155] Loading images...
I20251230 15:11:52.005085     1 database_cache.cc:239]  10 in 1.639s (connected 10)
I20251230 15:11:52.005141     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:11:52.005465     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:11:52.005689     1 timer.cc:90] Elapsed time: 0.039 [minutes]
I20251230 15:11:52.037410     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:52.350594     1 incremental_pipeline.cc:335] Registering initial image pair #7 and #6
I20251230 15:11:52.351354     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:52.826076     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:11:52.826242     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:52.833925     1 incremental_pipeline.cc:335] Registering initial image pair #4 and #3
I20251230 15:11:52.834180     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.112125     1 incremental_pipeline.cc:597] Keeping successful reconstruction
I20251230 15:11:53.147230     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.158353     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #9
I20251230 15:11:53.158672     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.225090     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:11:53.225291     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.234301     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #6
I20251230 15:11:53.234563     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.241608     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:11:53.241731     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.243167     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:11:53.243201     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:11:53.243228     1 incremental_pipeline.cc:245] => Relaxing the initialization constraints.
I20251230 15:11:53.243311     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.250972     1 incremental_pipeline.cc:335] Registering initial image pair #7 and #6
I20251230 15:11:53.251403     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.251636     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:11:53.251744     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.258452     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #9
I20251230 15:11:53.258755     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.277590     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:11:53.277773     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.283504     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #6
I20251230 15:11:53.283697     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.290525     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:11:53.290660     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.297632     1 incremental_pipeline.cc:335] Registering initial image pair #7 and #1
I20251230 15:11:53.297814     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.346835     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:11:53.346995     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.348565     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:11:53.348599     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:11:53.348630     1 incremental_pipeline.cc:254] => Relaxing the initialization constraints.
I20251230 15:11:53.348699     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.360787     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #2
I20251230 15:11:53.361213     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.361588     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:11:53.361755     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.367580     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #9
I20251230 15:11:53.367802     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.389183     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:11:53.389384     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.398820     1 incremental_pipeline.cc:335] Registering initial image pair #7 and #5
I20251230 15:11:53.399106     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.402524     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:11:53.402696     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.409111     1 incremental_pipeline.cc:335] Registering initial image pair #7 and #1
I20251230 15:11:53.409343     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.409541     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:11:53.409667     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.411453     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:11:53.411482     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:11:53.411507     1 incremental_pipeline.cc:245] => Relaxing the initialization constraints.
I20251230 15:11:53.411651     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.420810     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #2
I20251230 15:11:53.421380     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.421763     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:11:53.421876     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.428408     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #9
I20251230 15:11:53.428690     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.447160     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:11:53.447314     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.454720     1 incremental_pipeline.cc:335] Registering initial image pair #7 and #5
I20251230 15:11:53.454898     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.457476     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:11:53.457582     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.462785     1 incremental_pipeline.cc:335] Registering initial image pair #7 and #1
I20251230 15:11:53.462992     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.463200     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:11:53.463321     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.464341     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:11:53.464367     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:11:53.464390     1 incremental_pipeline.cc:254] => Relaxing the initialization constraints.
I20251230 15:11:53.464447     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.470628     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #2
I20251230 15:11:53.471019     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.471288     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:11:53.471379     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.478315     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #9
I20251230 15:11:53.478539     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.495468     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:11:53.495687     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.504895     1 incremental_pipeline.cc:335] Registering initial image pair #7 and #5
I20251230 15:11:53.505154     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.508064     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:11:53.508227     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.515694     1 incremental_pipeline.cc:335] Registering initial image pair #7 and #1
I20251230 15:11:53.515952     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:11:53.516176     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:11:53.516307     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:11:53.517877     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:11:53.517911     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:11:53.517940     1 timer.cc:90] Elapsed time: 0.065 [minutes]

[ok] ETs/cluster_0001: sparse model ready at /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0001/sparse/0
[cluster] 2/8: ETs/cluster_0002
[run] ETs/cluster_0002: images=8 matcher=dino
[dino] build db=/home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0002/colmap_dino.db images=8 pairing=auto topk=10
[dino] cache_dir=cache/dino_features
[dino] model=facebook/dinov2-small layer=last max_side=512 fp16=True
[dino] matcher: keypoints=patch max_keypoints=2048 min_similarity=0.75 min_inliers=15
[warn] --single-camera requested but image sizes differ [(300, 300), (344, 500), (360, 640)]; using per-image cameras.
[dino] using preloaded model on device=cuda patch=14
[dino] image 1/8: another_et_another_et001.png
[dino] extracting: another_et_another_et001.png
[dino] cached: another_et_another_et001.png
[dino] image 2/8: another_et_another_et002.png
[dino] extracting: another_et_another_et002.png
[dino] cached: another_et_another_et002.png
[dino] image 3/8: another_et_another_et003.png
[dino] extracting: another_et_another_et003.png
[dino] cached: another_et_another_et003.png
[dino] image 4/8: another_et_another_et004.png
[dino] extracting: another_et_another_et004.png
[dino] cached: another_et_another_et004.png
[dino] image 5/8: another_et_another_et005.png
[dino] extracting: another_et_another_et005.png
[dino] cached: another_et_another_et005.png
[dino] image 6/8: another_et_another_et006.png
[dino] extracting: another_et_another_et006.png
[dino] cached: another_et_another_et006.png
[dino] image 7/8: outliers_out_et002.png
[dino] extracting: outliers_out_et002.png
[dino] cached: outliers_out_et002.png
[dino] image 8/8: outliers_out_et003.png
[dino] extracting: outliers_out_et003.png
[dino] cached: outliers_out_et003.png
[dino] matching pairs=28 (RANSAC)...
[dino] pair 25/28: another_et_another_et005.png ↔ outliers_out_et003.png (inliers=12 < min_inliers=15)
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0002/colmap_dino.db (images=8 pairs=28 good_pairs=19, min_inliers=15)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0002/colmap_dino.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0002/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0002/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 3 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 2.0 --Mapper.tri_min_angle 1.5 --Mapper.filter_min_tri_angle 1.5 --Mapper.tri_ignore_two_view_tracks 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:12:30.523172     1 incremental_pipeline.cc:264] Loading database
I20251230 15:12:30.576526     1 database_cache.cc:67] Loading rigs...
I20251230 15:12:30.576609     1 database_cache.cc:77]  0 in 0.000s
I20251230 15:12:30.576623     1 database_cache.cc:85] Loading cameras...
I20251230 15:12:30.576644     1 database_cache.cc:103]  8 in 0.000s
I20251230 15:12:30.576649     1 database_cache.cc:111] Loading frames...
I20251230 15:12:30.576656     1 database_cache.cc:126]  0 in 0.000s
I20251230 15:12:30.576661     1 database_cache.cc:134] Loading matches...
I20251230 15:12:30.576714     1 database_cache.cc:139]  19 in 0.000s
I20251230 15:12:30.576719     1 database_cache.cc:155] Loading images...
I20251230 15:12:30.577064     1 database_cache.cc:239]  8 in 0.000s (connected 8)
I20251230 15:12:30.577103     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:12:30.577437     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:12:30.577760     1 timer.cc:90] Elapsed time: 0.001 [minutes]
I20251230 15:12:30.577955     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.594164     1 incremental_pipeline.cc:335] Registering initial image pair #2 and #5
I20251230 15:12:30.594918     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:30.653420     1 incremental_pipeline.cc:439] Registering image #1 (num_reg_frames=2)
I20251230 15:12:30.653487     1 incremental_pipeline.cc:442] => Image sees 34 / 355 points
I20251230 15:12:30.679430     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:12:30.679495     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 15:12:30.680220     1 incremental_pipeline.cc:439] Registering image #1 (num_reg_frames=2)
I20251230 15:12:30.680264     1 incremental_pipeline.cc:442] => Image sees 34 / 355 points
I20251230 15:12:30.681684     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:12:30.681730     1 incremental_pipeline.cc:597] Keeping successful reconstruction
I20251230 15:12:30.683337     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.693341     1 incremental_pipeline.cc:335] Registering initial image pair #4 and #6
I20251230 15:12:30.693590     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:30.711876     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:12:30.712036     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.715618     1 incremental_pipeline.cc:335] Registering initial image pair #8 and #6
I20251230 15:12:30.715765     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:12:30.715807     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:12:30.715827     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:12:30.715852     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:30.715943     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.717327     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:12:30.717366     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:12:30.717398     1 incremental_pipeline.cc:245] => Relaxing the initialization constraints.
I20251230 15:12:30.717458     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.726475     1 incremental_pipeline.cc:335] Registering initial image pair #4 and #3
I20251230 15:12:30.726989     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:30.739866     1 incremental_pipeline.cc:439] Registering image #2 (num_reg_frames=2)
I20251230 15:12:30.739926     1 incremental_pipeline.cc:442] => Image sees 32 / 417 points
I20251230 15:12:30.740417     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:12:30.740442     1 incremental_pipeline.cc:439] Registering image #1 (num_reg_frames=2)
I20251230 15:12:30.740449     1 incremental_pipeline.cc:442] => Image sees 31 / 355 points
I20251230 15:12:30.740836     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:12:30.740859     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 15:12:30.741470     1 incremental_pipeline.cc:439] Registering image #2 (num_reg_frames=2)
I20251230 15:12:30.741500     1 incremental_pipeline.cc:442] => Image sees 32 / 417 points
I20251230 15:12:30.742185     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:12:30.742208     1 incremental_pipeline.cc:439] Registering image #1 (num_reg_frames=2)
I20251230 15:12:30.742214     1 incremental_pipeline.cc:442] => Image sees 31 / 355 points
I20251230 15:12:30.742581     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:12:30.742600     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:12:30.742703     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.752673     1 incremental_pipeline.cc:335] Registering initial image pair #3 and #6
I20251230 15:12:30.752919     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:30.759449     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:30.759680     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.762022     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:12:30.762063     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:12:30.762095     1 incremental_pipeline.cc:254] => Relaxing the initialization constraints.
I20251230 15:12:30.762157     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.771183     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #6
I20251230 15:12:30.771625     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:30.780887     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:30.781047     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.788841     1 incremental_pipeline.cc:335] Registering initial image pair #3 and #6
I20251230 15:12:30.789166     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:30.794257     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:30.794485     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.796571     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:12:30.796623     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:12:30.796654     1 incremental_pipeline.cc:245] => Relaxing the initialization constraints.
I20251230 15:12:30.796715     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.804684     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #6
I20251230 15:12:30.805030     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:30.813753     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:30.813910     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.823333     1 incremental_pipeline.cc:335] Registering initial image pair #3 and #6
I20251230 15:12:30.823578     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:30.829392     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:30.829556     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.831328     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:12:30.831372     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:12:30.831403     1 incremental_pipeline.cc:254] => Relaxing the initialization constraints.
I20251230 15:12:30.831460     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.840396     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #6
I20251230 15:12:30.840734     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:30.848870     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:30.849022     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.856370     1 incremental_pipeline.cc:335] Registering initial image pair #6 and #3
I20251230 15:12:30.856592     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:30.861656     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:30.861809     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:30.864110     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:12:30.864151     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:12:30.864181     1 timer.cc:90] Elapsed time: 0.006 [minutes]

[ok] ETs/cluster_0002: sparse model ready at /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0002/sparse/0
[cluster] 3/8: ETs/cluster_0003
[run] ETs/cluster_0003: images=4 matcher=dino
[dino] build db=/home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0003/colmap_dino.db images=4 pairing=auto topk=10
[dino] cache_dir=cache/dino_features
[dino] model=facebook/dinov2-small layer=last max_side=512 fp16=True
[dino] matcher: keypoints=patch max_keypoints=2048 min_similarity=0.75 min_inliers=15
[dino] using preloaded model on device=cuda patch=14
[dino] image 1/4: another_et_another_et007.png
[dino] extracting: another_et_another_et007.png
[dino] cached: another_et_another_et007.png
[dino] image 2/4: another_et_another_et008.png
[dino] extracting: another_et_another_et008.png
[dino] cached: another_et_another_et008.png
[dino] image 3/4: another_et_another_et009.png
[dino] extracting: another_et_another_et009.png
[dino] cached: another_et_another_et009.png
[dino] image 4/4: another_et_another_et010.png
[dino] extracting: another_et_another_et010.png
[dino] cached: another_et_another_et010.png
[dino] matching pairs=6 (RANSAC)...
[dino] pair 1/6: another_et_another_et007.png ↔ another_et_another_et008.png (inliers=79)
[dino] pair 2/6: another_et_another_et007.png ↔ another_et_another_et009.png (inliers=39)
[dino] pair 3/6: another_et_another_et007.png ↔ another_et_another_et010.png (inliers=37)
[dino] pair 4/6: another_et_another_et008.png ↔ another_et_another_et009.png (inliers=98)
[dino] pair 5/6: another_et_another_et008.png ↔ another_et_another_et010.png (inliers=52)
[dino] pair 6/6: another_et_another_et009.png ↔ another_et_another_et010.png (inliers=62)
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0003/colmap_dino.db (images=4 pairs=6 good_pairs=6, min_inliers=15)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0003/colmap_dino.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0003/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0003/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 3 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 2.0 --Mapper.tri_min_angle 1.5 --Mapper.filter_min_tri_angle 1.5 --Mapper.tri_ignore_two_view_tracks 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:12:50.379972     1 incremental_pipeline.cc:264] Loading database
I20251230 15:12:50.381330     1 database_cache.cc:67] Loading rigs...
I20251230 15:12:50.381377     1 database_cache.cc:77]  0 in 0.000s
I20251230 15:12:50.381385     1 database_cache.cc:85] Loading cameras...
I20251230 15:12:50.381397     1 database_cache.cc:103]  1 in 0.000s
I20251230 15:12:50.381402     1 database_cache.cc:111] Loading frames...
I20251230 15:12:50.381407     1 database_cache.cc:126]  0 in 0.000s
I20251230 15:12:50.381410     1 database_cache.cc:134] Loading matches...
I20251230 15:12:50.381429     1 database_cache.cc:139]  6 in 0.000s
I20251230 15:12:50.381448     1 database_cache.cc:155] Loading images...
I20251230 15:12:50.381644     1 database_cache.cc:239]  4 in 0.000s (connected 4)
I20251230 15:12:50.381683     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:12:50.381772     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:12:50.381953     1 timer.cc:90] Elapsed time: 0.000 [minutes]
I20251230 15:12:50.382040     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:50.435361     1 incremental_pipeline.cc:335] Registering initial image pair #2 and #3
I20251230 15:12:50.435606     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:50.438618     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:50.438688     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:50.443168     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:12:50.443208     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:12:50.443228     1 incremental_pipeline.cc:245] => Relaxing the initialization constraints.
I20251230 15:12:50.443262     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:50.447193     1 incremental_pipeline.cc:335] Registering initial image pair #2 and #3
I20251230 15:12:50.447376     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:50.450167     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:50.450228     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:50.454401     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:12:50.454428     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:12:50.454442     1 incremental_pipeline.cc:254] => Relaxing the initialization constraints.
I20251230 15:12:50.454463     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:50.458128     1 incremental_pipeline.cc:335] Registering initial image pair #2 and #3
I20251230 15:12:50.458313     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:50.464121     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:50.464213     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:50.468379     1 incremental_pipeline.cc:335] Registering initial image pair #3 and #1
I20251230 15:12:50.468509     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:50.468752     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:50.468847     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:50.469997     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:12:50.470021     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:12:50.470033     1 incremental_pipeline.cc:245] => Relaxing the initialization constraints.
I20251230 15:12:50.470053     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:50.473800     1 incremental_pipeline.cc:335] Registering initial image pair #2 and #3
I20251230 15:12:50.473968     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:50.479794     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:50.479857     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:50.484045     1 incremental_pipeline.cc:335] Registering initial image pair #3 and #1
I20251230 15:12:50.484176     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:50.484318     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:50.484366     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:50.485333     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:12:50.485360     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:12:50.485373     1 incremental_pipeline.cc:254] => Relaxing the initialization constraints.
I20251230 15:12:50.485394     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:50.489007     1 incremental_pipeline.cc:335] Registering initial image pair #2 and #3
I20251230 15:12:50.489176     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:50.494935     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:50.494995     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:50.499554     1 incremental_pipeline.cc:335] Registering initial image pair #3 and #1
I20251230 15:12:50.499696     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:12:50.499855     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:12:50.499922     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:50.500887     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:12:50.500911     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:12:50.500924     1 timer.cc:90] Elapsed time: 0.002 [minutes]
E20251230 15:12:50.500932     1 sfm.cc:278] failed to create sparse model

[retry] ETs/cluster_0003: mapper attempt 2 (min_model_size=2, init_min_inliers=15, init_min_tri_angle=1.0, tri_min_angle=0.25, local_ba_min_tri_angle=0.25, tri_ignore_two_view_tracks=0)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0003/colmap_dino.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0003/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0003/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 2 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 1.0 --Mapper.tri_min_angle 0.25 --Mapper.filter_min_tri_angle 0.25 --Mapper.tri_ignore_two_view_tracks 0

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:12:59.958277     1 incremental_pipeline.cc:264] Loading database
I20251230 15:12:59.959767     1 database_cache.cc:67] Loading rigs...
I20251230 15:12:59.959816     1 database_cache.cc:77]  0 in 0.000s
I20251230 15:12:59.959825     1 database_cache.cc:85] Loading cameras...
I20251230 15:12:59.959838     1 database_cache.cc:103]  1 in 0.000s
I20251230 15:12:59.959843     1 database_cache.cc:111] Loading frames...
I20251230 15:12:59.959851     1 database_cache.cc:126]  0 in 0.000s
I20251230 15:12:59.959856     1 database_cache.cc:134] Loading matches...
I20251230 15:12:59.959880     1 database_cache.cc:139]  6 in 0.000s
I20251230 15:12:59.959899     1 database_cache.cc:155] Loading images...
I20251230 15:12:59.960114     1 database_cache.cc:239]  4 in 0.000s (connected 4)
I20251230 15:12:59.960141     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:12:59.960208     1 database_cache.cc:277]  in 0.000s (ignored 0)
I20251230 15:12:59.960429     1 timer.cc:90] Elapsed time: 0.000 [minutes]
I20251230 15:12:59.960510     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:12:59.965330     1 incremental_pipeline.cc:335] Registering initial image pair #2 and #1
I20251230 15:12:59.965629     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:00.020084     1 incremental_pipeline.cc:597] Keeping successful reconstruction
I20251230 15:13:00.020973     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:00.022172     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:13:00.022207     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:13:00.022225     1 incremental_pipeline.cc:245] => Relaxing the initialization constraints.
I20251230 15:13:00.022262     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:00.025306     1 incremental_pipeline.cc:335] Registering initial image pair #3 and #4
I20251230 15:13:00.025584     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:00.025820     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:00.025874     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:00.026895     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:13:00.026923     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:13:00.026937     1 incremental_pipeline.cc:254] => Relaxing the initialization constraints.
I20251230 15:13:00.026960     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:00.029896     1 incremental_pipeline.cc:335] Registering initial image pair #3 and #4
I20251230 15:13:00.030166     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:00.030354     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:00.030406     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:00.031728     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:13:00.031757     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:13:00.031771     1 incremental_pipeline.cc:245] => Relaxing the initialization constraints.
I20251230 15:13:00.031793     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:00.034914     1 incremental_pipeline.cc:335] Registering initial image pair #3 and #4
I20251230 15:13:00.035203     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:00.035408     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:00.035465     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:00.036758     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:13:00.036788     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:13:00.036804     1 incremental_pipeline.cc:254] => Relaxing the initialization constraints.
I20251230 15:13:00.036829     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:00.040014     1 incremental_pipeline.cc:335] Registering initial image pair #3 and #4
I20251230 15:13:00.040366     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:00.040603     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:00.040663     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:00.042096     1 incremental_pipeline.cc:315] => No good initial image pair found.
I20251230 15:13:00.042121     1 incremental_pipeline.cc:559] Discarding reconstruction due to no initial pair
I20251230 15:13:00.042135     1 timer.cc:90] Elapsed time: 0.001 [minutes]

[ok] ETs/cluster_0003: sparse model ready at /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/ETs_cluster_0003/sparse/0
[cluster] 4/8: pt_sacrecoeur_trevi_tajmahal/cluster_0001
[run] pt_sacrecoeur_trevi_tajmahal/cluster_0001: images=75 matcher=dino
[dino] build db=/home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0001/colmap_dino.db images=75 pairing=auto topk=10
[dino] cache_dir=cache/dino_features
[dino] model=facebook/dinov2-small layer=last max_side=512 fp16=True
[dino] matcher: keypoints=patch max_keypoints=2048 min_similarity=0.75 min_inliers=15
[warn] --single-camera requested but image sizes differ [(375, 501), (375, 502), (497, 497), (537, 820), (566, 1009), (660, 485), (678, 1018), (680, 1025), (684, 1031), (686, 1045), (687, 1041), (696, 1077), (699, 1088), (717, 1043), (760, 1014), (765, 1021), (768, 1025), (777, 1048), (781, 1059), (784, 1067), (828, 610), (970, 1026), (982, 551), (983, 652), (992, 728), (997, 665), (1000, 667), (1002, 668), (1004, 669), (1008, 670), (1009, 673), (1016, 762), (1019, 679), (1019, 776), (1021, 678), (1022, 681), (1023, 767), (1023, 770), (1024, 767), (1025, 767), (1025, 768), (1026, 768), (1027, 768), (1028, 683), (1028, 769), (1029, 769), (1030, 684), (1030, 692), (1030, 769), (1030, 770), (1032, 640), (1034, 771), (1036, 772), (1037, 595), (1038, 773), (1039, 773), (1043, 1043), (1044, 688), (1045, 776), (1045, 777), (1046, 770), (1047, 775), (1047, 776), (1048, 777), (1053, 779), (1058, 691), (1060, 781), (1064, 691), (1064, 693), (1087, 698), (1093, 699)]; using per-image cameras.
[dino] using preloaded model on device=cuda patch=14
[dino] image 1/75: taj_mahal_02760416_4808737899.png
[dino] extracting: taj_mahal_02760416_4808737899.png
[dino] cached: taj_mahal_02760416_4808737899.png
[dino] image 2/75: taj_mahal_03779515_11822031593.png
[dino] extracting: taj_mahal_03779515_11822031593.png
[dino] cached: taj_mahal_03779515_11822031593.png
[dino] image 3/75: taj_mahal_05099279_2123782505.png
[dino] extracting: taj_mahal_05099279_2123782505.png
[dino] cached: taj_mahal_05099279_2123782505.png
[dino] image 4/75: taj_mahal_05644193_4809375226.png
[dino] extracting: taj_mahal_05644193_4809375226.png
[dino] cached: taj_mahal_05644193_4809375226.png
[dino] image 5/75: taj_mahal_07292828_6865863886.png
[dino] extracting: taj_mahal_07292828_6865863886.png
[dino] cached: taj_mahal_07292828_6865863886.png
[dino] image 6/75: taj_mahal_07295255_5949580464.png
[dino] extracting: taj_mahal_07295255_5949580464.png
[dino] cached: taj_mahal_07295255_5949580464.png
[dino] image 7/75: taj_mahal_09748237_4479958542.png
[dino] extracting: taj_mahal_09748237_4479958542.png
[dino] cached: taj_mahal_09748237_4479958542.png
[dino] image 8/75: taj_mahal_15626988_320395276.png
[dino] extracting: taj_mahal_15626988_320395276.png
[dino] cached: taj_mahal_15626988_320395276.png
[dino] image 9/75: taj_mahal_16773607_5525472114.png
[dino] extracting: taj_mahal_16773607_5525472114.png
[dino] cached: taj_mahal_16773607_5525472114.png
[dino] image 10/75: taj_mahal_17911381_11822031993.png
[dino] extracting: taj_mahal_17911381_11822031993.png
[dino] cached: taj_mahal_17911381_11822031993.png
[dino] image 11/75: taj_mahal_21749909_452666809.png
[dino] extracting: taj_mahal_21749909_452666809.png
[dino] cached: taj_mahal_21749909_452666809.png
[dino] image 12/75: taj_mahal_23360557_2453971988.png
[dino] extracting: taj_mahal_23360557_2453971988.png
[dino] cached: taj_mahal_23360557_2453971988.png
[dino] image 13/75: taj_mahal_25038173_427948647.png
[dino] extracting: taj_mahal_25038173_427948647.png
[dino] cached: taj_mahal_25038173_427948647.png
[dino] image 14/75: taj_mahal_28658320_3250275528.png
[dino] extracting: taj_mahal_28658320_3250275528.png
[dino] cached: taj_mahal_28658320_3250275528.png
[dino] image 15/75: taj_mahal_33243562_4772593759.png
[dino] extracting: taj_mahal_33243562_4772593759.png
[dino] cached: taj_mahal_33243562_4772593759.png
[dino] image 16/75: taj_mahal_33561486_8345882977.png
[dino] extracting: taj_mahal_33561486_8345882977.png
[dino] cached: taj_mahal_33561486_8345882977.png
[dino] image 17/75: taj_mahal_33878661_5337234382.png
[dino] extracting: taj_mahal_33878661_5337234382.png
[dino] cached: taj_mahal_33878661_5337234382.png
[dino] image 18/75: taj_mahal_34892661_4479236831.png
[dino] extracting: taj_mahal_34892661_4479236831.png
[dino] cached: taj_mahal_34892661_4479236831.png
[dino] image 19/75: taj_mahal_35012799_233724898.png
[dino] extracting: taj_mahal_35012799_233724898.png
[dino] cached: taj_mahal_35012799_233724898.png
[dino] image 20/75: taj_mahal_35310867_4710497352.png
[dino] extracting: taj_mahal_35310867_4710497352.png
[dino] cached: taj_mahal_35310867_4710497352.png
[dino] image 21/75: taj_mahal_35871047_6486466789.png
[dino] extracting: taj_mahal_35871047_6486466789.png
[dino] cached: taj_mahal_35871047_6486466789.png
[dino] image 22/75: taj_mahal_36670333_3773568633.png
[dino] extracting: taj_mahal_36670333_3773568633.png
[dino] cached: taj_mahal_36670333_3773568633.png
[dino] image 23/75: taj_mahal_40047213_6060347747.png
[dino] extracting: taj_mahal_40047213_6060347747.png
[dino] cached: taj_mahal_40047213_6060347747.png
[dino] image 24/75: taj_mahal_40301482_6349100470.png
[dino] extracting: taj_mahal_40301482_6349100470.png
[dino] cached: taj_mahal_40301482_6349100470.png
[dino] image 25/75: taj_mahal_40357326_9141483717.png
[dino] extracting: taj_mahal_40357326_9141483717.png
[dino] cached: taj_mahal_40357326_9141483717.png
[dino] image 26/75: taj_mahal_40461214_8192836476.png
[dino] extracting: taj_mahal_40461214_8192836476.png
[dino] cached: taj_mahal_40461214_8192836476.png
[dino] image 27/75: taj_mahal_41314954_4418442825.png
[dino] extracting: taj_mahal_41314954_4418442825.png
[dino] cached: taj_mahal_41314954_4418442825.png
[dino] image 28/75: taj_mahal_45203396_7995388605.png
[dino] extracting: taj_mahal_45203396_7995388605.png
[dino] cached: taj_mahal_45203396_7995388605.png
[dino] image 29/75: taj_mahal_46195638_3569985892.png
[dino] extracting: taj_mahal_46195638_3569985892.png
[dino] cached: taj_mahal_46195638_3569985892.png
[dino] image 30/75: taj_mahal_46483850_3092227510.png
[dino] extracting: taj_mahal_46483850_3092227510.png
[dino] cached: taj_mahal_46483850_3092227510.png
[dino] image 31/75: taj_mahal_47981545_2123782613.png
[dino] extracting: taj_mahal_47981545_2123782613.png
[dino] cached: taj_mahal_47981545_2123782613.png
[dino] image 32/75: taj_mahal_48590156_9372591744.png
[dino] extracting: taj_mahal_48590156_9372591744.png
[dino] cached: taj_mahal_48590156_9372591744.png
[dino] image 33/75: taj_mahal_51297211_3293524007.png
[dino] extracting: taj_mahal_51297211_3293524007.png
[dino] cached: taj_mahal_51297211_3293524007.png
[dino] image 34/75: taj_mahal_52650931_8268706459.png
[dino] extracting: taj_mahal_52650931_8268706459.png
[dino] cached: taj_mahal_52650931_8268706459.png
[dino] image 35/75: taj_mahal_53757432_11494604856.png
[dino] extracting: taj_mahal_53757432_11494604856.png
[dino] cached: taj_mahal_53757432_11494604856.png
[dino] image 36/75: taj_mahal_54900410_4709458745.png
[dino] extracting: taj_mahal_54900410_4709458745.png
[dino] cached: taj_mahal_54900410_4709458745.png
[dino] image 37/75: taj_mahal_57532696_297637106.png
[dino] extracting: taj_mahal_57532696_297637106.png
[dino] cached: taj_mahal_57532696_297637106.png
[dino] image 38/75: taj_mahal_66281696_4846036976.png
[dino] extracting: taj_mahal_66281696_4846036976.png
[dino] cached: taj_mahal_66281696_4846036976.png
[dino] image 39/75: taj_mahal_67319805_2215339300.png
[dino] extracting: taj_mahal_67319805_2215339300.png
[dino] cached: taj_mahal_67319805_2215339300.png
[dino] image 40/75: taj_mahal_68263048_3884219324.png
[dino] extracting: taj_mahal_68263048_3884219324.png
[dino] cached: taj_mahal_68263048_3884219324.png
[dino] image 41/75: taj_mahal_68284397_7307804012.png
[dino] extracting: taj_mahal_68284397_7307804012.png
[dino] cached: taj_mahal_68284397_7307804012.png
[dino] image 42/75: taj_mahal_70456501_320396748.png
[dino] extracting: taj_mahal_70456501_320396748.png
[dino] cached: taj_mahal_70456501_320396748.png
[dino] image 43/75: taj_mahal_70518655_6429111743.png
[dino] extracting: taj_mahal_70518655_6429111743.png
[dino] cached: taj_mahal_70518655_6429111743.png
[dino] image 44/75: taj_mahal_72418664_4552163871.png
[dino] extracting: taj_mahal_72418664_4552163871.png
[dino] cached: taj_mahal_72418664_4552163871.png
[dino] image 45/75: taj_mahal_72721370_6780643247.png
[dino] extracting: taj_mahal_72721370_6780643247.png
[dino] cached: taj_mahal_72721370_6780643247.png
[dino] image 46/75: taj_mahal_73045053_2123874963.png
[dino] extracting: taj_mahal_73045053_2123874963.png
[dino] cached: taj_mahal_73045053_2123874963.png
[dino] image 47/75: taj_mahal_73346411_11842150495.png
[dino] extracting: taj_mahal_73346411_11842150495.png
[dino] cached: taj_mahal_73346411_11842150495.png
[dino] image 48/75: taj_mahal_75694348_4552162843.png
[dino] extracting: taj_mahal_75694348_4552162843.png
[dino] cached: taj_mahal_75694348_4552162843.png
[dino] image 49/75: taj_mahal_75960124_233048597.png
[dino] extracting: taj_mahal_75960124_233048597.png
[dino] cached: taj_mahal_75960124_233048597.png
[dino] image 50/75: taj_mahal_78595827_6619694947.png
[dino] extracting: taj_mahal_78595827_6619694947.png
[dino] cached: taj_mahal_78595827_6619694947.png
[dino] image 51/75: taj_mahal_79695821_354966524.png
[dino] extracting: taj_mahal_79695821_354966524.png
[dino] cached: taj_mahal_79695821_354966524.png
[dino] image 52/75: taj_mahal_80209116_3299258442.png
[dino] extracting: taj_mahal_80209116_3299258442.png
[dino] cached: taj_mahal_80209116_3299258442.png
[dino] image 53/75: taj_mahal_80696644_2234023339.png
[dino] extracting: taj_mahal_80696644_2234023339.png
[dino] cached: taj_mahal_80696644_2234023339.png
[dino] image 54/75: taj_mahal_81509461_2124556500.png
[dino] extracting: taj_mahal_81509461_2124556500.png
[dino] cached: taj_mahal_81509461_2124556500.png
[dino] image 55/75: taj_mahal_82182023_330370375.png
[dino] extracting: taj_mahal_82182023_330370375.png
[dino] cached: taj_mahal_82182023_330370375.png
[dino] image 56/75: taj_mahal_82967489_11494979004.png
[dino] extracting: taj_mahal_82967489_11494979004.png
[dino] cached: taj_mahal_82967489_11494979004.png
[dino] image 57/75: taj_mahal_84623051_5972175223.png
[dino] extracting: taj_mahal_84623051_5972175223.png
[dino] cached: taj_mahal_84623051_5972175223.png
[dino] image 58/75: taj_mahal_84741117_2234024581.png
[dino] extracting: taj_mahal_84741117_2234024581.png
[dino] cached: taj_mahal_84741117_2234024581.png
[dino] image 59/75: taj_mahal_85291466_3299259390.png
[dino] extracting: taj_mahal_85291466_3299259390.png
[dino] cached: taj_mahal_85291466_3299259390.png
[dino] image 60/75: taj_mahal_86821641_6619697153.png
[dino] extracting: taj_mahal_86821641_6619697153.png
[dino] cached: taj_mahal_86821641_6619697153.png
[dino] image 61/75: taj_mahal_86871041_2123874981.png
[dino] extracting: taj_mahal_86871041_2123874981.png
[dino] cached: taj_mahal_86871041_2123874981.png
[dino] image 62/75: taj_mahal_87027560_6486839789.png
[dino] extracting: taj_mahal_87027560_6486839789.png
[dino] cached: taj_mahal_87027560_6486839789.png
[dino] image 63/75: taj_mahal_87115605_383650319.png
[dino] extracting: taj_mahal_87115605_383650319.png
[dino] cached: taj_mahal_87115605_383650319.png
[dino] image 64/75: taj_mahal_88652653_6486332399.png
[dino] extracting: taj_mahal_88652653_6486332399.png
[dino] cached: taj_mahal_88652653_6486332399.png
[dino] image 65/75: taj_mahal_88681740_6486186923.png
[dino] extracting: taj_mahal_88681740_6486186923.png
[dino] cached: taj_mahal_88681740_6486186923.png
[dino] image 66/75: taj_mahal_89175833_3348677963.png
[dino] extracting: taj_mahal_89175833_3348677963.png
[dino] cached: taj_mahal_89175833_3348677963.png
[dino] image 67/75: taj_mahal_92344991_5630498660.png
[dino] extracting: taj_mahal_92344991_5630498660.png
[dino] cached: taj_mahal_92344991_5630498660.png
[dino] image 68/75: taj_mahal_95761991_3716491774.png
[dino] extracting: taj_mahal_95761991_3716491774.png
[dino] cached: taj_mahal_95761991_3716491774.png
[dino] image 69/75: taj_mahal_96431892_320398075.png
[dino] extracting: taj_mahal_96431892_320398075.png
[dino] cached: taj_mahal_96431892_320398075.png
[dino] image 70/75: taj_mahal_96947007_371077369.png
[dino] extracting: taj_mahal_96947007_371077369.png
[dino] cached: taj_mahal_96947007_371077369.png
[dino] image 71/75: taj_mahal_97524709_11495119913.png
[dino] extracting: taj_mahal_97524709_11495119913.png
[dino] cached: taj_mahal_97524709_11495119913.png
[dino] image 72/75: taj_mahal_97855310_320398500.png
[dino] extracting: taj_mahal_97855310_320398500.png
[dino] cached: taj_mahal_97855310_320398500.png
[dino] image 73/75: taj_mahal_99106990_5972735988.png
[dino] extracting: taj_mahal_99106990_5972735988.png
[dino] cached: taj_mahal_99106990_5972735988.png
[dino] image 74/75: taj_mahal_99238567_2155545598.png
[dino] extracting: taj_mahal_99238567_2155545598.png
[dino] cached: taj_mahal_99238567_2155545598.png
[dino] image 75/75: taj_mahal_99395911_415466662.png
[dino] extracting: taj_mahal_99395911_415466662.png
[dino] cached: taj_mahal_99395911_415466662.png
[dino] matching pairs=516 (RANSAC)...
[dino] pair 25/516: taj_mahal_03779515_11822031593.png ↔ taj_mahal_40047213_6060347747.png (inliers=32)
[dino] pair 50/516: taj_mahal_05644193_4809375226.png ↔ taj_mahal_72418664_4552163871.png (inliers=36)
[dino] pair 75/516: taj_mahal_07295255_5949580464.png ↔ taj_mahal_86821641_6619697153.png (inliers=37)
[dino] pair 100/516: taj_mahal_15626988_320395276.png ↔ taj_mahal_97855310_320398500.png (inliers=132)
[dino] pair 125/516: taj_mahal_21749909_452666809.png ↔ taj_mahal_35012799_233724898.png (inliers=55)
[dino] pair 150/516: taj_mahal_23360557_2453971988.png ↔ taj_mahal_86821641_6619697153.png (inliers=73)
[dino] pair 175/516: taj_mahal_28658320_3250275528.png ↔ taj_mahal_86821641_6619697153.png (inliers=21)
[dino] pair 200/516: taj_mahal_33561486_8345882977.png ↔ taj_mahal_81509461_2124556500.png (inliers=63)
[dino] pair 225/516: taj_mahal_33878661_5337234382.png ↔ taj_mahal_96947007_371077369.png (inliers=72)
[dino] pair 250/516: taj_mahal_35310867_4710497352.png ↔ taj_mahal_45203396_7995388605.png (inliers=52)
[dino] pair 275/516: taj_mahal_40047213_6060347747.png ↔ taj_mahal_48590156_9372591744.png (inliers=20)
[dino] pair 300/516: taj_mahal_40301482_6349100470.png ↔ taj_mahal_95761991_3716491774.png (inliers=66)
[dino] pair 325/516: taj_mahal_41314954_4418442825.png ↔ taj_mahal_73045053_2123874963.png (inliers=42)
[dino] pair 350/516: taj_mahal_46483850_3092227510.png ↔ taj_mahal_99238567_2155545598.png (inliers=89)
[dino] pair 375/516: taj_mahal_52650931_8268706459.png ↔ taj_mahal_99106990_5972735988.png (inliers=29)
[dino] pair 400/516: taj_mahal_66281696_4846036976.png ↔ taj_mahal_79695821_354966524.png (inliers=23)
[dino] pair 425/516: taj_mahal_70456501_320396748.png ↔ taj_mahal_84623051_5972175223.png (inliers=36)
[dino] pair 450/516: taj_mahal_73045053_2123874963.png ↔ taj_mahal_81509461_2124556500.png (inliers=28)
[dino] pair 475/516: taj_mahal_80209116_3299258442.png ↔ taj_mahal_85291466_3299259390.png (inliers=47)
[dino] pair 500/516: taj_mahal_87027560_6486839789.png ↔ taj_mahal_88681740_6486186923.png (inliers=106)
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0001/colmap_dino.db (images=75 pairs=516 good_pairs=514, min_inliers=15)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0001/colmap_dino.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0001/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0001/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 3 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 2.0 --Mapper.tri_min_angle 1.5 --Mapper.filter_min_tri_angle 1.5 --Mapper.tri_ignore_two_view_tracks 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:13:50.344748     1 incremental_pipeline.cc:264] Loading database
I20251230 15:13:50.457525     1 database_cache.cc:67] Loading rigs...
I20251230 15:13:50.457600     1 database_cache.cc:77]  0 in 0.000s
I20251230 15:13:50.457623     1 database_cache.cc:85] Loading cameras...
I20251230 15:13:50.457710     1 database_cache.cc:103]  75 in 0.000s
I20251230 15:13:50.457741     1 database_cache.cc:111] Loading frames...
I20251230 15:13:50.457758     1 database_cache.cc:126]  0 in 0.000s
I20251230 15:13:50.457767     1 database_cache.cc:134] Loading matches...
I20251230 15:13:50.464164     1 database_cache.cc:139]  514 in 0.006s
I20251230 15:13:50.464269     1 database_cache.cc:155] Loading images...
I20251230 15:13:50.474920     1 database_cache.cc:239]  75 in 0.011s (connected 75)
I20251230 15:13:50.475039     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:13:50.490159     1 database_cache.cc:277]  in 0.015s (ignored 0)
I20251230 15:13:50.490958     1 timer.cc:90] Elapsed time: 0.002 [minutes]
I20251230 15:13:50.499480     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:50.786827     1 incremental_pipeline.cc:335] Registering initial image pair #39 and #46
I20251230 15:13:50.787804     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:54.167294     1 incremental_pipeline.cc:597] Keeping successful reconstruction
I20251230 15:13:54.574007     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:54.581918     1 incremental_pipeline.cc:335] Registering initial image pair #24 and #53
I20251230 15:13:54.582746     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:54.698655     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:54.700568     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:54.713658     1 incremental_pipeline.cc:335] Registering initial image pair #24 and #33
I20251230 15:13:54.714582     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:54.780604     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:13:54.782045     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:54.789451     1 incremental_pipeline.cc:335] Registering initial image pair #17 and #69
I20251230 15:13:54.790040     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:54.807487     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:54.808372     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:54.816517     1 incremental_pipeline.cc:335] Registering initial image pair #17 and #8
I20251230 15:13:54.817148     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:54.832904     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:54.833813     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:54.840936     1 incremental_pipeline.cc:335] Registering initial image pair #48 and #43
I20251230 15:13:54.841500     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:54.875151     1 incremental_pipeline.cc:439] Registering image #12 (num_reg_frames=2)
I20251230 15:13:54.875208     1 incremental_pipeline.cc:442] => Image sees 32 / 490 points
I20251230 15:13:54.970118     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:54.970185     1 incremental_pipeline.cc:439] Registering image #52 (num_reg_frames=2)
I20251230 15:13:54.970196     1 incremental_pipeline.cc:442] => Image sees 31 / 449 points
I20251230 15:13:54.971562     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:54.971581     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 15:13:54.972167     1 incremental_pipeline.cc:439] Registering image #12 (num_reg_frames=2)
I20251230 15:13:54.972203     1 incremental_pipeline.cc:442] => Image sees 32 / 490 points
I20251230 15:13:54.978081     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:54.978109     1 incremental_pipeline.cc:439] Registering image #52 (num_reg_frames=2)
I20251230 15:13:54.978117     1 incremental_pipeline.cc:442] => Image sees 31 / 449 points
I20251230 15:13:54.979527     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:54.979565     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:13:54.980592     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:54.987850     1 incremental_pipeline.cc:335] Registering initial image pair #48 and #60
I20251230 15:13:54.988382     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.000154     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.001021     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.013029     1 incremental_pipeline.cc:335] Registering initial image pair #63 and #67
I20251230 15:13:55.013468     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.013883     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.014799     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.023161     1 incremental_pipeline.cc:335] Registering initial image pair #63 and #24
I20251230 15:13:55.023941     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.091439     1 incremental_pipeline.cc:439] Registering image #37 (num_reg_frames=2)
I20251230 15:13:55.091497     1 incremental_pipeline.cc:442] => Image sees 34 / 482 points
I20251230 15:13:55.092882     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:55.092933     1 incremental_pipeline.cc:439] Registering image #33 (num_reg_frames=2)
I20251230 15:13:55.092943     1 incremental_pipeline.cc:442] => Image sees 34 / 445 points
I20251230 15:13:55.093485     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:55.093500     1 incremental_pipeline.cc:439] Registering image #53 (num_reg_frames=2)
I20251230 15:13:55.093506     1 incremental_pipeline.cc:442] => Image sees 33 / 363 points
I20251230 15:13:55.094120     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:55.094192     1 incremental_pipeline.cc:439] Registering image #1 (num_reg_frames=2)
I20251230 15:13:55.094235     1 incremental_pipeline.cc:442] => Image sees 33 / 559 points
I20251230 15:13:55.094692     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:55.094718     1 incremental_pipeline.cc:439] Registering image #19 (num_reg_frames=2)
I20251230 15:13:55.094726     1 incremental_pipeline.cc:442] => Image sees 31 / 507 points
I20251230 15:13:55.096452     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:55.096495     1 incremental_pipeline.cc:439] Registering image #39 (num_reg_frames=2)
I20251230 15:13:55.096508     1 incremental_pipeline.cc:442] => Image sees 30 / 571 points
I20251230 15:13:55.105271     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:55.105350     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 15:13:55.125486     1 incremental_pipeline.cc:439] Registering image #37 (num_reg_frames=2)
I20251230 15:13:55.125562     1 incremental_pipeline.cc:442] => Image sees 34 / 482 points
I20251230 15:13:55.127436     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:55.127466     1 incremental_pipeline.cc:439] Registering image #33 (num_reg_frames=2)
I20251230 15:13:55.127475     1 incremental_pipeline.cc:442] => Image sees 34 / 445 points
I20251230 15:13:55.127969     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:55.127991     1 incremental_pipeline.cc:439] Registering image #53 (num_reg_frames=2)
I20251230 15:13:55.127998     1 incremental_pipeline.cc:442] => Image sees 33 / 363 points
I20251230 15:13:55.128509     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:55.128533     1 incremental_pipeline.cc:439] Registering image #1 (num_reg_frames=2)
I20251230 15:13:55.128542     1 incremental_pipeline.cc:442] => Image sees 33 / 559 points
I20251230 15:13:55.128973     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:55.128999     1 incremental_pipeline.cc:439] Registering image #19 (num_reg_frames=2)
I20251230 15:13:55.129009     1 incremental_pipeline.cc:442] => Image sees 31 / 507 points
I20251230 15:13:55.131024     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:55.131083     1 incremental_pipeline.cc:439] Registering image #39 (num_reg_frames=2)
I20251230 15:13:55.131095     1 incremental_pipeline.cc:442] => Image sees 30 / 571 points
I20251230 15:13:55.140300     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:13:55.140380     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:13:55.141387     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.156302     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #41
I20251230 15:13:55.156675     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.157054     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.157927     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.165498     1 incremental_pipeline.cc:335] Registering initial image pair #1 and #25
I20251230 15:13:55.165959     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:13:55.166036     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:13:55.166047     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:13:55.166090     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.167052     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.177057     1 incremental_pipeline.cc:335] Registering initial image pair #52 and #2
I20251230 15:13:55.177374     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.181548     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.182646     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.193368     1 incremental_pipeline.cc:335] Registering initial image pair #52 and #13
I20251230 15:13:55.193730     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.197052     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.197952     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.212184     1 incremental_pipeline.cc:335] Registering initial image pair #12 and #38
I20251230 15:13:55.212560     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.216302     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.217285     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.228287     1 incremental_pipeline.cc:335] Registering initial image pair #12 and #18
I20251230 15:13:55.228619     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.235594     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.236682     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.250006     1 incremental_pipeline.cc:335] Registering initial image pair #19 and #41
I20251230 15:13:55.250414     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.254380     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.255471     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.275082     1 incremental_pipeline.cc:335] Registering initial image pair #19 and #27
I20251230 15:13:55.275467     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.280193     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.281294     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.291518     1 incremental_pipeline.cc:335] Registering initial image pair #11 and #31
I20251230 15:13:55.291865     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:13:55.291932     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:13:55.291941     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:13:55.291970     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.292996     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.320933     1 incremental_pipeline.cc:335] Registering initial image pair #11 and #27
I20251230 15:13:55.321250     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:13:55.321308     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:13:55.321316     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:13:55.321345     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.322304     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.332154     1 incremental_pipeline.cc:335] Registering initial image pair #16 and #74
I20251230 15:13:55.332589     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:13:55.332649     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:13:55.332656     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:13:55.332685     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.333484     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.342065     1 incremental_pipeline.cc:335] Registering initial image pair #29 and #54
I20251230 15:13:55.342581     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.353449     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.354476     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.378157     1 incremental_pipeline.cc:335] Registering initial image pair #16 and #24
I20251230 15:13:55.378578     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.381374     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.382277     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.396456     1 incremental_pipeline.cc:335] Registering initial image pair #33 and #44
I20251230 15:13:55.396752     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.401145     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.402024     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.410318     1 incremental_pipeline.cc:335] Registering initial image pair #25 and #51
I20251230 15:13:55.410652     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.451162     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:13:55.451960     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.461011     1 incremental_pipeline.cc:335] Registering initial image pair #10 and #30
I20251230 15:13:55.461329     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.494082     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:13:55.494999     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.508917     1 incremental_pipeline.cc:335] Registering initial image pair #47 and #2
I20251230 15:13:55.509234     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.515404     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.516320     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.538394     1 incremental_pipeline.cc:335] Registering initial image pair #10 and #70
I20251230 15:13:55.538769     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.549048     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.550283     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.564296     1 incremental_pipeline.cc:335] Registering initial image pair #58 and #54
I20251230 15:13:55.564580     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:13:55.564632     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:13:55.564639     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:13:55.564668     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.565519     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.580401     1 incremental_pipeline.cc:335] Registering initial image pair #38 and #24
I20251230 15:13:55.580755     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:13:55.633620     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.634532     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.650640     1 incremental_pipeline.cc:335] Registering initial image pair #30 and #67
I20251230 15:13:55.650943     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:13:55.651001     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:13:55.651010     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:13:55.651050     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:13:55.652077     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:13:55.674980     1 incremental_pipeline.cc:335] Registering initial image pair #28 and #48
I20251230 15:13:55.675329     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:13:55.675385     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:13:55.675393     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0

[ok] pt_sacrecoeur_trevi_tajmahal/cluster_0001: sparse model ready at /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0001/sparse/0
[cluster] 5/8: pt_sacrecoeur_trevi_tajmahal/cluster_0002
[run] pt_sacrecoeur_trevi_tajmahal/cluster_0002: images=75 matcher=dino
[dino] build db=/home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0002/colmap_dino.db images=75 pairing=auto topk=10
[dino] cache_dir=cache/dino_features
[dino] model=facebook/dinov2-small layer=last max_side=512 fp16=True
[dino] matcher: keypoints=patch max_keypoints=2048 min_similarity=0.75 min_inliers=15
[warn] --single-camera requested but image sizes differ [(497, 497), (517, 383), (575, 1025), (596, 795), (674, 1017), (682, 1023), (686, 1036), (691, 1057), (694, 1057), (696, 1055), (698, 1082), (757, 1010), (771, 1032), (772, 1035), (774, 1041), (775, 1042), (778, 1050), (779, 1050), (779, 1054), (782, 1061), (782, 1062), (783, 1064), (785, 1054), (819, 607), (968, 643), (993, 664), (1000, 749), (1019, 696), (1020, 683), (1020, 1020), (1022, 681), (1023, 1023), (1024, 767), (1025, 756), (1029, 683), (1032, 770), (1033, 682), (1034, 687), (1035, 578), (1035, 640), (1035, 771), (1035, 772), (1036, 685), (1037, 686), (1037, 772), (1040, 774), (1042, 775), (1045, 690), (1045, 776), (1046, 776), (1047, 777), (1049, 777), (1051, 778), (1052, 693), (1052, 778), (1053, 779), (1054, 779), (1055, 779), (1057, 780), (1059, 692), (1060, 782), (1061, 689), (1061, 692), (1061, 750), (1061, 782), (1062, 782), (1063, 693), (1063, 783), (1064, 582), (1066, 784), (1074, 787), (1085, 791)]; using per-image cameras.
[dino] using preloaded model on device=cuda patch=14
[dino] image 1/75: trevi_fountain_00358444_4165248133.png
[dino] extracting: trevi_fountain_00358444_4165248133.png
[dino] cached: trevi_fountain_00358444_4165248133.png
[dino] image 2/75: trevi_fountain_01241225_4293371290.png
[dino] extracting: trevi_fountain_01241225_4293371290.png
[dino] cached: trevi_fountain_01241225_4293371290.png
[dino] image 3/75: trevi_fountain_01404558_5160423697.png
[dino] extracting: trevi_fountain_01404558_5160423697.png
[dino] cached: trevi_fountain_01404558_5160423697.png
[dino] image 4/75: trevi_fountain_09071644_2938441433.png
[dino] extracting: trevi_fountain_09071644_2938441433.png
[dino] cached: trevi_fountain_09071644_2938441433.png
[dino] image 5/75: trevi_fountain_14195208_276265172.png
[dino] extracting: trevi_fountain_14195208_276265172.png
[dino] cached: trevi_fountain_14195208_276265172.png
[dino] image 6/75: trevi_fountain_15038544_3727504813.png
[dino] extracting: trevi_fountain_15038544_3727504813.png
[dino] cached: trevi_fountain_15038544_3727504813.png
[dino] image 7/75: trevi_fountain_16517106_11484965983.png
[dino] extracting: trevi_fountain_16517106_11484965983.png
[dino] cached: trevi_fountain_16517106_11484965983.png
[dino] image 8/75: trevi_fountain_16771025_6187661240.png
[dino] extracting: trevi_fountain_16771025_6187661240.png
[dino] cached: trevi_fountain_16771025_6187661240.png
[dino] image 9/75: trevi_fountain_17378230_8657377873.png
[dino] extracting: trevi_fountain_17378230_8657377873.png
[dino] cached: trevi_fountain_17378230_8657377873.png
[dino] image 10/75: trevi_fountain_17750259_5579050866.png
[dino] extracting: trevi_fountain_17750259_5579050866.png
[dino] cached: trevi_fountain_17750259_5579050866.png
[dino] image 11/75: trevi_fountain_17804574_3525103748.png
[dino] extracting: trevi_fountain_17804574_3525103748.png
[dino] cached: trevi_fountain_17804574_3525103748.png
[dino] image 12/75: trevi_fountain_17973182_5956257468.png
[dino] extracting: trevi_fountain_17973182_5956257468.png
[dino] cached: trevi_fountain_17973182_5956257468.png
[dino] image 13/75: trevi_fountain_18865921_5109712344.png
[dino] extracting: trevi_fountain_18865921_5109712344.png
[dino] cached: trevi_fountain_18865921_5109712344.png
[dino] image 14/75: trevi_fountain_19939802_5963665770.png
[dino] extracting: trevi_fountain_19939802_5963665770.png
[dino] cached: trevi_fountain_19939802_5963665770.png
[dino] image 15/75: trevi_fountain_21017479_3693575843.png
[dino] extracting: trevi_fountain_21017479_3693575843.png
[dino] cached: trevi_fountain_21017479_3693575843.png
[dino] image 16/75: trevi_fountain_21324671_251787492.png
[dino] extracting: trevi_fountain_21324671_251787492.png
[dino] cached: trevi_fountain_21324671_251787492.png
[dino] image 17/75: trevi_fountain_22494549_5871994022.png
[dino] extracting: trevi_fountain_22494549_5871994022.png
[dino] cached: trevi_fountain_22494549_5871994022.png
[dino] image 18/75: trevi_fountain_22555231_8007352373.png
[dino] extracting: trevi_fountain_22555231_8007352373.png
[dino] cached: trevi_fountain_22555231_8007352373.png
[dino] image 19/75: trevi_fountain_26921609_5411058517.png
[dino] extracting: trevi_fountain_26921609_5411058517.png
[dino] cached: trevi_fountain_26921609_5411058517.png
[dino] image 20/75: trevi_fountain_27009206_5185352408.png
[dino] extracting: trevi_fountain_27009206_5185352408.png
[dino] cached: trevi_fountain_27009206_5185352408.png
[dino] image 21/75: trevi_fountain_29250228_5522743340.png
[dino] extracting: trevi_fountain_29250228_5522743340.png
[dino] cached: trevi_fountain_29250228_5522743340.png
[dino] image 22/75: trevi_fountain_29511430_5519433926.png
[dino] extracting: trevi_fountain_29511430_5519433926.png
[dino] cached: trevi_fountain_29511430_5519433926.png
[dino] image 23/75: trevi_fountain_30002765_4759346847.png
[dino] extracting: trevi_fountain_30002765_4759346847.png
[dino] cached: trevi_fountain_30002765_4759346847.png
[dino] image 24/75: trevi_fountain_30069642_3966141600.png
[dino] extracting: trevi_fountain_30069642_3966141600.png
[dino] cached: trevi_fountain_30069642_3966141600.png
[dino] image 25/75: trevi_fountain_30910735_201249046.png
[dino] extracting: trevi_fountain_30910735_201249046.png
[dino] cached: trevi_fountain_30910735_201249046.png
[dino] image 26/75: trevi_fountain_33816922_8591444000.png
[dino] extracting: trevi_fountain_33816922_8591444000.png
[dino] cached: trevi_fountain_33816922_8591444000.png
[dino] image 27/75: trevi_fountain_34630714_3685665828.png
[dino] extracting: trevi_fountain_34630714_3685665828.png
[dino] cached: trevi_fountain_34630714_3685665828.png
[dino] image 28/75: trevi_fountain_38993702_4733402071.png
[dino] extracting: trevi_fountain_38993702_4733402071.png
[dino] cached: trevi_fountain_38993702_4733402071.png
[dino] image 29/75: trevi_fountain_40184297_2989394429.png
[dino] extracting: trevi_fountain_40184297_2989394429.png
[dino] cached: trevi_fountain_40184297_2989394429.png
[dino] image 30/75: trevi_fountain_41815199_3578791286.png
[dino] extracting: trevi_fountain_41815199_3578791286.png
[dino] cached: trevi_fountain_41815199_3578791286.png
[dino] image 31/75: trevi_fountain_42098841_2972162031.png
[dino] extracting: trevi_fountain_42098841_2972162031.png
[dino] cached: trevi_fountain_42098841_2972162031.png
[dino] image 32/75: trevi_fountain_43321508_5715952972.png
[dino] extracting: trevi_fountain_43321508_5715952972.png
[dino] cached: trevi_fountain_43321508_5715952972.png
[dino] image 33/75: trevi_fountain_48230932_8038671426.png
[dino] extracting: trevi_fountain_48230932_8038671426.png
[dino] cached: trevi_fountain_48230932_8038671426.png
[dino] image 34/75: trevi_fountain_50357199_8205859052.png
[dino] extracting: trevi_fountain_50357199_8205859052.png
[dino] cached: trevi_fountain_50357199_8205859052.png
[dino] image 35/75: trevi_fountain_52144216_2711106071.png
[dino] extracting: trevi_fountain_52144216_2711106071.png
[dino] cached: trevi_fountain_52144216_2711106071.png
[dino] image 36/75: trevi_fountain_54470469_2296508341.png
[dino] extracting: trevi_fountain_54470469_2296508341.png
[dino] cached: trevi_fountain_54470469_2296508341.png
[dino] image 37/75: trevi_fountain_55838538_4636348360.png
[dino] extracting: trevi_fountain_55838538_4636348360.png
[dino] cached: trevi_fountain_55838538_4636348360.png
[dino] image 38/75: trevi_fountain_56026722_4376692497.png
[dino] extracting: trevi_fountain_56026722_4376692497.png
[dino] cached: trevi_fountain_56026722_4376692497.png
[dino] image 39/75: trevi_fountain_56493755_3454995877.png
[dino] extracting: trevi_fountain_56493755_3454995877.png
[dino] cached: trevi_fountain_56493755_3454995877.png
[dino] image 40/75: trevi_fountain_58525833_5956866479.png
[dino] extracting: trevi_fountain_58525833_5956866479.png
[dino] cached: trevi_fountain_58525833_5956866479.png
[dino] image 41/75: trevi_fountain_58732203_2711105477.png
[dino] extracting: trevi_fountain_58732203_2711105477.png
[dino] cached: trevi_fountain_58732203_2711105477.png
[dino] image 42/75: trevi_fountain_59883665_3581996971.png
[dino] extracting: trevi_fountain_59883665_3581996971.png
[dino] cached: trevi_fountain_59883665_3581996971.png
[dino] image 43/75: trevi_fountain_64273020_5411668132.png
[dino] extracting: trevi_fountain_64273020_5411668132.png
[dino] cached: trevi_fountain_64273020_5411668132.png
[dino] image 44/75: trevi_fountain_66347814_2029982255.png
[dino] extracting: trevi_fountain_66347814_2029982255.png
[dino] cached: trevi_fountain_66347814_2029982255.png
[dino] image 45/75: trevi_fountain_66677085_4725569846.png
[dino] extracting: trevi_fountain_66677085_4725569846.png
[dino] cached: trevi_fountain_66677085_4725569846.png
[dino] image 46/75: trevi_fountain_69481877_5327669439.png
[dino] extracting: trevi_fountain_69481877_5327669439.png
[dino] cached: trevi_fountain_69481877_5327669439.png
[dino] image 47/75: trevi_fountain_70315674_7178465185.png
[dino] extracting: trevi_fountain_70315674_7178465185.png
[dino] cached: trevi_fountain_70315674_7178465185.png
[dino] image 48/75: trevi_fountain_71421235_8100441323.png
[dino] extracting: trevi_fountain_71421235_8100441323.png
[dino] cached: trevi_fountain_71421235_8100441323.png
[dino] image 49/75: trevi_fountain_72669213_5987184866.png
[dino] extracting: trevi_fountain_72669213_5987184866.png
[dino] cached: trevi_fountain_72669213_5987184866.png
[dino] image 50/75: trevi_fountain_73284018_2156414038.png
[dino] extracting: trevi_fountain_73284018_2156414038.png
[dino] cached: trevi_fountain_73284018_2156414038.png
[dino] image 51/75: trevi_fountain_74305025_425098856.png
[dino] extracting: trevi_fountain_74305025_425098856.png
[dino] cached: trevi_fountain_74305025_425098856.png
[dino] image 52/75: trevi_fountain_75017867_5746101695.png
[dino] extracting: trevi_fountain_75017867_5746101695.png
[dino] cached: trevi_fountain_75017867_5746101695.png
[dino] image 53/75: trevi_fountain_75810419_3515709926.png
[dino] extracting: trevi_fountain_75810419_3515709926.png
[dino] cached: trevi_fountain_75810419_3515709926.png
[dino] image 54/75: trevi_fountain_78010545_349314185.png
[dino] extracting: trevi_fountain_78010545_349314185.png
[dino] cached: trevi_fountain_78010545_349314185.png
[dino] image 55/75: trevi_fountain_78723734_3158991011.png
[dino] extracting: trevi_fountain_78723734_3158991011.png
[dino] cached: trevi_fountain_78723734_3158991011.png
[dino] image 56/75: trevi_fountain_78842056_325218062.png
[dino] extracting: trevi_fountain_78842056_325218062.png
[dino] cached: trevi_fountain_78842056_325218062.png
[dino] image 57/75: trevi_fountain_79598868_8555774052.png
[dino] extracting: trevi_fountain_79598868_8555774052.png
[dino] cached: trevi_fountain_79598868_8555774052.png
[dino] image 58/75: trevi_fountain_80167621_5886522855.png
[dino] extracting: trevi_fountain_80167621_5886522855.png
[dino] cached: trevi_fountain_80167621_5886522855.png
[dino] image 59/75: trevi_fountain_81409989_5495330211.png
[dino] extracting: trevi_fountain_81409989_5495330211.png
[dino] cached: trevi_fountain_81409989_5495330211.png
[dino] image 60/75: trevi_fountain_84357746_4061156508.png
[dino] extracting: trevi_fountain_84357746_4061156508.png
[dino] cached: trevi_fountain_84357746_4061156508.png
[dino] image 61/75: trevi_fountain_85397053_1435622623.png
[dino] extracting: trevi_fountain_85397053_1435622623.png
[dino] cached: trevi_fountain_85397053_1435622623.png
[dino] image 62/75: trevi_fountain_86451018_5200654015.png
[dino] extracting: trevi_fountain_86451018_5200654015.png
[dino] cached: trevi_fountain_86451018_5200654015.png
[dino] image 63/75: trevi_fountain_89086898_3494993799.png
[dino] extracting: trevi_fountain_89086898_3494993799.png
[dino] cached: trevi_fountain_89086898_3494993799.png
[dino] image 64/75: trevi_fountain_90077341_5746101059.png
[dino] extracting: trevi_fountain_90077341_5746101059.png
[dino] cached: trevi_fountain_90077341_5746101059.png
[dino] image 65/75: trevi_fountain_90669518_8321386929.png
[dino] extracting: trevi_fountain_90669518_8321386929.png
[dino] cached: trevi_fountain_90669518_8321386929.png
[dino] image 66/75: trevi_fountain_91266839_729663994.png
[dino] extracting: trevi_fountain_91266839_729663994.png
[dino] cached: trevi_fountain_91266839_729663994.png
[dino] image 67/75: trevi_fountain_91729188_430652744.png
[dino] extracting: trevi_fountain_91729188_430652744.png
[dino] cached: trevi_fountain_91729188_430652744.png
[dino] image 68/75: trevi_fountain_92808638_88785341.png
[dino] extracting: trevi_fountain_92808638_88785341.png
[dino] cached: trevi_fountain_92808638_88785341.png
[dino] image 69/75: trevi_fountain_93831605_13948911711.png
[dino] extracting: trevi_fountain_93831605_13948911711.png
[dino] cached: trevi_fountain_93831605_13948911711.png
[dino] image 70/75: trevi_fountain_94682384_4342842330.png
[dino] extracting: trevi_fountain_94682384_4342842330.png
[dino] cached: trevi_fountain_94682384_4342842330.png
[dino] image 71/75: trevi_fountain_95794971_4901889397.png
[dino] extracting: trevi_fountain_95794971_4901889397.png
[dino] cached: trevi_fountain_95794971_4901889397.png
[dino] image 72/75: trevi_fountain_96647518_7739315718.png
[dino] extracting: trevi_fountain_96647518_7739315718.png
[dino] cached: trevi_fountain_96647518_7739315718.png
[dino] image 73/75: trevi_fountain_98071474_3495805188.png
[dino] extracting: trevi_fountain_98071474_3495805188.png
[dino] cached: trevi_fountain_98071474_3495805188.png
[dino] image 74/75: trevi_fountain_98446525_8467892061.png
[dino] extracting: trevi_fountain_98446525_8467892061.png
[dino] cached: trevi_fountain_98446525_8467892061.png
[dino] image 75/75: trevi_fountain_99804374_8024711160.png
[dino] extracting: trevi_fountain_99804374_8024711160.png
[dino] cached: trevi_fountain_99804374_8024711160.png
[dino] matching pairs=575 (RANSAC)...
[dino] pair 25/575: trevi_fountain_01241225_4293371290.png ↔ trevi_fountain_75017867_5746101695.png (inliers=91)
[dino] pair 50/575: trevi_fountain_09071644_2938441433.png ↔ trevi_fountain_73284018_2156414038.png (inliers=32)
[dino] pair 75/575: trevi_fountain_15038544_3727504813.png ↔ trevi_fountain_90669518_8321386929.png (inliers=47)
[dino] pair 100/575: trevi_fountain_16771025_6187661240.png ↔ trevi_fountain_90077341_5746101059.png (inliers=35)
[dino] pair 125/575: trevi_fountain_17750259_5579050866.png ↔ trevi_fountain_17804574_3525103748.png (inliers=38)
[dino] pair 150/575: trevi_fountain_17804574_3525103748.png ↔ trevi_fountain_43321508_5715952972.png (inliers=58)
[dino] pair 175/575: trevi_fountain_18865921_5109712344.png ↔ trevi_fountain_30002765_4759346847.png (inliers=38)
[dino] pair 200/575: trevi_fountain_19939802_5963665770.png ↔ trevi_fountain_29250228_5522743340.png (inliers=87)
[dino] pair 225/575: trevi_fountain_21324671_251787492.png ↔ trevi_fountain_54470469_2296508341.png (inliers=76)
[dino] pair 250/575: trevi_fountain_22555231_8007352373.png ↔ trevi_fountain_95794971_4901889397.png (inliers=31)
[dino] pair 275/575: trevi_fountain_29250228_5522743340.png ↔ trevi_fountain_59883665_3581996971.png (inliers=39)
[dino] pair 300/575: trevi_fountain_30002765_4759346847.png ↔ trevi_fountain_93831605_13948911711.png (inliers=63)
[dino] pair 325/575: trevi_fountain_33816922_8591444000.png ↔ trevi_fountain_66347814_2029982255.png (inliers=47)
[dino] pair 350/575: trevi_fountain_34630714_3685665828.png ↔ trevi_fountain_81409989_5495330211.png (inliers=50)
[dino] pair 375/575: trevi_fountain_40184297_2989394429.png ↔ trevi_fountain_52144216_2711106071.png (inliers=45)
[dino] pair 400/575: trevi_fountain_42098841_2972162031.png ↔ trevi_fountain_73284018_2156414038.png (inliers=36)
[dino] pair 425/575: trevi_fountain_48230932_8038671426.png ↔ trevi_fountain_98446525_8467892061.png (inliers=14 < min_inliers=15)
[dino] pair 450/575: trevi_fountain_55838538_4636348360.png ↔ trevi_fountain_93831605_13948911711.png (inliers=57)
[dino] pair 475/575: trevi_fountain_58732203_2711105477.png ↔ trevi_fountain_91729188_430652744.png (inliers=33)
[dino] pair 500/575: trevi_fountain_66677085_4725569846.png ↔ trevi_fountain_80167621_5886522855.png (inliers=65)
[dino] pair 525/575: trevi_fountain_73284018_2156414038.png ↔ trevi_fountain_96647518_7739315718.png (inliers=20)
[dino] pair 550/575: trevi_fountain_78723734_3158991011.png ↔ trevi_fountain_96647518_7739315718.png (inliers=23)
[dino] pair 575/575: trevi_fountain_95794971_4901889397.png ↔ trevi_fountain_96647518_7739315718.png (inliers=39)
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0002/colmap_dino.db (images=75 pairs=575 good_pairs=568, min_inliers=15)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0002/colmap_dino.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0002/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0002/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 3 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 2.0 --Mapper.tri_min_angle 1.5 --Mapper.filter_min_tri_angle 1.5 --Mapper.tri_ignore_two_view_tracks 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:15:14.079815     1 incremental_pipeline.cc:264] Loading database
I20251230 15:15:14.719861     1 database_cache.cc:67] Loading rigs...
I20251230 15:15:14.720736     1 database_cache.cc:77]  0 in 0.001s
I20251230 15:15:14.720784     1 database_cache.cc:85] Loading cameras...
I20251230 15:15:14.720914     1 database_cache.cc:103]  75 in 0.000s
I20251230 15:15:14.720934     1 database_cache.cc:111] Loading frames...
I20251230 15:15:14.720945     1 database_cache.cc:126]  0 in 0.000s
I20251230 15:15:14.720949     1 database_cache.cc:134] Loading matches...
I20251230 15:15:15.136529     1 database_cache.cc:139]  568 in 0.416s
I20251230 15:15:15.136610     1 database_cache.cc:155] Loading images...
I20251230 15:15:17.996063     1 database_cache.cc:239]  75 in 2.860s (connected 75)
I20251230 15:15:17.996204     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:15:18.004890     1 database_cache.cc:277]  in 0.009s (ignored 0)
I20251230 15:15:18.005626     1 timer.cc:90] Elapsed time: 0.063 [minutes]
I20251230 15:15:18.017455     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:18.175915     1 incremental_pipeline.cc:335] Registering initial image pair #67 and #10
I20251230 15:15:18.534412     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:20.878929     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:20.880419     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:20.892051     1 incremental_pipeline.cc:335] Registering initial image pair #67 and #69
I20251230 15:15:20.893052     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:20.934696     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:20.935691     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:20.943380     1 incremental_pipeline.cc:335] Registering initial image pair #27 and #34
I20251230 15:15:20.944211     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:20.968713     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:20.969657     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:20.975780     1 incremental_pipeline.cc:335] Registering initial image pair #28 and #44
I20251230 15:15:20.976568     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:21.255070     1 incremental_pipeline.cc:597] Keeping successful reconstruction
I20251230 15:15:21.284548     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:21.320129     1 incremental_pipeline.cc:335] Registering initial image pair #27 and #69
I20251230 15:15:21.320751     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:21.339658     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:21.340580     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:21.373818     1 incremental_pipeline.cc:335] Registering initial image pair #49 and #67
I20251230 15:15:21.374723     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:21.391427     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:21.392485     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:21.402645     1 incremental_pipeline.cc:335] Registering initial image pair #49 and #22
I20251230 15:15:21.403074     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:21.410123     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:21.411727     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:21.420298     1 incremental_pipeline.cc:335] Registering initial image pair #31 and #1
I20251230 15:15:21.420845     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:21.604449     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:15:21.605849     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:21.621476     1 incremental_pipeline.cc:335] Registering initial image pair #31 and #4
I20251230 15:15:21.622054     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:15:21.622139     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:15:21.622154     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:15:21.622195     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:21.623248     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:21.652659     1 incremental_pipeline.cc:335] Registering initial image pair #36 and #22
I20251230 15:15:21.653211     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:21.660851     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:21.662731     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:21.676343     1 incremental_pipeline.cc:335] Registering initial image pair #36 and #75
I20251230 15:15:21.676900     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:21.851756     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:15:21.853219     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:21.883821     1 incremental_pipeline.cc:335] Registering initial image pair #52 and #18
I20251230 15:15:21.884259     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.116606     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:15:22.118108     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.133175     1 incremental_pipeline.cc:335] Registering initial image pair #52 and #45
I20251230 15:15:22.133553     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.137614     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.138940     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.150674     1 incremental_pipeline.cc:335] Registering initial image pair #9 and #60
I20251230 15:15:22.151036     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:15:22.151091     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:15:22.151099     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:15:22.151130     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.152029     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.168387     1 incremental_pipeline.cc:335] Registering initial image pair #10 and #11
I20251230 15:15:22.168769     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.177594     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.178963     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.192863     1 incremental_pipeline.cc:335] Registering initial image pair #9 and #2
I20251230 15:15:22.193414     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.202373     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.203753     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.222667     1 incremental_pipeline.cc:335] Registering initial image pair #29 and #31
I20251230 15:15:22.223145     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.230409     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.231676     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.259545     1 incremental_pipeline.cc:335] Registering initial image pair #29 and #49
I20251230 15:15:22.259950     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:15:22.260013     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:15:22.260023     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:15:22.260056     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.261431     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.281682     1 incremental_pipeline.cc:335] Registering initial image pair #64 and #8
I20251230 15:15:22.282020     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.289803     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.291064     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.306967     1 incremental_pipeline.cc:335] Registering initial image pair #64 and #45
I20251230 15:15:22.307304     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.310693     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.311774     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.326192     1 incremental_pipeline.cc:335] Registering initial image pair #13 and #27
I20251230 15:15:22.326555     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.329805     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.330932     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.375207     1 incremental_pipeline.cc:335] Registering initial image pair #13 and #16
I20251230 15:15:22.375661     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.377332     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.378546     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.399180     1 incremental_pipeline.cc:335] Registering initial image pair #2 and #13
I20251230 15:15:22.399510     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.406028     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.407097     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.419524     1 incremental_pipeline.cc:335] Registering initial image pair #26 and #49
I20251230 15:15:22.419878     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.427860     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.428895     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.436851     1 incremental_pipeline.cc:335] Registering initial image pair #26 and #68
I20251230 15:15:22.437206     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:15:22.437266     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:15:22.437274     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:15:22.437311     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.438476     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.448240     1 incremental_pipeline.cc:335] Registering initial image pair #11 and #71
I20251230 15:15:22.448603     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.455685     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.456681     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.477378     1 incremental_pipeline.cc:335] Registering initial image pair #53 and #31
I20251230 15:15:22.477732     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.478041     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.479082     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.489530     1 incremental_pipeline.cc:335] Registering initial image pair #53 and #17
I20251230 15:15:22.489862     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.495926     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.496919     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.533281     1 incremental_pipeline.cc:335] Registering initial image pair #66 and #22
I20251230 15:15:22.533813     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.664733     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:15:22.665745     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.681296     1 incremental_pipeline.cc:335] Registering initial image pair #59 and #31
I20251230 15:15:22.681715     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.682276     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.683259     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.700695     1 incremental_pipeline.cc:335] Registering initial image pair #59 and #57
I20251230 15:15:22.701017     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:15:22.701079     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:15:22.701090     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:15:22.701135     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.702209     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.725078     1 incremental_pipeline.cc:335] Registering initial image pair #66 and #36
I20251230 15:15:22.725454     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.725742     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.726737     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.746518     1 incremental_pipeline.cc:335] Registering initial image pair #65 and #57
I20251230 15:15:22.747015     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:15:22.747117     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:15:22.747129     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:15:22.747175     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.748832     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.783401     1 incremental_pipeline.cc:335] Registering initial image pair #65 and #20
I20251230 15:15:22.783725     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.791179     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.792688     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.815402     1 incremental_pipeline.cc:335] Registering initial image pair #40 and #46
I20251230 15:15:22.815763     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:15:22.815822     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:15:22.815830     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:15:22.815872     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.817358     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.838963     1 incremental_pipeline.cc:335] Registering initial image pair #41 and #52
I20251230 15:15:22.839377     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.845798     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.847054     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.876904     1 incremental_pipeline.cc:335] Registering initial image pair #41 and #5
I20251230 15:15:22.877218     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.886644     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.887706     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.900305     1 incremental_pipeline.cc:335] Registering initial image pair #43 and #71
I20251230 15:15:22.900633     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.901803     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.902786     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.912968     1 incremental_pipeline.cc:335] Registering initial image pair #3 and #15
I20251230 15:15:22.913360     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.919865     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.920949     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.939430     1 incremental_pipeline.cc:335] Registering initial image pair #3 and #20
I20251230 15:15:22.939790     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.944553     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.945694     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:22.964898     1 incremental_pipeline.cc:335] Registering initial image pair #50 and #31
I20251230 15:15:22.965389     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:22.969738     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:22.971131     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:23.003382     1 incremental_pipeline.cc:335] Registering initial image pair #50 and #10
I20251230 15:15:23.003813     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:23.007745     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:23.008975     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:15:23.032392     1 incremental_pipeline.cc:335] Registering initial image pair #23 and #57
I20251230 15:15:23.032755     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:15:23.033077     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:15:23.034085     1 incremental_pipeline.cc:311] Finding good initial image pair

[ok] pt_sacrecoeur_trevi_tajmahal/cluster_0002: sparse model ready at /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0002/sparse/0
[cluster] 6/8: pt_sacrecoeur_trevi_tajmahal/cluster_0003
[run] pt_sacrecoeur_trevi_tajmahal/cluster_0003: images=74 matcher=dino
[dino] build db=/home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0003/colmap_dino.db images=74 pairing=auto topk=10
[dino] cache_dir=cache/dino_features
[dino] model=facebook/dinov2-small layer=last max_side=512 fp16=True
[dino] matcher: keypoints=patch max_keypoints=2048 min_similarity=0.75 min_inliers=15
[warn] --single-camera requested but image sizes differ [(501, 501), (503, 375), (518, 381), (603, 809), (651, 989), (666, 999), (676, 1014), (683, 1027), (687, 1050), (688, 1045), (690, 1059), (694, 1058), (694, 1094), (695, 1069), (729, 1050), (752, 1003), (767, 1025), (769, 1028), (771, 1032), (773, 1038), (774, 1040), (774, 1041), (775, 1043), (779, 1055), (780, 1055), (780, 1056), (780, 1063), (781, 1059), (783, 1063), (784, 1067), (785, 1068), (787, 1074), (794, 1094), (815, 605), (822, 608), (888, 888), (938, 694), (990, 661), (991, 743), (1008, 672), (1009, 757), (1012, 759), (1015, 761), (1023, 767), (1024, 680), (1024, 767), (1026, 768), (1033, 688), (1034, 771), (1035, 772), (1037, 686), (1038, 686), (1045, 776), (1046, 776), (1049, 685), (1049, 758), (1049, 777), (1050, 778), (1052, 778), (1053, 779), (1057, 780), (1059, 692), (1064, 783), (1066, 783), (1066, 784), (1070, 694), (1074, 787), (1078, 788), (1082, 790), (1083, 695)]; using per-image cameras.
[dino] using preloaded model on device=cuda patch=14
[dino] image 1/74: sacre_coeur_02928139_3448003521.png
[dino] extracting: sacre_coeur_02928139_3448003521.png
[dino] cached: sacre_coeur_02928139_3448003521.png
[dino] image 2/74: sacre_coeur_04739785_8198592553.png
[dino] extracting: sacre_coeur_04739785_8198592553.png
[dino] cached: sacre_coeur_04739785_8198592553.png
[dino] image 3/74: sacre_coeur_04822190_12621366523.png
[dino] extracting: sacre_coeur_04822190_12621366523.png
[dino] cached: sacre_coeur_04822190_12621366523.png
[dino] image 4/74: sacre_coeur_10474405_6093717701.png
[dino] extracting: sacre_coeur_10474405_6093717701.png
[dino] cached: sacre_coeur_10474405_6093717701.png
[dino] image 5/74: sacre_coeur_11626754_2718827730.png
[dino] extracting: sacre_coeur_11626754_2718827730.png
[dino] cached: sacre_coeur_11626754_2718827730.png
[dino] image 6/74: sacre_coeur_16385535_4660789205.png
[dino] extracting: sacre_coeur_16385535_4660789205.png
[dino] cached: sacre_coeur_16385535_4660789205.png
[dino] image 7/74: sacre_coeur_16537684_4545274148.png
[dino] extracting: sacre_coeur_16537684_4545274148.png
[dino] cached: sacre_coeur_16537684_4545274148.png
[dino] image 8/74: sacre_coeur_16776129_4239663609.png
[dino] extracting: sacre_coeur_16776129_4239663609.png
[dino] cached: sacre_coeur_16776129_4239663609.png
[dino] image 9/74: sacre_coeur_16971221_7856309770.png
[dino] extracting: sacre_coeur_16971221_7856309770.png
[dino] cached: sacre_coeur_16971221_7856309770.png
[dino] image 10/74: sacre_coeur_18725380_2402129328.png
[dino] extracting: sacre_coeur_18725380_2402129328.png
[dino] cached: sacre_coeur_18725380_2402129328.png
[dino] image 11/74: sacre_coeur_23327088_8208333914.png
[dino] extracting: sacre_coeur_23327088_8208333914.png
[dino] cached: sacre_coeur_23327088_8208333914.png
[dino] image 12/74: sacre_coeur_24292909_11972893303.png
[dino] extracting: sacre_coeur_24292909_11972893303.png
[dino] cached: sacre_coeur_24292909_11972893303.png
[dino] image 13/74: sacre_coeur_28088482_1061487806.png
[dino] extracting: sacre_coeur_28088482_1061487806.png
[dino] cached: sacre_coeur_28088482_1061487806.png
[dino] image 14/74: sacre_coeur_30642459_5864476232.png
[dino] extracting: sacre_coeur_30642459_5864476232.png
[dino] cached: sacre_coeur_30642459_5864476232.png
[dino] image 15/74: sacre_coeur_32069695_13023252634.png
[dino] extracting: sacre_coeur_32069695_13023252634.png
[dino] cached: sacre_coeur_32069695_13023252634.png
[dino] image 16/74: sacre_coeur_32086795_402359870.png
[dino] extracting: sacre_coeur_32086795_402359870.png
[dino] cached: sacre_coeur_32086795_402359870.png
[dino] image 17/74: sacre_coeur_32188921_4453876221.png
[dino] extracting: sacre_coeur_32188921_4453876221.png
[dino] cached: sacre_coeur_32188921_4453876221.png
[dino] image 18/74: sacre_coeur_33340964_112626481.png
[dino] extracting: sacre_coeur_33340964_112626481.png
[dino] cached: sacre_coeur_33340964_112626481.png
[dino] image 19/74: sacre_coeur_34264811_99184810.png
[dino] extracting: sacre_coeur_34264811_99184810.png
[dino] cached: sacre_coeur_34264811_99184810.png
[dino] image 20/74: sacre_coeur_34904068_5083153.png
[dino] extracting: sacre_coeur_34904068_5083153.png
[dino] cached: sacre_coeur_34904068_5083153.png
[dino] image 21/74: sacre_coeur_35905283_32603557.png
[dino] extracting: sacre_coeur_35905283_32603557.png
[dino] cached: sacre_coeur_35905283_32603557.png
[dino] image 22/74: sacre_coeur_37175111_6635304477.png
[dino] extracting: sacre_coeur_37175111_6635304477.png
[dino] cached: sacre_coeur_37175111_6635304477.png
[dino] image 23/74: sacre_coeur_38755762_4239668423.png
[dino] extracting: sacre_coeur_38755762_4239668423.png
[dino] cached: sacre_coeur_38755762_4239668423.png
[dino] image 24/74: sacre_coeur_39172134_3155998144.png
[dino] extracting: sacre_coeur_39172134_3155998144.png
[dino] cached: sacre_coeur_39172134_3155998144.png
[dino] image 25/74: sacre_coeur_39702035_1808089104.png
[dino] extracting: sacre_coeur_39702035_1808089104.png
[dino] cached: sacre_coeur_39702035_1808089104.png
[dino] image 26/74: sacre_coeur_39852107_3868092306.png
[dino] extracting: sacre_coeur_39852107_3868092306.png
[dino] cached: sacre_coeur_39852107_3868092306.png
[dino] image 27/74: sacre_coeur_41224690_4580747259.png
[dino] extracting: sacre_coeur_41224690_4580747259.png
[dino] cached: sacre_coeur_41224690_4580747259.png
[dino] image 28/74: sacre_coeur_42287322_536307676.png
[dino] extracting: sacre_coeur_42287322_536307676.png
[dino] cached: sacre_coeur_42287322_536307676.png
[dino] image 29/74: sacre_coeur_45927449_5904684394.png
[dino] extracting: sacre_coeur_45927449_5904684394.png
[dino] cached: sacre_coeur_45927449_5904684394.png
[dino] image 30/74: sacre_coeur_46031506_3822251715.png
[dino] extracting: sacre_coeur_46031506_3822251715.png
[dino] cached: sacre_coeur_46031506_3822251715.png
[dino] image 31/74: sacre_coeur_46459330_5716002401.png
[dino] extracting: sacre_coeur_46459330_5716002401.png
[dino] cached: sacre_coeur_46459330_5716002401.png
[dino] image 32/74: sacre_coeur_47029087_8959697396.png
[dino] extracting: sacre_coeur_47029087_8959697396.png
[dino] cached: sacre_coeur_47029087_8959697396.png
[dino] image 33/74: sacre_coeur_47042061_9637017399.png
[dino] extracting: sacre_coeur_47042061_9637017399.png
[dino] cached: sacre_coeur_47042061_9637017399.png
[dino] image 34/74: sacre_coeur_47788810_3531619701.png
[dino] extracting: sacre_coeur_47788810_3531619701.png
[dino] cached: sacre_coeur_47788810_3531619701.png
[dino] image 35/74: sacre_coeur_48325951_2932818065.png
[dino] extracting: sacre_coeur_48325951_2932818065.png
[dino] cached: sacre_coeur_48325951_2932818065.png
[dino] image 36/74: sacre_coeur_49896012_2400282601.png
[dino] extracting: sacre_coeur_49896012_2400282601.png
[dino] cached: sacre_coeur_49896012_2400282601.png
[dino] image 37/74: sacre_coeur_52914810_3288295639.png
[dino] extracting: sacre_coeur_52914810_3288295639.png
[dino] cached: sacre_coeur_52914810_3288295639.png
[dino] image 38/74: sacre_coeur_55167859_91653543.png
[dino] extracting: sacre_coeur_55167859_91653543.png
[dino] cached: sacre_coeur_55167859_91653543.png
[dino] image 39/74: sacre_coeur_55297752_267282770.png
[dino] extracting: sacre_coeur_55297752_267282770.png
[dino] cached: sacre_coeur_55297752_267282770.png
[dino] image 40/74: sacre_coeur_55640818_3363877988.png
[dino] extracting: sacre_coeur_55640818_3363877988.png
[dino] cached: sacre_coeur_55640818_3363877988.png
[dino] image 41/74: sacre_coeur_55695069_9640098822.png
[dino] extracting: sacre_coeur_55695069_9640098822.png
[dino] cached: sacre_coeur_55695069_9640098822.png
[dino] image 42/74: sacre_coeur_61531052_7402696624.png
[dino] extracting: sacre_coeur_61531052_7402696624.png
[dino] cached: sacre_coeur_61531052_7402696624.png
[dino] image 43/74: sacre_coeur_66573940_9624143830.png
[dino] extracting: sacre_coeur_66573940_9624143830.png
[dino] cached: sacre_coeur_66573940_9624143830.png
[dino] image 44/74: sacre_coeur_67466492_5056065534.png
[dino] extracting: sacre_coeur_67466492_5056065534.png
[dino] cached: sacre_coeur_67466492_5056065534.png
[dino] image 45/74: sacre_coeur_68663909_1356782012.png
[dino] extracting: sacre_coeur_68663909_1356782012.png
[dino] cached: sacre_coeur_68663909_1356782012.png
[dino] image 46/74: sacre_coeur_68688218_4738908453.png
[dino] extracting: sacre_coeur_68688218_4738908453.png
[dino] cached: sacre_coeur_68688218_4738908453.png
[dino] image 47/74: sacre_coeur_69399539_4178098151.png
[dino] extracting: sacre_coeur_69399539_4178098151.png
[dino] cached: sacre_coeur_69399539_4178098151.png
[dino] image 48/74: sacre_coeur_70116109_2697195876.png
[dino] extracting: sacre_coeur_70116109_2697195876.png
[dino] cached: sacre_coeur_70116109_2697195876.png
[dino] image 49/74: sacre_coeur_70118605_5991576631.png
[dino] extracting: sacre_coeur_70118605_5991576631.png
[dino] cached: sacre_coeur_70118605_5991576631.png
[dino] image 50/74: sacre_coeur_70724808_2779990339.png
[dino] extracting: sacre_coeur_70724808_2779990339.png
[dino] cached: sacre_coeur_70724808_2779990339.png
[dino] image 51/74: sacre_coeur_70970334_5790897082.png
[dino] extracting: sacre_coeur_70970334_5790897082.png
[dino] cached: sacre_coeur_70970334_5790897082.png
[dino] image 52/74: sacre_coeur_71955478_140210696.png
[dino] extracting: sacre_coeur_71955478_140210696.png
[dino] cached: sacre_coeur_71955478_140210696.png
[dino] image 53/74: sacre_coeur_73084286_312927075.png
[dino] extracting: sacre_coeur_73084286_312927075.png
[dino] cached: sacre_coeur_73084286_312927075.png
[dino] image 54/74: sacre_coeur_75030977_10341125684.png
[dino] extracting: sacre_coeur_75030977_10341125684.png
[dino] cached: sacre_coeur_75030977_10341125684.png
[dino] image 55/74: sacre_coeur_75716321_3698743515.png
[dino] extracting: sacre_coeur_75716321_3698743515.png
[dino] cached: sacre_coeur_75716321_3698743515.png
[dino] image 56/74: sacre_coeur_76611857_9600863579.png
[dino] extracting: sacre_coeur_76611857_9600863579.png
[dino] cached: sacre_coeur_76611857_9600863579.png
[dino] image 57/74: sacre_coeur_77299481_4479618965.png
[dino] extracting: sacre_coeur_77299481_4479618965.png
[dino] cached: sacre_coeur_77299481_4479618965.png
[dino] image 58/74: sacre_coeur_79500596_4830716729.png
[dino] extracting: sacre_coeur_79500596_4830716729.png
[dino] cached: sacre_coeur_79500596_4830716729.png
[dino] image 59/74: sacre_coeur_80691366_2623658065.png
[dino] extracting: sacre_coeur_80691366_2623658065.png
[dino] cached: sacre_coeur_80691366_2623658065.png
[dino] image 60/74: sacre_coeur_81282261_3885204620.png
[dino] extracting: sacre_coeur_81282261_3885204620.png
[dino] cached: sacre_coeur_81282261_3885204620.png
[dino] image 61/74: sacre_coeur_81935357_9658163122.png
[dino] extracting: sacre_coeur_81935357_9658163122.png
[dino] cached: sacre_coeur_81935357_9658163122.png
[dino] image 62/74: sacre_coeur_82410562_10997050704.png
[dino] extracting: sacre_coeur_82410562_10997050704.png
[dino] cached: sacre_coeur_82410562_10997050704.png
[dino] image 63/74: sacre_coeur_85164542_170630708.png
[dino] extracting: sacre_coeur_85164542_170630708.png
[dino] cached: sacre_coeur_85164542_170630708.png
[dino] image 64/74: sacre_coeur_86731151_442052253.png
[dino] extracting: sacre_coeur_86731151_442052253.png
[dino] cached: sacre_coeur_86731151_442052253.png
[dino] image 65/74: sacre_coeur_87446292_3971192822.png
[dino] extracting: sacre_coeur_87446292_3971192822.png
[dino] cached: sacre_coeur_87446292_3971192822.png
[dino] image 66/74: sacre_coeur_88008039_6208734830.png
[dino] extracting: sacre_coeur_88008039_6208734830.png
[dino] cached: sacre_coeur_88008039_6208734830.png
[dino] image 67/74: sacre_coeur_90467261_5816977333.png
[dino] extracting: sacre_coeur_90467261_5816977333.png
[dino] cached: sacre_coeur_90467261_5816977333.png
[dino] image 68/74: sacre_coeur_90517919_4394638107.png
[dino] extracting: sacre_coeur_90517919_4394638107.png
[dino] cached: sacre_coeur_90517919_4394638107.png
[dino] image 69/74: sacre_coeur_91139284_7856526282.png
[dino] extracting: sacre_coeur_91139284_7856526282.png
[dino] cached: sacre_coeur_91139284_7856526282.png
[dino] image 70/74: sacre_coeur_91671915_1791174514.png
[dino] extracting: sacre_coeur_91671915_1791174514.png
[dino] cached: sacre_coeur_91671915_1791174514.png
[dino] image 71/74: sacre_coeur_93423882_13476569344.png
[dino] extracting: sacre_coeur_93423882_13476569344.png
[dino] cached: sacre_coeur_93423882_13476569344.png
[dino] image 72/74: sacre_coeur_93638576_44195081.png
[dino] extracting: sacre_coeur_93638576_44195081.png
[dino] cached: sacre_coeur_93638576_44195081.png
[dino] image 73/74: sacre_coeur_95734826_713795234.png
[dino] extracting: sacre_coeur_95734826_713795234.png
[dino] cached: sacre_coeur_95734826_713795234.png
[dino] image 74/74: sacre_coeur_98546957_2200688611.png
[dino] extracting: sacre_coeur_98546957_2200688611.png
[dino] cached: sacre_coeur_98546957_2200688611.png
[dino] matching pairs=529 (RANSAC)...
[dino] pair 25/529: sacre_coeur_04822190_12621366523.png ↔ sacre_coeur_32086795_402359870.png (inliers=22)
[dino] pair 50/529: sacre_coeur_11626754_2718827730.png ↔ sacre_coeur_70970334_5790897082.png (inliers=53)
[dino] pair 75/529: sacre_coeur_16776129_4239663609.png ↔ sacre_coeur_28088482_1061487806.png (inliers=24)
[dino] pair 100/529: sacre_coeur_16776129_4239663609.png ↔ sacre_coeur_85164542_170630708.png (inliers=21)
[dino] pair 125/529: sacre_coeur_18725380_2402129328.png ↔ sacre_coeur_87446292_3971192822.png (inliers=47)
[dino] pair 150/529: sacre_coeur_28088482_1061487806.png ↔ sacre_coeur_52914810_3288295639.png (inliers=37)
[dino] pair 175/529: sacre_coeur_32069695_13023252634.png ↔ sacre_coeur_68663909_1356782012.png (inliers=53)
[dino] pair 200/529: sacre_coeur_33340964_112626481.png ↔ sacre_coeur_39172134_3155998144.png (inliers=87)
[dino] pair 225/529: sacre_coeur_34264811_99184810.png ↔ sacre_coeur_73084286_312927075.png (inliers=62)
[dino] pair 250/529: sacre_coeur_35905283_32603557.png ↔ sacre_coeur_77299481_4479618965.png (inliers=24)
[dino] pair 275/529: sacre_coeur_38755762_4239668423.png ↔ sacre_coeur_61531052_7402696624.png (inliers=26)
[dino] pair 300/529: sacre_coeur_39852107_3868092306.png ↔ sacre_coeur_75030977_10341125684.png (inliers=26)
[dino] pair 325/529: sacre_coeur_42287322_536307676.png ↔ sacre_coeur_87446292_3971192822.png (inliers=76)
[dino] pair 350/529: sacre_coeur_46459330_5716002401.png ↔ sacre_coeur_55167859_91653543.png (inliers=76)
[dino] pair 375/529: sacre_coeur_47042061_9637017399.png ↔ sacre_coeur_88008039_6208734830.png (inliers=43)
[dino] pair 400/529: sacre_coeur_52914810_3288295639.png ↔ sacre_coeur_55167859_91653543.png (inliers=70)
[dino] pair 425/529: sacre_coeur_55695069_9640098822.png ↔ sacre_coeur_70118605_5991576631.png (inliers=20)
[dino] pair 450/529: sacre_coeur_68688218_4738908453.png ↔ sacre_coeur_81282261_3885204620.png (inliers=48)
[dino] pair 475/529: sacre_coeur_71955478_140210696.png ↔ sacre_coeur_91671915_1791174514.png (inliers=21)
[dino] pair 500/529: sacre_coeur_79500596_4830716729.png ↔ sacre_coeur_93423882_13476569344.png (inliers=56)
[dino] pair 525/529: sacre_coeur_88008039_6208734830.png ↔ sacre_coeur_98546957_2200688611.png (inliers=83)
[ok] wrote /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0003/colmap_dino.db (images=74 pairs=529 good_pairs=514, min_inliers=15)
+ docker run --rm --gpus all -v /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025:/workspace -w /workspace colmap/colmap:latest colmap mapper --database_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0003/colmap_dino.db --image_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0003/images --output_path outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0003/sparse --Mapper.ba_refine_principal_point 0 --Mapper.min_num_matches 15 --Mapper.min_model_size 3 --Mapper.init_min_num_inliers 15 --Mapper.init_min_tri_angle 2.0 --Mapper.tri_min_angle 1.5 --Mapper.filter_min_tri_angle 1.5 --Mapper.tri_ignore_two_view_tracks 1

==========
== CUDA ==
==========

CUDA Version 12.9.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

I20251230 15:17:55.312337     1 incremental_pipeline.cc:264] Loading database
I20251230 15:17:55.599505     1 database_cache.cc:67] Loading rigs...
I20251230 15:17:55.653944     1 database_cache.cc:77]  0 in 0.055s
I20251230 15:17:55.654031     1 database_cache.cc:85] Loading cameras...
I20251230 15:17:55.803743     1 database_cache.cc:103]  74 in 0.150s
I20251230 15:17:55.803803     1 database_cache.cc:111] Loading frames...
I20251230 15:17:55.803818     1 database_cache.cc:126]  0 in 0.000s
I20251230 15:17:55.803822     1 database_cache.cc:134] Loading matches...
I20251230 15:17:55.805143     1 database_cache.cc:139]  514 in 0.001s
I20251230 15:17:55.805200     1 database_cache.cc:155] Loading images...
I20251230 15:17:55.860088     1 database_cache.cc:239]  74 in 0.055s (connected 74)
I20251230 15:17:55.860206     1 database_cache.cc:250] Building correspondence graph...
I20251230 15:17:55.863490     1 database_cache.cc:277]  in 0.003s (ignored 0)
I20251230 15:17:55.863919     1 timer.cc:90] Elapsed time: 0.009 [minutes]
I20251230 15:17:55.870651     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:55.944355     1 incremental_pipeline.cc:335] Registering initial image pair #53 and #24
I20251230 15:17:55.946118     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.163908     1 incremental_pipeline.cc:439] Registering image #23 (num_reg_frames=2)
I20251230 15:17:56.163975     1 incremental_pipeline.cc:442] => Image sees 39 / 531 points
I20251230 15:17:56.164474     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:17:56.164500     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 15:17:56.182580     1 incremental_pipeline.cc:439] Registering image #23 (num_reg_frames=2)
I20251230 15:17:56.182637     1 incremental_pipeline.cc:442] => Image sees 30 / 531 points
I20251230 15:17:56.183019     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:17:56.183043     1 incremental_pipeline.cc:597] Keeping successful reconstruction
I20251230 15:17:56.184739     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.192360     1 incremental_pipeline.cc:335] Registering initial image pair #8 and #19
I20251230 15:17:56.192998     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.251670     1 incremental_pipeline.cc:439] Registering image #23 (num_reg_frames=2)
I20251230 15:17:56.251729     1 incremental_pipeline.cc:442] => Image sees 35 / 531 points
I20251230 15:17:56.304857     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 15:17:56.354048     1 incremental_pipeline.cc:597] Keeping successful reconstruction
I20251230 15:17:56.356796     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.367656     1 incremental_pipeline.cc:335] Registering initial image pair #37 and #58
I20251230 15:17:56.368171     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.383414     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:56.388532     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.396023     1 incremental_pipeline.cc:335] Registering initial image pair #37 and #54
I20251230 15:17:56.396454     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.424666     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:17:56.425916     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.431285     1 incremental_pipeline.cc:335] Registering initial image pair #60 and #5
I20251230 15:17:56.431841     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.464118     1 incremental_pipeline.cc:439] Registering image #35 (num_reg_frames=2)
I20251230 15:17:56.464180     1 incremental_pipeline.cc:442] => Image sees 45 / 398 points
I20251230 15:17:56.468001     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:17:56.468068     1 incremental_pipeline.cc:439] Registering image #65 (num_reg_frames=2)
I20251230 15:17:56.468083     1 incremental_pipeline.cc:442] => Image sees 32 / 376 points
I20251230 15:17:56.473965     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:17:56.474017     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 15:17:56.474717     1 incremental_pipeline.cc:439] Registering image #35 (num_reg_frames=2)
I20251230 15:17:56.474752     1 incremental_pipeline.cc:442] => Image sees 45 / 398 points
I20251230 15:17:56.480561     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:17:56.480625     1 incremental_pipeline.cc:439] Registering image #65 (num_reg_frames=2)
I20251230 15:17:56.480638     1 incremental_pipeline.cc:442] => Image sees 32 / 376 points
I20251230 15:17:56.485484     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:17:56.485546     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:17:56.486457     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.496310     1 incremental_pipeline.cc:335] Registering initial image pair #60 and #32
I20251230 15:17:56.496763     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.550171     1 incremental_pipeline.cc:439] Registering image #74 (num_reg_frames=2)
I20251230 15:17:56.550230     1 incremental_pipeline.cc:442] => Image sees 48 / 370 points
I20251230 15:17:56.551191     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:17:56.551213     1 incremental_pipeline.cc:439] Registering image #28 (num_reg_frames=2)
I20251230 15:17:56.551219     1 incremental_pipeline.cc:442] => Image sees 37 / 425 points
I20251230 15:17:56.554669     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:17:56.554762     1 incremental_pipeline.cc:439] Registering image #5 (num_reg_frames=2)
I20251230 15:17:56.554781     1 incremental_pipeline.cc:442] => Image sees 31 / 379 points
I20251230 15:17:56.557102     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:17:56.557132     1 incremental_pipeline.cc:439] Registering image #35 (num_reg_frames=2)
I20251230 15:17:56.557143     1 incremental_pipeline.cc:442] => Image sees 30 / 398 points
I20251230 15:17:56.558744     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:17:56.558763     1 incremental_pipeline.cc:43] Retriangulation and Global bundle adjustment
I20251230 15:17:56.577836     1 incremental_pipeline.cc:439] Registering image #74 (num_reg_frames=2)
I20251230 15:17:56.577890     1 incremental_pipeline.cc:442] => Image sees 48 / 370 points
I20251230 15:17:56.579306     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:17:56.579356     1 incremental_pipeline.cc:439] Registering image #28 (num_reg_frames=2)
I20251230 15:17:56.579365     1 incremental_pipeline.cc:442] => Image sees 37 / 425 points
I20251230 15:17:56.583042     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:17:56.583076     1 incremental_pipeline.cc:439] Registering image #5 (num_reg_frames=2)
I20251230 15:17:56.583086     1 incremental_pipeline.cc:442] => Image sees 31 / 379 points
I20251230 15:17:56.584990     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:17:56.585018     1 incremental_pipeline.cc:439] Registering image #35 (num_reg_frames=2)
I20251230 15:17:56.585027     1 incremental_pipeline.cc:442] => Image sees 30 / 398 points
I20251230 15:17:56.586954     1 incremental_pipeline.cc:453] => Could not register, trying another image.
I20251230 15:17:56.586992     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:17:56.587868     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.609939     1 incremental_pipeline.cc:335] Registering initial image pair #63 and #71
I20251230 15:17:56.610257     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:17:56.610316     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:17:56.610340     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:17:56.610380     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:56.611217     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.626452     1 incremental_pipeline.cc:335] Registering initial image pair #63 and #27
I20251230 15:17:56.626797     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.630851     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:56.631742     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.658825     1 incremental_pipeline.cc:335] Registering initial image pair #29 and #39
I20251230 15:17:56.659153     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.659523     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:56.667825     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.683984     1 incremental_pipeline.cc:335] Registering initial image pair #29 and #44
I20251230 15:17:56.684371     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.690053     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:56.691241     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.702646     1 incremental_pipeline.cc:335] Registering initial image pair #65 and #61
I20251230 15:17:56.703007     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.745193     1 incremental_pipeline.cc:592] Discarding reconstruction due to insufficient size
I20251230 15:17:56.746021     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.776302     1 incremental_pipeline.cc:335] Registering initial image pair #66 and #67
I20251230 15:17:56.776593     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.776939     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:56.777802     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.791134     1 incremental_pipeline.cc:335] Registering initial image pair #65 and #70
I20251230 15:17:56.791401     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.798187     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:56.799410     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.809418     1 incremental_pipeline.cc:335] Registering initial image pair #20 and #25
I20251230 15:17:56.809692     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.811203     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:56.812081     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.840948     1 incremental_pipeline.cc:335] Registering initial image pair #20 and #62
I20251230 15:17:56.841210     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:17:56.841264     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:17:56.841270     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:17:56.841300     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:56.842777     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.873432     1 incremental_pipeline.cc:335] Registering initial image pair #18 and #48
I20251230 15:17:56.873697     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:17:56.873759     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:17:56.873768     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:17:56.873804     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:56.874828     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.899647     1 incremental_pipeline.cc:335] Registering initial image pair #18 and #52
I20251230 15:17:56.900117     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.908288     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:56.909755     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.951000     1 incremental_pipeline.cc:335] Registering initial image pair #41 and #15
I20251230 15:17:56.951269     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.954361     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:56.955322     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:56.983172     1 incremental_pipeline.cc:335] Registering initial image pair #41 and #68
I20251230 15:17:56.983430     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:56.983687     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:56.984740     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:57.011004     1 incremental_pipeline.cc:335] Registering initial image pair #33 and #42
I20251230 15:17:57.011248     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:57.013052     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:57.014127     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:57.028839     1 incremental_pipeline.cc:335] Registering initial image pair #5 and #6
I20251230 15:17:57.029173     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:57.037730     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:57.038766     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:57.053534     1 incremental_pipeline.cc:335] Registering initial image pair #33 and #48
I20251230 15:17:57.053900     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:57.062017     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:57.063019     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:57.077363     1 incremental_pipeline.cc:335] Registering initial image pair #26 and #15
I20251230 15:17:57.077642     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:17:57.077730     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:17:57.077744     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:17:57.077802     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:57.078997     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:57.092983     1 incremental_pipeline.cc:335] Registering initial image pair #10 and #21
I20251230 15:17:57.093322     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:57.104799     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:57.105858     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:57.128875     1 incremental_pipeline.cc:335] Registering initial image pair #10 and #40
I20251230 15:17:57.129180     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:17:57.129244     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:17:57.129254     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:17:57.129287     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:57.130257     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:57.159475     1 incremental_pipeline.cc:335] Registering initial image pair #26 and #68
I20251230 15:17:57.159817     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:57.160573     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:57.171507     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:57.186141     1 incremental_pipeline.cc:335] Registering initial image pair #51 and #6
I20251230 15:17:57.191499     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:17:57.191594     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:17:57.191607     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:17:57.191644     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:57.192637     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:57.213088     1 incremental_pipeline.cc:335] Registering initial image pair #61 and #56
I20251230 15:17:57.213402     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:17:57.213476     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:17:57.213490     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:17:57.213541     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:57.214774     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:57.231176     1 incremental_pipeline.cc:335] Registering initial image pair #13 and #62
I20251230 15:17:57.231467     1 incremental_pipeline.cc:349] Global bundle adjustment
I20251230 15:17:57.231787     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:57.232795     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:57.289466     1 incremental_pipeline.cc:335] Registering initial image pair #13 and #3
I20251230 15:17:57.289696     1 incremental_pipeline.cc:349] Global bundle adjustment
W20251230 15:17:57.289753     1 bundle_adjustment.cc:583] Failed to fix Gauge with two cameras. Falling back to fixing Gauge with three points.
W20251230 15:17:57.289760     1 bundle_adjustment.cc:489] Failed to fix Gauge due to insufficient number of fixed points: 0
I20251230 15:17:57.289803     1 incremental_pipeline.cc:569] Discarding reconstruction due to bad initial pair
I20251230 15:17:57.291190     1 incremental_pipeline.cc:311] Finding good initial image pair
I20251230 15:17:57.307489     1 incremental_pipeline.cc:335] Registering initial image pair #44 and #62

[ok] pt_sacrecoeur_trevi_tajmahal/cluster_0003: sparse model ready at /home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_sacrecoeur_trevi_tajmahal_cluster_0003/sparse/1
[cluster] 7/8: pt_stpeters_stpauls/cluster_0001
[run] pt_stpeters_stpauls/cluster_0001: images=101 matcher=dino
[dino] build db=/home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/outputs/ablation_holdout_ets_sacrecoeur_stpeters/sfm_matcher_compare/recon_dino/pt_stpeters_stpauls_cluster_0001/colmap_dino.db images=101 pairing=auto topk=10
[dino] cache_dir=cache/dino_features
[dino] model=facebook/dinov2-small layer=last max_side=512 fp16=True
[dino] matcher: keypoints=patch max_keypoints=2048 min_similarity=0.75 min_inliers=15
[warn] --single-camera requested but image sizes differ [(462, 621), (489, 489), (490, 490), (491, 491), (502, 375), (511, 379), (586, 786), (622, 462), (672, 1004), (679, 1028), (680, 1020), (684, 1030), (688, 1046), (689, 1050), (762, 1017), (779, 1053), (780, 1055), (812, 604), (815, 605), (816, 606), (819, 1010), (870, 643), (980, 658), (997, 665), (1000, 665), (1007, 568), (1011, 758), (1014, 758), (1015, 570), (1015, 571), (1017, 675), (1017, 678), (1017, 762), (1018, 572), (1018, 678), (1020, 765), (1023, 682), (1025, 661), (1028, 681), (1028, 683), (1028, 698), (1029, 683), (1030, 770), (1031, 684), (1031, 767), (1031, 770), (1032, 685), (1032, 770), (1033, 771), (1033, 800), (1035, 683), (1036, 684), (1037, 683), (1039, 577), (1039, 687), (1040, 774), (1042, 687), (1042, 775), (1043, 775), (1044, 775), (1045, 688), (1045, 776), (1046, 686), (1046, 688), (1046, 776), (1047, 776), (1047, 777), (1048, 689), (1048, 777), (1049, 689), (1049, 692), (1049, 694), (1051, 778), (1052, 579), (1052, 688), (1052, 779), (1053, 779), (1054, 783), (1055, 691), (1055, 780), (1056, 565), (1056, 691), (1057, 691), (1058, 691), (1058, 781), (1062, 693), (1063, 782), (1066, 694), (1072, 695)]; using per-image cameras.
[dino] using preloaded model on device=cuda patch=14
[dino] image 1/101: st_pauls_cathedral_22051479_11389229645.png
[dino] extracting: st_pauls_cathedral_22051479_11389229645.png
[dino] cached: st_pauls_cathedral_22051479_11389229645.png
[dino] image 2/101: st_peters_square_01086691_5427945640.png
[dino] extracting: st_peters_square_01086691_5427945640.png
[dino] cached: st_peters_square_01086691_5427945640.png
[dino] image 3/101: st_peters_square_01113045_2151200754.png
[dino] extracting: st_peters_square_01113045_2151200754.png
[dino] cached: st_peters_square_01113045_2151200754.png
[dino] image 4/101: st_peters_square_03091803_3301752366.png
[dino] extracting: st_peters_square_03091803_3301752366.png
[dino] cached: st_peters_square_03091803_3301752366.png
[dino] image 5/101: st_peters_square_03746789_4463922325.png
[dino] extracting: st_peters_square_03746789_4463922325.png
[dino] cached: st_peters_square_03746789_4463922325.png
[dino] image 6/101: st_peters_square_03988695_8001663418.png
[dino] extracting: st_peters_square_03988695_8001663418.png
[dino] cached: st_peters_square_03988695_8001663418.png
[dino] image 7/101: st_peters_square_04610226_4103646673.png
[dino] extracting: st_peters_square_04610226_4103646673.png
[dino] cached: st_peters_square_04610226_4103646673.png
[dino] image 8/101: st_peters_square_04687924_2163037290.png
[dino] extracting: st_peters_square_04687924_2163037290.png
[dino] cached: st_peters_square_04687924_2163037290.png
[dino] image 9/101: st_peters_square_05036686_9559490324.png
[dino] extracting: st_peters_square_05036686_9559490324.png
[dino] cached: st_peters_square_05036686_9559490324.png
[dino] image 10/101: st_peters_square_05894880_3961210476.png
[dino] extracting: st_peters_square_05894880_3961210476.png
[dino] cached: st_peters_square_05894880_3961210476.png
[dino] image 11/101: st_peters_square_07459783_2116496273.png
[dino] extracting: st_peters_square_07459783_2116496273.png
[dino] cached: st_peters_square_07459783_2116496273.png
[dino] image 12/101: st_peters_square_09150846_12806538585.png
[dino] extracting: st_peters_square_09150846_12806538585.png
[dino] cached: st_peters_square_09150846_12806538585.png
[dino] image 13/101: st_peters_square_11170243_108218811.png
[dino] extracting: st_peters_square_11170243_108218811.png
[dino] cached: st_peters_square_11170243_108218811.png
[dino] image 14/101: st_peters_square_12334689_522974921.png
[dino] extracting: st_peters_square_12334689_522974921.png
[dino] cached: st_peters_square_12334689_522974921.png
[dino] image 15/101: st_peters_square_14434211_3241927710.png
[dino] extracting: st_peters_square_14434211_3241927710.png
[dino] cached: st_peters_square_14434211_3241927710.png
[dino] image 16/101: st_peters_square_16459160_169609859.png
[dino] extracting: st_peters_square_16459160_169609859.png
[dino] cached: st_peters_square_16459160_169609859.png
[dino] image 17/101: st_peters_square_16560660_87393276.png
[dino] extracting: st_peters_square_16560660_87393276.png
[dino] cached: st_peters_square_16560660_87393276.png
[dino] image 18/101: st_peters_square_17992917_296706864.png
[dino] extracting: st_peters_square_17992917_296706864.png
[dino] cached: st_peters_square_17992917_296706864.png
[dino] image 19/101: st_peters_square_18412179_6172244512.png
[dino] extracting: st_peters_square_18412179_6172244512.png
[dino] cached: st_peters_square_18412179_6172244512.png
[dino] image 20/101: st_peters_square_18948310_1391071648.png
[dino] extracting: st_peters_square_18948310_1391071648.png
[dino] cached: st_peters_square_18948310_1391071648.png
[dino] image 21/101: st_peters_square_20328156_5873219320.png
[dino] extracting: st_peters_square_20328156_5873219320.png
[dino] cached: st_peters_square_20328156_5873219320.png
[dino] image 22/101: st_peters_square_21905075_5452965061.png
[dino] extracting: st_peters_square_21905075_5452965061.png
[dino] cached: st_peters_square_21905075_5452965061.png
[dino] image 23/101: st_peters_square_22421524_4050930227.png
[dino] extracting: st_peters_square_22421524_4050930227.png
[dino] cached: st_peters_square_22421524_4050930227.png
[dino] image 24/101: st_peters_square_22746486_9560856076.png
[dino] extracting: st_peters_square_22746486_9560856076.png
[dino] cached: st_peters_square_22746486_9560856076.png
[dino] image 25/101: st_peters_square_24059795_9603235434.png
[dino] extracting: st_peters_square_24059795_9603235434.png
[dino] cached: st_peters_square_24059795_9603235434.png
[dino] image 26/101: st_peters_square_24636762_4089050891.png
[dino] extracting: st_peters_square_24636762_4089050891.png
[dino] cached: st_peters_square_24636762_4089050891.png
[dino] image 27/101: st_peters_square_24719115_774461939.png
[dino] extracting: st_peters_square_24719115_774461939.png
[dino] cached: st_peters_square_24719115_774461939.png
[dino] image 28/101: st_peters_square_27722146_2540992403.png
[dino] extracting: st_peters_square_27722146_2540992403.png
[dino] cached: st_peters_square_27722146_2540992403.png
[dino] image 29/101: st_peters_square_27821246_220471245.png
[dino] extracting: st_peters_square_27821246_220471245.png
[dino] cached: st_peters_square_27821246_220471245.png
[dino] image 30/101: st_peters_square_29679303_181377461.png
[dino] extracting: st_peters_square_29679303_181377461.png
[dino] cached: st_peters_square_29679303_181377461.png
[dino] image 31/101: st_peters_square_32164473_4104406816.png
[dino] extracting: st_peters_square_32164473_4104406816.png
[dino] cached: st_peters_square_32164473_4104406816.png
[dino] image 32/101: st_peters_square_33011793_12700964863.png
[dino] extracting: st_peters_square_33011793_12700964863.png
[dino] cached: st_peters_square_33011793_12700964863.png
[dino] image 33/101: st_peters_square_33563670_5242619236.png
[dino] extracting: st_peters_square_33563670_5242619236.png
[dino] cached: st_peters_square_33563670_5242619236.png
[dino] image 34/101: st_peters_square_35727766_2927321004.png
[dino] extracting: st_peters_square_35727766_2927321004.png
[dino] cached: st_peters_square_35727766_2927321004.png
[dino] image 35/101: st_peters_square_36268301_7354161880.png
[dino] extracting: st_peters_square_36268301_7354161880.png
[dino] cached: st_peters_square_36268301_7354161880.png
[dino] image 36/101: st_peters_square_37466637_151112376.png
[dino] extracting: st_peters_square_37466637_151112376.png
[dino] cached: st_peters_square_37466637_151112376.png
[dino] image 37/101: st_peters_square_40696807_2666761892.png
[dino] extracting: st_peters_square_40696807_2666761892.png
[dino] cached: st_peters_square_40696807_2666761892.png
[dino] image 38/101: st_peters_square_41659819_2070196997.png
[dino] extracting: st_peters_square_41659819_2070196997.png
[dino] cached: st_peters_square_41659819_2070196997.png
[dino] image 39/101: st_peters_square_43335638_88784147.png
[dino] extracting: st_peters_square_43335638_88784147.png
[dino] cached: st_peters_square_43335638_88784147.png
[dino] image 40/101: st_peters_square_44390759_5115213112.png
[dino] extracting: st_peters_square_44390759_5115213112.png
[dino] cached: st_peters_square_44390759_5115213112.png
[dino] image 41/101: st_peters_square_44455970_5746646894.png
[dino] extracting: st_peters_square_44455970_5746646894.png
[dino] cached: st_peters_square_44455970_5746646894.png
[dino] image 42/101: st_peters_square_44478569_2733152198.png
[dino] extracting: st_peters_square_44478569_2733152198.png
[dino] cached: st_peters_square_44478569_2733152198.png
[dino] image 43/101: st_peters_square_45146398_300508266.png
[dino] extracting: st_peters_square_45146398_300508266.png
[dino] cached: st_peters_square_45146398_300508266.png
[dino] image 44/101: st_peters_square_45336170_8518744916.png
[dino] extracting: st_peters_square_45336170_8518744916.png
[dino] cached: st_peters_square_45336170_8518744916.png
[dino] image 45/101: st_peters_square_46268845_5210431.png
[dino] extracting: st_peters_square_46268845_5210431.png
[dino] cached: st_peters_square_46268845_5210431.png
[dino] image 46/101: st_peters_square_46663883_6534848061.png
[dino] extracting: st_peters_square_46663883_6534848061.png
[dino] cached: st_peters_square_46663883_6534848061.png
[dino] image 47/101: st_peters_square_47361588_602059416.png
[dino] extracting: st_peters_square_47361588_602059416.png
[dino] cached: st_peters_square_47361588_602059416.png
[dino] image 48/101: st_peters_square_48141965_9536256202.png
[dino] extracting: st_peters_square_48141965_9536256202.png
[dino] cached: st_peters_square_48141965_9536256202.png
[dino] image 49/101: st_peters_square_48496249_4257721183.png
[dino] extracting: st_peters_square_48496249_4257721183.png
[dino] cached: st_peters_square_48496249_4257721183.png
[dino] image 50/101: st_peters_square_50829067_6827571714.png
[dino] extracting: st_peters_square_50829067_6827571714.png
[dino] cached: st_peters_square_50829067_6827571714.png
[dino] image 51/101: st_peters_square_51093586_7936643532.png
[dino] extracting: st_peters_square_51093586_7936643532.png
[dino] cached: st_peters_square_51093586_7936643532.png
[dino] image 52/101: st_peters_square_51383333_4555047040.png
[dino] extracting: st_peters_square_51383333_4555047040.png
[dino] cached: st_peters_square_51383333_4555047040.png
[dino] image 53/101: st_peters_square_55218853_3759440157.png
[dino] extracting: st_peters_square_55218853_3759440157.png
[dino] cached: st_peters_square_55218853_3759440157.png
[dino] image 54/101: st_peters_square_56468077_4089051561.png
[dino] extracting: st_peters_square_56468077_4089051561.png
[dino] cached: st_peters_square_56468077_4089051561.png
[dino] image 55/101: st_peters_square_57090695_8548496597.png
[dino] extracting: st_peters_square_57090695_8548496597.png
[dino] cached: st_peters_square_57090695_8548496597.png
[dino] image 56/101: st_peters_square_57954696_5417448065.png
[dino] extracting: st_peters_square_57954696_5417448065.png
[dino] cached: st_peters_square_57954696_5417448065.png
[dino] image 57/101: st_peters_square_58474381_9559488022.png
[dino] extracting: st_peters_square_58474381_9559488022.png
[dino] cached: st_peters_square_58474381_9559488022.png
[dino] image 58/101: st_peters_square_58475035_2122656414.png
[dino] extracting: st_peters_square_58475035_2122656414.png
[dino] cached: st_peters_square_58475035_2122656414.png
[dino] image 59/101: st_peters_square_60121796_5502368748.png
[dino] extracting: st_peters_square_60121796_5502368748.png
[dino] cached: st_peters_square_60121796_5502368748.png
[dino] image 60/101: st_peters_square_60793175_3515361889.png
[dino] extracting: st_peters_square_60793175_3515361889.png
[dino] cached: st_peters_square_60793175_3515361889.png
[dino] image 61/101: st_peters_square_60887425_4988344850.png
[dino] extracting: st_peters_square_60887425_4988344850.png
[dino] cached: st_peters_square_60887425_4988344850.png
[dino] image 62/101: st_peters_square_61199489_492461058.png
[dino] extracting: st_peters_square_61199489_492461058.png
[dino] cached: st_peters_square_61199489_492461058.png
[dino] image 63/101: st_peters_square_61596216_926981615.png
[dino] extracting: st_peters_square_61596216_926981615.png
[dino] cached: st_peters_square_61596216_926981615.png
[dino] image 64/101: st_peters_square_64157046_4825759910.png
[dino] extracting: st_peters_square_64157046_4825759910.png
[dino] cached: st_peters_square_64157046_4825759910.png
[dino] image 65/101: st_peters_square_64605808_5986711471.png
[dino] extracting: st_peters_square_64605808_5986711471.png
[dino] cached: st_peters_square_64605808_5986711471.png
[dino] image 66/101: st_peters_square_64856605_10034558183.png
[dino] extracting: st_peters_square_64856605_10034558183.png
[dino] cached: st_peters_square_64856605_10034558183.png
[dino] image 67/101: st_peters_square_67407966_4358094261.png
[dino] extracting: st_peters_square_67407966_4358094261.png
[dino] cached: st_peters_square_67407966_4358094261.png
[dino] image 68/101: st_peters_square_70326181_5251675186.png
[dino] extracting: st_peters_square_70326181_5251675186.png
[dino] cached: st_peters_square_70326181_5251675186.png
[dino] image 69/101: st_peters_square_70611917_5987268232.png
[dino] extracting: st_peters_square_70611917_5987268232.png
[dino] cached: st_peters_square_70611917_5987268232.png
[dino] image 70/101: st_peters_square_71743967_13589039945.png
[dino] extracting: st_peters_square_71743967_13589039945.png
[dino] cached: st_peters_square_71743967_13589039945.png
[dino] image 71/101: st_peters_square_71826517_5746260945.png
[dino] extracting: st_peters_square_71826517_5746260945.png
[dino] cached: st_peters_square_71826517_5746260945.png
[dino] image 72/101: st_peters_square_72710271_9087579115.png
[dino] extracting: st_peters_square_72710271_9087579115.png
[dino] cached: st_peters_square_72710271_9087579115.png
[dino] image 73/101: st_peters_square_72862254_5114619647.png
[dino] extracting: st_peters_square_72862254_5114619647.png
[dino] cached: st_peters_square_72862254_5114619647.png
[dino] image 74/101: st_peters_square_73950904_275489778.png
[dino] extracting: st_peters_square_73950904_275489778.png
[dino] cached: st_peters_square_73950904_275489778.png
[dino] image 75/101: st_peters_square_74059884_5303611340.png
[dino] extracting: st_peters_square_74059884_5303611340.png
[dino] cached: st_peters_square_74059884_5303611340.png
[dino] image 76/101: st_peters_square_74375638_1347790951.png
[dino] extracting: st_peters_square_74375638_1347790951.png
[dino] cached: st_peters_square_74375638_1347790951.png
[dino] image 77/101: st_peters_square_77282490_453023076.png
[dino] extracting: st_peters_square_77282490_453023076.png
[dino] cached: st_peters_square_77282490_453023076.png
[dino] image 78/101: st_peters_square_78236367_3680548187.png
[dino] extracting: st_peters_square_78236367_3680548187.png
[dino] cached: st_peters_square_78236367_3680548187.png
[dino] image 79/101: st_peters_square_79673014_480541710.png
[dino] extracting: st_peters_square_79673014_480541710.png
[dino] cached: st_peters_square_79673014_480541710.png
[dino] image 80/101: st_peters_square_79705761_286952048.png
[dino] extracting: st_peters_square_79705761_286952048.png
[dino] cached: st_peters_square_79705761_286952048.png
[dino] image 81/101: st_peters_square_80363066_1340868362.png
[dino] extracting: st_peters_square_80363066_1340868362.png
[dino] cached: st_peters_square_80363066_1340868362.png
[dino] image 82/101: st_peters_square_84026672_4257874044.png
[dino] extracting: st_peters_square_84026672_4257874044.png
[dino] cached: st_peters_square_84026672_4257874044.png
[dino] image 83/101: st_peters_square_84278273_4258469058.png
[dino] extracting: st_peters_square_84278273_4258469058.png
[dino] cached: st_peters_square_84278273_4258469058.png
[dino] image 84/101: st_peters_square_84356787_41289007.png
[dino] extracting: st_peters_square_84356787_41289007.png
[dino] cached: st_peters_square_84356787_41289007.png
[dino] image 85/101: st_peters_square_84897883_3397284524.png
[dino] extracting: st_peters_square_84897883_3397284524.png
[dino] cached: st_peters_square_84897883_3397284524.png
[dino] image 86/101: st_peters_square_85112064_8554016061.png
[dino] extracting: st_peters_square_85112064_8554016061.png
[dino] cached: st_peters_square_85112064_8554016061.png
[dino] image 87/101: st_peters_square_85174888_2795417037.png
[dino] extracting: st_peters_square_85174888_2795417037.png
[dino] cached: st_peters_square_85174888_2795417037.png
[dino] image 88/101: st_peters_square_87967653_2756655360.png
[dino] extracting: st_peters_square_87967653_2756655360.png
[dino] cached: st_peters_square_87967653_2756655360.png
[dino] image 89/101: st_peters_square_89231283_4583657302.png
[dino] extracting: st_peters_square_89231283_4583657302.png
[dino] cached: st_peters_square_89231283_4583657302.png
[dino] image 90/101: st_peters_square_91440455_2973906531.png
[dino] extracting: st_peters_square_91440455_2973906531.png
[dino] cached: st_peters_square_91440455_2973906531.png
[dino] image 91/101: st_peters_square_92930792_3241113575.png
[dino] extracting: st_peters_square_92930792_3241113575.png
[dino] cached: st_peters_square_92930792_3241113575.png
[dino] image 92/101: st_peters_square_93827329_275493871.png
[dino] extracting: st_peters_square_93827329_275493871.png
[dino] cached: st_peters_square_93827329_275493871.png
[dino] image 93/101: st_peters_square_93849170_8602630853.png
[dino] extracting: st_peters_square_93849170_8602630853.png
[dino] cached: st_peters_square_93849170_8602630853.png
[dino] image 94/101: st_peters_square_94126033_8728856148.png
[dino] extracting: st_peters_square_94126033_8728856148.png
[dino] cached: st_peters_square_94126033_8728856148.png
[dino] image 95/101: st_peters_square_94275623_8588288449.png
[dino] extracting: st_peters_square_94275623_8588288449.png
[dino] cached: st_peters_square_94275623_8588288449.png
[dino] image 96/101: st_peters_square_95260621_11241567214.png
[dino] extracting: st_peters_square_95260621_11241567214.png
[dino] cached: st_peters_square_95260621_11241567214.png
[dino] image 97/101: st_peters_square_95364400_2795430893.png
[dino] extracting: st_peters_square_95364400_2795430893.png
[dino] cached: st_peters_square_95364400_2795430893.png
[dino] image 98/101: st_peters_square_95709487_7541298516.png
[dino] extracting: st_peters_square_95709487_7541298516.png
[dino] cached: st_peters_square_95709487_7541298516.png
[dino] image 99/101: st_peters_square_96944137_5746647680.png
[dino] extracting: st_peters_square_96944137_5746647680.png
[dino] cached: st_peters_square_96944137_5746647680.png
[dino] image 100/101: st_peters_square_96961885_104769206.png
[dino] extracting: st_peters_square_96961885_104769206.png
[dino] cached: st_peters_square_96961885_104769206.png
[dino] image 101/101: st_peters_square_97299190_230228215.png
[dino] extracting: st_peters_square_97299190_230228215.png

Traceback (most recent call last):
  File "/home/shamika/documents/prog_workspace/ml_imc25/ImageMatchingChallenge2025/scripts/colmap_dense_clusters.py", line 16, in <module>

KeyboardInterrupt: